-- Anmelde-Schema: Voranmeldung, Anmeldegespräch und Schulvertrag (Domäne 2/4,
-- fachdomaenen.md Abschnitt 6) samt den Querschnitts-Entitäten Zustimmung (Q1)
-- und Dokument/Signatur (Q2) und der Erweiterung des Zahlungsvorgangs (Q3).
-- Konzeptioneller Entwurf zu domains/anmeldung.md und domains/grenzkarte.md —
-- konkreter als Prosa, aber noch kein Alembic-Migrationscode.
--
-- SETZT domains/stammdaten-schema.sql UND domains/putzdienst-schema.sql VORAUS
-- und wird nach beiden geladen: es referenziert children/persons/grade_levels
-- und erweitert die dort gebaute payments-Tabelle. Es nutzt außerdem
-- set_row_audit() samt app.actor-Präfixregel aus Stammdaten; eine zweite
-- Audit-Variante gibt es bewusst nicht.
--
-- Stammdaten sind ab dem Vollimport eingefroren (domains/grenzkarte.md, „Freeze
-- der Stammdaten"). Dieses Schema hält sich daran: es legt in Stammdaten Zeilen
-- an und ändert sie (das ist sein Zweck, fachdomaenen.md Abschnitt 6), aber es
-- ändert dort keine einzige Spalte, keinen Typ und keinen Constraint.
--
-- id-Typ wie in den beiden anderen Schemata: uuid, wo eine Zeile in einer
-- Eltern-URL auftauchen kann (Bewerbung, Vertragsvorgang, Zustimmung, Dokument,
-- Signatur, Betreuungsbuchung), integer-Identity für die rein intern gepflegten
-- Verwaltungs- und Wertelisten.
--
-- ZWEI STRUKTURENTSCHEIDUNGEN, aus denen der Rest folgt:
--
--   1. Die Personenzeilen entstehen bei der VORANMELDUNG, nicht erst bei der
--      Aufnahme. Drei Gründe, von denen jeder allein trägt: Personendaten haben
--      genau ein Zuhause und werden nie kopiert (domains/grenzkarte.md, Regel 2)
--      — eine Bewerbung mit eigenen Namens-, Geburts- und Adressfeldern wäre
--      genau diese Kopie; der OTP-Zugang, die jährliche Wartelisten-Rückfrage
--      und die persönlichen Vertragslinks brauchen alle eine Personenidentität,
--      und die Warteliste läuft über Jahre; und die Dublettenvermeidung ist eine
--      Auswahl aus bekannten Personen, kein Abgleich (TODO-SESSIONS.md).
--      Preis: Bewerbungen, die nie zur Aufnahme führen, hinterlassen
--      Personenzeilen. Sie sind daran erkennbar, dass children.entry_date leer
--      ist und alle Bewerbungen des Kindes in einem Endstatus stehen — eine
--      Abfrage des Lösch-Jobs, keine Spalte (idea/06-dsgvo-organisatorisch.md).
--
--   2. Die Zeilen entstehen beim ABSENDEN, nicht erst nach der
--      Zahlungsbestätigung. Die Alternative hieße, den Formularinhalt bis zur
--      Bestätigung zwischenzuparken — also dieselben Personendaten an einem
--      zweiten Ort mit eigener Aufbewahrung und eigenem Leserkreis. Ein
--      abgebrochener Zahlungsvorgang hinterlässt stattdessen eine Bewerbung mit
--      offener Zahlung, die derselbe Lösch-Job aufräumt.
--
-- Was hier bewusst NICHT steht:
--   * Keine Personenfelder an der Bewerbung (Begründung oben).
--   * Keine Wartelisten-Entität und kein Rangfeld darin. Die Warteliste ist ein
--     Status samt jährlich fortgeschriebener Zielklassenstufe; bei einem frei
--     werdenden Platz entscheidet ein Mensch neu (domains/grenzkarte.md).
--   * Keine Bewertungszeile je Lehrkraft. Festgehalten wird das konsolidierte
--     Ergebnis — mehrere konkurrierende Urteile ohne definierten Sieger gibt es
--     im realen Verfahren nicht (domains/grenzkarte.md, „Bewertung").
--   * Keine Geschwister-Namensliste. Gebraucht werden nur zwei Tatsachen: ob
--     Geschwister an der Schule sind und wie viele es insgesamt sind.
--   * Kein Gesundheitsmerkmal. Der Schulvertrag erhebt den Satz, geführt wird er
--     aber in Domäne 9 mit eigenem Zugriffsprofil; hier steht nur die
--     Zustimmung (Q1) und das signierte Blatt (Q2).
--   * Kein Kindergarten in previous_schools. Der trägt die staatlichen
--     Überweisungspartner; der Kindergarten bekommt seine eigene Werteliste
--     (domains/grenzkarte.md, „Zwei Schulen, nicht eine").
--   * Keine Frist-Prüfung als Constraint. Die 14-Tage-Frist des Vertrags und die
--     Fälligkeiten der Buchung sind Ablauflogik, kein Datenzustand.

-- ---------------------------------------------------------------------------
-- Wertelisten
-- ---------------------------------------------------------------------------

-- Kindergarten der abgebenden Seite bei der Grundschul-Voranmeldung. Eigene
-- Liste und NICHT previous_schools: die trägt die staatlichen
-- Überweisungspartner, ein Kindergarten darin verschöbe die Bedeutung einer
-- bestehenden Stammdaten-Spalte (domains/grenzkarte.md).
CREATE TABLE kindergartens (
    kindergarten_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           text NOT NULL UNIQUE CHECK (label <> '')
);

-- Empfehlung des Kindergartens: Einschulung oder Zurückstellung. Werteliste
-- statt CHECK, wie jede Kategorie in diesem Projekt (rules.md Abschnitt 3) —
-- eine dritte Ausprägung ist damit eine Zeile statt einer Migration.
CREATE TABLE kindergarten_recommendations (
    kindergarten_recommendation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                          text NOT NULL UNIQUE CHECK (label <> '')
);

-- Schulpflicht-Einstufung des Kindes: schulpflichtig, Kann-Kind, zurückgestellt.
-- Die Einstufung wird gespeichert und nicht bei jeder Anzeige neu gerechnet: sie
-- ist eine Entscheidung, kein Rechenergebnis — ein schulpflichtiges Kind kann
-- zurückgestellt werden (domains/anmeldung.md).
CREATE TABLE enrollment_categories (
    enrollment_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                  text NOT NULL UNIQUE CHECK (label <> '')
);

-- Stichtage, aus denen die Oberfläche die Einstufung VORSCHLÄGT. Als Daten und
-- nicht im Code, weil die Schule ausdrücklich sagt, dass sie sich immer mal
-- wieder ändern (rules.md Abschnitt 3, prozesse.md Abschnitt 5.3). Aktuell: wer
-- bis zum 30.06. sechs wird, ist schulpflichtig; ab dem 01.07. Kann-Kind.
-- Je Zielschuljahr eine Zeile — ein geänderter Stichtag gilt nie rückwirkend
-- für ein bereits laufendes Verfahren.
CREATE TABLE enrollment_cutoffs (
    enrollment_cutoff_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year          text NOT NULL UNIQUE CHECK (school_year <> ''),   -- z. B. "2027/28"
    cutoff_on            date NOT NULL,
    compulsory_age       smallint NOT NULL CHECK (compulsory_age BETWEEN 4 AND 10),
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           text NOT NULL,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    updated_by           text NOT NULL
);

-- Angebote, deren Wahrnehmung bei der Zusage einen Bonus gibt (Musikarche,
-- Ferienprogramm, Clemens-KITA). Selbstauskunft im Formular, deshalb eine
-- Werteliste und kein Verweis auf echte Buchungen: ein Ferienprogramm-Besuch von
-- vor drei Jahren steht in keiner Buchungstabelle, die noch existiert.
CREATE TABLE school_programs (
    school_program_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> '')
);

-- Status der Bewerbung. Trägt den gesamten Lebenslauf und ersetzt drei
-- naheliegende Zusatzentitäten: Warteliste, Absage und der Rücktritt vor dem
-- ersten Schultag sind Ausprägungen dieses Feldes (domains/grenzkarte.md).
--
-- Zwei nicht umbenennbare Kennzeichen daneben, gleiche Bauform wie
-- cleaning_duty_types.is_major: is_waitlist steuert die jährliche
-- Fortschreibung, is_final beendet das Verfahren und startet die Löschfrist.
-- Beide dürfen sich nicht ändern, wenn jemand das Label umbenennt.
CREATE TABLE application_statuses (
    application_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                 text NOT NULL UNIQUE CHECK (label <> ''),
    is_waitlist           boolean NOT NULL DEFAULT false,
    is_final              boolean NOT NULL DEFAULT false,
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            text NOT NULL,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    updated_by            text NOT NULL,
    -- Ein Status kann nicht zugleich „wartet" und „ist abgeschlossen" sein.
    CONSTRAINT application_statuses_waitlist_not_final_check
        CHECK (NOT (is_waitlist AND is_final))
);

-- Schulart-Niveau: Hauptschule, Realschule, Gymnasium. EINE Liste für ZWEI
-- Spalten der Bewerbung — die amtliche Grundschulempfehlung und die eigene
-- Einschätzung aus Gespräch und Testblättern (Begründung an applications).
CREATE TABLE school_recommendations (
    school_recommendation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                    text NOT NULL UNIQUE CHECK (label <> '')
);

-- Konsolidierte Einschätzung „passt zur Schule": Zusage / Eher Ja / Eher Nein /
-- Absage. sort_order, weil die Reihenfolge fachlich ist und nicht alphabetisch.
CREATE TABLE fit_assessments (
    fit_assessment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> ''),
    sort_order        smallint NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Q1 — Zustimmung
-- ---------------------------------------------------------------------------

-- Zweck einer Zustimmung: Schulvertrag, Gesundheitsdaten, Fotoeinverständnis,
-- Informationsaustausch Hort↔Schule, Werbung, Lastschrift-Erlaubnis.
CREATE TABLE consent_purposes (
    consent_purpose_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label              text NOT NULL UNIQUE CHECK (label <> '')
);

-- Wer hat wann wozu zugestimmt, über welche Zustelladresse, und wurde es
-- widerrufen (domains/grenzkarte.md, Q1).
--
-- Die Zustelladresse gehört zwingend dazu und ist NICHT aus persons.email
-- ableitbar: zwei Erziehungsberechtigte dürfen sich eine Mailbox teilen
-- (domains/stammdaten.md, „Geteilte Mailbox"), und nur mit festgehaltener
-- Adresse ist hinterher auswertbar, ob zwei Zustimmungen über dasselbe Postfach
-- kamen. Ebenso wenig ableitbar ist sie aus der Login-Identität — die
-- Oberflächen-Abfrage „als wer sind Sie angemeldet" ist Bedienführung, keine
-- Sicherheitsgrenze (idea/04-identitaet-zugriff.md).
--
-- person_id ist eine beliebige persons-Zeile und nicht auf Erziehungsberechtigte
-- eingeschränkt: ab 14 Jahren muss das Kind beim Fotoeinverständnis selbst
-- zustimmen.
--
-- child_id nullable, weil nicht jede Zustimmung ein Kind betrifft (Werbung an
-- den anmeldenden Elternteil). Das UNIQUE ist deshalb NULLS NOT DISTINCT: sonst
-- ließe sich dieselbe kindlose Zustimmung beliebig oft anlegen, weil NULL in
-- einem gewöhnlichen UNIQUE zu sich selbst ungleich ist.
--
-- Keine Zustimmungshistorie: revoked_at ersetzt den Zustand, ein erneutes
-- Erteilen überschreibt dieselbe Zeile — wie überall in diesem Projekt.
CREATE TABLE consents (
    consent_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id          uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    child_id           uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    consent_purpose_id integer NOT NULL REFERENCES consent_purposes(consent_purpose_id) ON DELETE RESTRICT,
    -- Zeitpunkt statt Boolean wegen der Nachweispflicht aus Art. 7 Abs. 1 DSGVO,
    -- dieselbe Bauform wie children.previous_school_consent_at.
    granted_at         timestamptz NOT NULL DEFAULT now(),
    delivery_email     citext NOT NULL CHECK (delivery_email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    revoked_at         timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    UNIQUE NULLS NOT DISTINCT (person_id, child_id, consent_purpose_id),
    CONSTRAINT consents_revoked_after_granted_check
        CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);
CREATE INDEX ON consents (child_id);

-- ---------------------------------------------------------------------------
-- Q2 — Dokument und Signatur
-- ---------------------------------------------------------------------------

CREATE TABLE document_types (
    document_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            text NOT NULL UNIQUE CHECK (label <> '')
);

-- Dokument: Typ, Bezug, Ablageort, Erzeugungszeitpunkt. Bewusst NICHT mit Q1
-- verschmolzen — eine Zustimmung kann ohne Dokument existieren (Häkchen), und
-- ein Dokument trägt oft mehrere Zustimmungen (ein Schulvertrag, zwei
-- Unterschriften).
--
-- DIE DATEI SELBST BLEIBT IN SHAREPOINT, hier steht nur die Referenz
-- (domains/grenzkarte.md, Q2). Zwei Folgen, die nicht übersehen werden dürfen:
-- der pg_dump-Backupumfang bleibt unverändert, und der Lösch-Job muss die Datei
-- dort mitentfernen — eine verwaiste Datei in SharePoint ist genauso ein
-- DSGVO-Verstoß wie eine verwaiste Zeile, und sie fällt niemandem auf.
--
-- Bezug ist entweder ein Kind (Geburtsurkunde, Zeugnis) oder eine Bewerbung
-- (Schulvertrag, Gesundheitsblatt, SEPA-Mandat des Vorgangs) — genau eines von
-- beidem, getragen vom Fremdschlüssel statt von einem Typ-Feld daneben, wie bei
-- payments. Der Vertragsvorgang braucht keinen eigenen Bezug, weil er 1:1 an
-- der Bewerbung hängt.
CREATE TABLE documents (
    document_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_type_id integer NOT NULL REFERENCES document_types(document_type_id) ON DELETE RESTRICT,
    child_id         uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    application_id   uuid,   -- Fremdschlüssel per ALTER TABLE unten (applications wird danach definiert)
    storage_path     text NOT NULL CHECK (storage_path <> ''),
    created_on       date NOT NULL DEFAULT current_date,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    CONSTRAINT documents_exactly_one_subject_check
        CHECK ((child_id IS NOT NULL)::int + (application_id IS NOT NULL)::int = 1)
);
CREATE INDEX ON documents (child_id);

-- Signatur: Person × Dokument × Zeitpunkt × Signaturbild × Niveau.
-- Niveau als Spalte und nicht als Werteliste: es gibt heute durchgängig genau
-- eine Stufe (einfache elektronische Signatur), und eine Liste mit einer Zeile
-- wäre ein Mechanismus ohne Bedarf (rules.md Abschnitt 1). Kommt eine zweite
-- Stufe, ist das eine Werteliste und keine Umdeutung dieser Spalte.
CREATE TABLE signatures (
    signature_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     uuid NOT NULL REFERENCES documents(document_id) ON DELETE RESTRICT,
    person_id       uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    signed_at       timestamptz NOT NULL DEFAULT now(),
    image_path      text CHECK (image_path <> ''),
    signature_level text NOT NULL DEFAULT 'EES' CHECK (signature_level <> ''),
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    -- Dieselbe Person unterschreibt dasselbe Dokument einmal.
    UNIQUE (document_id, person_id)
);
CREATE INDEX ON signatures (person_id);

-- Eine Zustimmung zeigt optional auf die Signatur, die sie belegt. Nachgezogen,
-- weil consents vor signatures steht: das Häkchen ohne Dokument ist der
-- Regelfall, die belegte Zustimmung die Ausnahme.
ALTER TABLE consents ADD COLUMN signature_id uuid REFERENCES signatures(signature_id) ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------
-- Gesprächstermine
-- ---------------------------------------------------------------------------

-- Ein Anmeldetag je Schulzweig: das Raster, aus dem die Slots entstehen.
-- Wochentag, Zeitfenster, Mittagspause und Kinder je Stunde sind DATEN und
-- keine Konstanten — die zuständigen Personen setzen sie selbst, weil sie sich
-- immer wieder ändern und die Sondertermine heute ohnehin niemand vollständig
-- kennt (prozesse.md Abschnitt 5.1). Der heutige Stand ist damit ein
-- Ausgangswert und keine Regel im Code.
CREATE TABLE interview_days (
    interview_day_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(school_branch_id) ON DELETE RESTRICT,
    school_year      text NOT NULL CHECK (school_year <> ''),
    day_on           date NOT NULL,
    starts_at        time NOT NULL,
    ends_at          time NOT NULL,
    break_starts_at  time,
    break_ends_at    time,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, day_on),
    CONSTRAINT interview_days_period_check CHECK (ends_at > starts_at),
    -- Pause gilt nur ganz oder gar nicht, und sie liegt innerhalb des Tages.
    CONSTRAINT interview_days_break_complete_check
        CHECK ((break_starts_at IS NULL) = (break_ends_at IS NULL)),
    CONSTRAINT interview_days_break_within_day_check
        CHECK (break_starts_at IS NULL
               OR (break_ends_at > break_starts_at
                   AND break_starts_at >= starts_at AND break_ends_at <= ends_at))
);

-- Konkreter buchbarer Slot. Eigene Zeilen statt einer Berechnung aus dem Raster:
-- eine Buchung braucht ein stabiles Ziel, das auch dann noch dasselbe meint,
-- wenn jemand die Pause des Tages verschiebt.
--
-- Kapazität am Slot, weil real 4–5 Kinder je Stunde verarbeitet werden und die
-- Zahl je Tag schwankt. Sie ist hier eine harte Obergrenze für die
-- Selbstbuchung durch die Eltern — anders als beim Putzdienst, wo die Kapazität
-- berechnet wird und das Sekretariat sie überschreiten darf.
CREATE TABLE interview_slots (
    interview_slot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_day_id  integer NOT NULL REFERENCES interview_days(interview_day_id) ON DELETE RESTRICT,
    starts_at         time NOT NULL,
    capacity          smallint NOT NULL CHECK (capacity > 0),
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    UNIQUE (interview_day_id, starts_at)
);

-- ---------------------------------------------------------------------------
-- Bewerbung
-- ---------------------------------------------------------------------------

-- Die Bewerbung ZEIGT auf Kind und Familie, statt Personendaten zu kopieren
-- (Kopfkommentar, Entscheidung 1). Sie trägt nur, was die Bewerbung selbst
-- betrifft.
--
-- Mehrere Bewerbungen je Kind sind der Normalfall, nicht der Ausnahmefall: der
-- Wechsel von der eigenen Grundschule in die eigene Realschule ist eine zweite
-- Bewerbung desselben Kindes, und eine abgelehnte Bewerbung kann im Folgejahr
-- wiederholt werden. Deshalb UNIQUE nur je Kind und Zielschuljahr.
--
-- registration_date steht daneben an children und ist keine Doppelung: das
-- Anmeldedatum überlebt die Bewerbung, die eine kürzere Löschfrist hat
-- (domains/stammdaten.md, „Felder").
CREATE TABLE applications (
    application_id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    child_id                   uuid NOT NULL REFERENCES children(child_id) ON DELETE RESTRICT,
    application_status_id      integer NOT NULL REFERENCES application_statuses(application_status_id) ON DELETE RESTRICT,
    -- Ziel der Bewerbung. Die Klassenstufe wird bei Wartelistenfällen jährlich
    -- fortgeschrieben (Klasse 5 → Klasse 6), das Zielschuljahr ebenso — deshalb
    -- zwei Spalten und keine Ableitung aus dem Anmeldedatum.
    target_school_year         text NOT NULL CHECK (target_school_year <> ''),
    target_grade_level_id      integer NOT NULL REFERENCES grade_levels(grade_level_id) ON DELETE RESTRICT,
    -- Quereinstieg ist ein eigener Ablauf (ganzjährig, Platzprüfung vor dem
    -- Gespräch) und kein Nebeneffekt der Zielklassenstufe: ableitbar wäre er nur
    -- über ein Kennzeichen „Eingangsklassenstufe" an grade_levels, das es dort
    -- nicht gibt und für das eine eingefrorene Stammdaten-Tabelle nicht
    -- aufgemacht wird.
    is_lateral_entry           boolean NOT NULL DEFAULT false,
    submitted_on               date NOT NULL DEFAULT current_date,
    -- Wer das Formular ausgefüllt hat und die Bestätigung, dass der andere
    -- Elternteil informiert ist — beides steht so auf dem realen Formular.
    filled_by_person_id        uuid REFERENCES persons(person_id) ON DELETE RESTRICT,
    other_parent_informed      boolean NOT NULL DEFAULT false,
    attended_info_evening      boolean NOT NULL DEFAULT false,
    -- Geschwister als Selbstauskunft, weil es bei externen Bewerbern noch keine
    -- Familie gibt, aus der es folgen könnte. Bei der Aufnahme löst es sich
    -- gegen families auf. Bewusst ohne Namensliste (Kopfkommentar).
    siblings_at_school         boolean NOT NULL DEFAULT false,
    sibling_count              smallint CHECK (sibling_count >= 0),
    interested_in_care         boolean NOT NULL DEFAULT false,
    -- Grundschulseite: Kindergarten samt Rücksprache-Erlaubnis und Empfehlung.
    -- Die Erlaubnis ist wie children.previous_school_consent_at ein einmaliges,
    -- sofort verbrauchtes Einverständnis (also NICHT Q1), steht aber an der
    -- Bewerbung und nicht am Kind: die abgebende Schule wird über den
    -- Anmeldetag hinaus gebraucht, der Kindergarten nicht.
    kindergarten_id            integer REFERENCES kindergartens(kindergarten_id) ON DELETE RESTRICT,
    kindergarten_consent_at    timestamptz,
    kindergarten_recommendation_id integer REFERENCES kindergarten_recommendations(kindergarten_recommendation_id) ON DELETE RESTRICT,
    enrollment_category_id     integer REFERENCES enrollment_categories(enrollment_category_id) ON DELETE RESTRICT,
    -- Realschulseite: die amtliche Grundschulempfehlung der abgebenden Schule.
    -- ZWEI Felder mit derselben Werteliste, solange nicht bestätigt ist, dass es
    -- dasselbe ist (domains/grenzkarte.md, „Bewertung"): dies ist das Dokument
    -- der abgebenden Schule, own_recommendation_id unten die eigene Einschätzung
    -- aus Gespräch und Testblättern. Sind es zwei Namen für dieselbe Angabe,
    -- bleibt eine Spalte leer — der billigere Irrtum, denn ein Feld für zwei
    -- Sachverhalte verlöre gerade den interessanten Fall, dass beide
    -- auseinandergehen.
    primary_school_recommendation_id integer REFERENCES school_recommendations(school_recommendation_id) ON DELETE RESTRICT,
    -- Gesprächstermin. Nullable: die Voranmeldung läuft Monate vor der
    -- Terminvergabe.
    interview_slot_id          integer REFERENCES interview_slots(interview_slot_id) ON DELETE RESTRICT,
    -- --- Bewertung: engstes Zugriffsprofil im System nach den Art.-9-Daten -----
    -- Vier Spalten, kein eigenes Zugriffssystem: sie bekommen ein eigenes
    -- Spalten-GRANT auf dieser Tabelle (wie die Konfessionsspalten an children),
    -- und sie sind standardmäßig NICHT breit sichtbar. Die Lehrer-Checkliste
    -- bleibt Papier und wird nach dem Verfahren vernichtet; hier landet nur das
    -- konsolidierte Ergebnis samt weniger Notizen (prozesse.md Abschnitt 5.2).
    fit_assessment_id          integer REFERENCES fit_assessments(fit_assessment_id) ON DELETE RESTRICT,
    own_recommendation_id      integer REFERENCES school_recommendations(school_recommendation_id) ON DELETE RESTRICT,
    -- Rangnummer nur für die Grenzfälle der Entscheidungsrunde; klare Zusagen
    -- und klare Absagen brauchen keine. Nach der Entscheidung liest sie niemand
    -- mehr — sie bleibt als Beleg, wie entschieden wurde.
    rank_number                smallint CHECK (rank_number > 0),
    assessment_notes           text CHECK (assessment_notes <> ''),
    -- --- Ende Bewertung -------------------------------------------------------
    -- EIN Freitextfeld für den Bearbeitungsstand, bewusst nicht zwei: die
    -- Trennung zwischen „Bemerkung" und „Stand" wird im Alltag nicht eingehalten
    -- (domains/grenzkarte.md). Kein Notiz-Verlauf, solange niemand danach sucht.
    processing_note            text CHECK (processing_note <> ''),
    -- Zusammensetzungswunsch für die Klassenbildung — real drei Kinder je
    -- Jahrgang. Eine Kind-zu-Kind-Verknüpfung mit Richtung und Gegenseitigkeit
    -- dafür zu bauen wäre ein Mechanismus ohne Bedarf (domains/grenzkarte.md,
    -- „Klassenbildung").
    class_placement_wish       text CHECK (class_placement_wish <> ''),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    created_by                 text NOT NULL,
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    updated_by                 text NOT NULL,
    UNIQUE (child_id, target_school_year),
    -- Eine Geschwisterzahl von 0 verträgt sich nicht mit „Geschwister an der
    -- Schule": beides zusammen ist ein Ausfüllfehler, kein Sonderfall.
    -- Name bewusst nicht "applications_sibling_count_check": den vergibt
    -- Postgres bereits automatisch für den Spalten-CHECK an sibling_count, und
    -- zwei Constraints desselben Namens gibt es nicht.
    CONSTRAINT applications_siblings_at_school_count_check
        CHECK (NOT siblings_at_school OR coalesce(sibling_count, 1) > 0),
    -- Eine Rücksprache-Erlaubnis ohne Kindergarten hat keinen Adressaten.
    CONSTRAINT applications_kindergarten_consent_requires_kindergarten_check
        CHECK (kindergarten_consent_at IS NULL OR kindergarten_id IS NOT NULL)
);
CREATE INDEX ON applications (child_id);
CREATE INDEX ON applications (application_status_id);
CREATE INDEX ON applications (interview_slot_id);
-- „Alle Bewerbungen dieses Zielschuljahrs samt Stufe" ist die Arbeitsliste der
-- Entscheidungsrunde und der jährlichen Fortschreibung.
CREATE INDEX ON applications (target_school_year, target_grade_level_id);

ALTER TABLE documents ADD FOREIGN KEY (application_id) REFERENCES applications(application_id) ON DELETE RESTRICT;
CREATE INDEX ON documents (application_id);

-- Wahrgenommene Angebote: M:N, weil mehrere gleichzeitig zutreffen.
CREATE TABLE application_programs (
    application_id    uuid NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    school_program_id integer NOT NULL REFERENCES school_programs(school_program_id) ON DELETE RESTRICT,
    PRIMARY KEY (application_id, school_program_id)
);

-- ---------------------------------------------------------------------------
-- Schulvertrag
-- ---------------------------------------------------------------------------

-- Der Vertragsvorgang beginnt mit der Zusage und endet mit der Bestätigungsmail.
-- 1:1 zur Bewerbung (UNIQUE), aber eigene Zeile und keine Spalten an der
-- Bewerbung: er hat einen eigenen Lebenslauf mit vier Stationen, von denen drei
-- nach dem Absenden der Eltern liegen, und die meisten Bewerbungen erreichen ihn
-- nie.
--
-- Die vier Zeitpunkte sind bewusst Zeitpunkte und kein Statusfeld: sie treten
-- immer in dieser Reihenfolge ein, und „wann war das" ist die Frage, die im
-- Nachhinein gestellt wird (domains/anmeldung.md).
CREATE TABLE contracts (
    contract_id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id        uuid NOT NULL UNIQUE REFERENCES applications(application_id) ON DELETE RESTRICT,
    -- Frist für die Eltern, real 14 Tage ab Versand. Als Datum und nicht als
    -- Dauer, weil das Sekretariat sie im Einzelfall verlängert.
    deadline_on           date NOT NULL,
    secretariat_checked_at timestamptz,
    headmaster_released_at timestamptz,
    confirmation_sent_at   timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            text NOT NULL,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    updated_by            text NOT NULL,
    -- Die Reihenfolge ist Teil des Verfahrens: erst prüft das Sekretariat, dann
    -- gibt die Schulleitung frei, dann geht die Bestätigung raus. Eine
    -- Bestätigungsmail vor der Freigabe wäre genau der Fehler, der an dieser
    -- Schule niemandem auffiele.
    CONSTRAINT contracts_release_after_check_check
        CHECK (headmaster_released_at IS NULL OR secretariat_checked_at IS NOT NULL),
    CONSTRAINT contracts_confirmation_after_release_check
        CHECK (confirmation_sent_at IS NULL OR headmaster_released_at IS NOT NULL)
);

-- Antwort je Erziehungsberechtigtem. Eigene Zeilen und kein Feld am Vertrag,
-- weil Mutter und Vater je einen eigenen persönlichen Link bekommen und
-- UNTERSCHIEDLICH antworten können — sagt einer ja und der andere nein, wird das
-- Sekretariat benachrichtigt und klärt telefonisch (prozesse.md Abschnitt 7.1).
-- Genau dieser Konflikt ist an einem einzelnen Vertragsfeld nicht darstellbar.
--
-- Die Stammdatenbestätigung steht daneben: jeder bestätigt seine EIGENEN Daten,
-- die des Kindes bestätigen beide — deshalb zwei Zeitpunkte je Zeile und nicht
-- einer.
CREATE TABLE contract_responses (
    contract_id             uuid NOT NULL REFERENCES contracts(contract_id) ON DELETE CASCADE,
    person_id               uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    accepted                boolean,
    responded_at            timestamptz,
    own_data_confirmed_at   timestamptz,
    child_data_confirmed_at timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    created_by              text NOT NULL,
    updated_at              timestamptz NOT NULL DEFAULT now(),
    updated_by              text NOT NULL,
    PRIMARY KEY (contract_id, person_id),
    -- Eine Antwort ohne Zeitpunkt ist keine, und ein Zeitpunkt ohne Antwort
    -- ebenso wenig.
    CONSTRAINT contract_responses_answer_complete_check
        CHECK ((accepted IS NULL) = (responded_at IS NULL))
);
CREATE INDEX ON contract_responses (person_id);

-- ---------------------------------------------------------------------------
-- Betreuungsmodule (Hortvertrag)
-- ---------------------------------------------------------------------------

-- Katalog der buchbaren Module: Frühbetreuung, vier Nachmittagsvarianten, Hort
-- nach Mittagschule (prozesse.md Abschnitt 8). Werteliste, weil die Schule
-- Module streicht und ergänzt, ohne dass eine Migration nötig sein darf.
--
-- school_branch_id nullable: „Hort nach Mittagschule" gilt nur für die
-- Realschule, alle übrigen für beide Zweige. NULL heißt also „ohne
-- Einschränkung" und nicht „unbekannt".
CREATE TABLE care_modules (
    care_module_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> ''),
    school_branch_id  integer REFERENCES school_branches(school_branch_id) ON DELETE RESTRICT,
    -- Zeiten als Text und nicht als time-Spalten: der reale Katalog beginnt
    -- überwiegend bei „Schulende" und nicht zu einer Uhrzeit, und diese Angabe
    -- steht im Formular, wird aber von keiner Abfrage ausgewertet.
    time_description  text NOT NULL CHECK (time_description <> ''),
    includes_homework boolean NOT NULL DEFAULT false,
    sort_order        smallint NOT NULL UNIQUE,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL
);

-- Gebuchtes Modul für ein Kind, mit eigenem Gültigkeitszeitraum.
--
-- Hängt am KIND und nicht am Vertragsvorgang: der Hort nimmt auch Kinder auf,
-- die weder Grund- noch Realschüler sind (prozesse.md Abschnitt 8) — für sie
-- gibt es keine Bewerbung, aber eine Buchung. contract_id bleibt deshalb
-- nullable und sagt nur, aus welchem Anmeldevorgang die Buchung entstanden ist.
--
-- valid_until trägt die automatische Kündigung: bis Ende Klasse 4, ein Vertrag
-- für Klasse 5 gilt nur für Klasse 5, mit Klasse 5 endet das Angebot. Als Datum
-- und nicht als Regel im Code, weil die Schule die Grenzen verschiebt.
CREATE TABLE care_module_bookings (
    care_module_booking_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    child_id               uuid NOT NULL REFERENCES children(child_id) ON DELETE RESTRICT,
    care_module_id         integer NOT NULL REFERENCES care_modules(care_module_id) ON DELETE RESTRICT,
    contract_id            uuid REFERENCES contracts(contract_id) ON DELETE RESTRICT,
    valid_from             date NOT NULL,
    valid_until            date,
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             text NOT NULL,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    updated_by             text NOT NULL,
    UNIQUE (child_id, care_module_id, valid_from),
    CONSTRAINT care_module_bookings_period_check
        CHECK (valid_until IS NULL OR valid_until >= valid_from)
);
CREATE INDEX ON care_module_bookings (child_id);

-- Die Buchungseinheit ist Modul × Wochentag, nicht das Modul allein: je Modul
-- werden die einzelnen Tage gewählt (prozesse.md Abschnitt 8). Deshalb eine
-- eigene Zeile je Tag und keine sieben Boolean-Spalten — ein Wochentag mehr oder
-- weniger ist damit ein Datensatz.
CREATE TABLE care_module_booking_days (
    care_module_booking_id uuid NOT NULL REFERENCES care_module_bookings(care_module_booking_id) ON DELETE CASCADE,
    -- ISO-8601: 1 = Montag … 5 = Freitag. Betreuung am Wochenende gibt es nicht,
    -- und ein Tippfehler „7" wäre sonst eine stille Buchung ins Leere.
    weekday                smallint NOT NULL CHECK (weekday BETWEEN 1 AND 5),
    PRIMARY KEY (care_module_booking_id, weekday)
);

-- ---------------------------------------------------------------------------
-- Q3 — Zahlungsvorgang erweitern
-- ---------------------------------------------------------------------------

-- Die Anmeldegebühr ist der dritte Stripe-Anlass (domains/grenzkarte.md, Q3).
-- Sie kommt als weitere nullable Vorgangs-Spalte samt erweitertem
-- Entweder-oder-CHECK an die bestehende Tabelle — nicht als zweite
-- Zahlungstabelle: der Fremdschlüssel trägt die Unterscheidung, und genau die
-- referenzielle Integrität ist der Grund, Q3 überhaupt einmal zu bauen.
ALTER TABLE payments
    ADD COLUMN application_id uuid UNIQUE REFERENCES applications(application_id) ON DELETE RESTRICT;

ALTER TABLE payments DROP CONSTRAINT payments_exactly_one_subject_check;
ALTER TABLE payments ADD CONSTRAINT payments_exactly_one_subject_check
    CHECK ((cleaning_buyout_id IS NOT NULL)::int
         + (cleaning_slot_buyout_id IS NOT NULL)::int
         + (application_id IS NOT NULL)::int = 1);

-- ---------------------------------------------------------------------------
-- Audit-Trigger
-- ---------------------------------------------------------------------------
-- Nur auf Tabellen mit Audit-Spalten: die reinen Wertelisten ohne eigenen
-- Lebenslauf (kindergartens, school_programs, …) tragen keine, wie in Stammdaten.
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON enrollment_cutoffs
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON application_statuses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON consents
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON documents
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON signatures
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON interview_days
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON interview_slots
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON applications
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contracts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contract_responses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON care_modules
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON care_module_bookings
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
