-- Anmelde-Schema: Voranmeldung, Anmeldegespräch und Schulvertrag (Domäne 2/4,
-- fachdomaenen.md Abschnitt 6) samt den Querschnitts-Entitäten Zustimmung (Q1)
-- und Dokument/Signatur (Q2) und der Erweiterung des Zahlungsvorgangs (Q3).
-- Konzeptioneller Entwurf zu domains/anmeldung.md und domains/grenzkarte.md —
-- konkreter als Prosa, aber noch kein Alembic-Migrationscode.
--
-- SETZT domains/stammdaten-schema.sql UND domains/putzdienst-schema.sql VORAUS
-- und wird nach beiden geladen: es referenziert children/persons/grade_levels
-- und erweitert die dort gebaute payments-Tabelle. Es nutzt außerdem
-- set_row_audit() samt app.actor-Präfixregel aus Stammdaten; eine zweite
-- Audit-Variante gibt es bewusst nicht.
--
-- Stammdaten sind ab dem Vollimport eingefroren (domains/grenzkarte.md, „Freeze
-- der Stammdaten"). Dieses Schema hält sich daran: es legt in Stammdaten Zeilen
-- an und ändert sie (das ist sein Zweck, fachdomaenen.md Abschnitt 6), aber es
-- ändert dort keine einzige Spalte, keinen Typ und keinen Constraint.
--
-- id-Typ wie in den beiden anderen Schemata: uuid, wo eine Zeile in einer
-- Eltern-URL auftauchen kann (Bewerbung, Vertragsvorgang, Zustimmung, Dokument,
-- Signatur, Betreuungsbuchung), integer-Identity für die rein intern gepflegten
-- Verwaltungs- und Wertelisten.
--
-- ZWEI STRUKTURENTSCHEIDUNGEN, aus denen der Rest folgt:
--
--   1. Die Personenzeilen entstehen bei der VORANMELDUNG, nicht erst bei der
--      Aufnahme. Drei Gründe, von denen jeder allein trägt: Personendaten haben
--      genau ein Zuhause und werden nie kopiert (domains/grenzkarte.md, Regel 2)
--      — eine Bewerbung mit eigenen Namens-, Geburts- und Adressfeldern wäre
--      genau diese Kopie; der OTP-Zugang, die jährliche Wartelisten-Rückfrage
--      und die persönlichen Vertragslinks brauchen alle eine Personenidentität,
--      und die Warteliste läuft über Jahre; und die Dublettenvermeidung ist eine
--      Auswahl aus bekannten Personen, kein Abgleich (TODO-SESSIONS.md).
--      Preis: Bewerbungen, die nie zur Aufnahme führen, hinterlassen
--      Personenzeilen. Sie sind daran erkennbar, dass children.entry_date leer
--      ist und alle Bewerbungen des Kindes in einem Endstatus stehen — eine
--      Abfrage des Lösch-Jobs, keine Spalte (idea/06-dsgvo-organisatorisch.md).
--
--   2. Die Zeilen entstehen beim ABSENDEN, nicht erst nach der
--      Zahlungsbestätigung. Die Alternative hieße, den Formularinhalt bis zur
--      Bestätigung zwischenzuparken — also dieselben Personendaten an einem
--      zweiten Ort mit eigener Aufbewahrung und eigenem Leserkreis. Ein
--      abgebrochener Zahlungsvorgang hinterlässt stattdessen eine Bewerbung mit
--      offener Zahlung, die derselbe Lösch-Job aufräumt.
--
-- Was hier bewusst NICHT steht:
--   * Keine Personenfelder an der Bewerbung (Begründung oben).
--   * Keine Wartelisten-Entität und kein Rangfeld darin. Die Warteliste ist ein
--     Status samt jährlich fortgeschriebener Zielklassenstufe; bei einem frei
--     werdenden Platz entscheidet ein Mensch neu (domains/grenzkarte.md).
--   * Keine Bewertungszeile je Lehrkraft. Festgehalten wird das konsolidierte
--     Ergebnis — mehrere konkurrierende Urteile ohne definierten Sieger gibt es
--     im realen Verfahren nicht (domains/grenzkarte.md, „Bewertung").
--   * Keine Geschwister-Namensliste. Gebraucht werden nur zwei Tatsachen: ob
--     Geschwister an der Schule sind und wie viele es insgesamt sind.
--   * Kein Gesundheitsmerkmal. Der Schulvertrag erhebt den Satz, geführt wird er
--     aber in Domäne 9 mit eigenem Zugriffsprofil; hier steht nur die
--     Zustimmung (Q1) und das signierte Blatt (Q2).
--   * Kein Kindergarten in previous_schools. Der trägt die staatlichen
--     Überweisungspartner; der Kindergarten bekommt seine eigene Werteliste
--     (domains/grenzkarte.md, „Zwei Schulen, nicht eine").
--   * Keine Frist-Prüfung als Constraint. Die 14-Tage-Frist des Vertrags und die
--     Fälligkeiten der Buchung sind Ablauflogik, kein Datenzustand — ebenso die
--     harte Sperre der Voranmeldung: offen/zu ist ein Backend-Vergleich gegen
--     application_windows, kein Constraint.

-- ---------------------------------------------------------------------------
-- Wertelisten
-- ---------------------------------------------------------------------------

-- Kindergarten der abgebenden Seite bei der Grundschul-Voranmeldung. Eigene
-- Liste und NICHT previous_schools: die trägt die staatlichen
-- Überweisungspartner, ein Kindergarten darin verschöbe die Bedeutung einer
-- bestehenden Stammdaten-Spalte (domains/grenzkarte.md).
CREATE TABLE kindergartens (
    kindergarten_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           text NOT NULL UNIQUE CHECK (label <> '')
);

-- Empfehlung des Kindergartens: Einschulung oder Zurückstellung. Werteliste
-- statt CHECK, wie jede Kategorie in diesem Projekt (rules.md Abschnitt 3) —
-- eine dritte Ausprägung ist damit eine Zeile statt einer Migration.
CREATE TABLE kindergarten_recommendations (
    kindergarten_recommendation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                          text NOT NULL UNIQUE CHECK (label <> '')
);

-- Schulpflicht-Einstufung des Kindes: schulpflichtig, Kann-Kind, zurückgestellt.
-- Die Einstufung wird gespeichert und nicht bei jeder Anzeige neu gerechnet: sie
-- ist eine Entscheidung, kein Rechenergebnis — ein schulpflichtiges Kind kann
-- zurückgestellt werden (domains/anmeldung.md).
CREATE TABLE enrollment_categories (
    enrollment_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                  text NOT NULL UNIQUE CHECK (label <> '')
);

-- Stichtage, aus denen die Oberfläche die Einstufung VORSCHLÄGT. Als Daten und
-- nicht im Code, weil die Schule ausdrücklich sagt, dass sie sich immer mal
-- wieder ändern (rules.md Abschnitt 3, prozesse.md Abschnitt 5.3). Aktuell: wer
-- bis zum 30.06. sechs wird, ist schulpflichtig; ab dem 01.07. Kann-Kind.
-- Je Zielschuljahr eine Zeile — ein geänderter Stichtag gilt nie rückwirkend
-- für ein bereits laufendes Verfahren.
-- school_year überall in diesem Schema mit demselben Formatprüf-CHECK
-- (JJJJ/JJ, z. B. "2027/28"). Nötig, weil das Schuljahr hier ein TRAGENDER
-- Verbindungswert ist und kein Anzeigetext: die Oberfläche findet den Stichtag
-- einer Bewerbung, indem sie applications.target_school_year gegen diese Spalte
-- hält. Ein Fremdschlüssel darauf wäre falsch — eine Bewerbung darf existieren,
-- bevor jemand den Stichtag des Jahrgangs gepflegt hat —, aber ohne
-- Formatprüfung liefen "2027/28", "2027/2028" und "27/28" nebeneinander und der
-- Vergleich fände still nichts: keine Fehlermeldung, nur ein fehlender
-- Vorschlag, und die Einstufung wird ungeprüft von Hand gesetzt. Stammdaten hat
-- für dieselbe Tatsache dieselbe Entscheidung getroffen (classes.entry_year,
-- vierstellig gegen Mehrdeutigkeit).
CREATE TABLE enrollment_cutoffs (
    enrollment_cutoff_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year          text NOT NULL UNIQUE CHECK (school_year ~ '^[0-9]{4}/[0-9]{2}$'),   -- z. B. "2027/28"
    cutoff_on            date NOT NULL,
    compulsory_age       smallint NOT NULL CHECK (compulsory_age BETWEEN 4 AND 10),
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           text NOT NULL,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    updated_by           text NOT NULL
);

-- Anmeldefenster der Voranmeldung je Zweig und Zielschuljahr — das Gegenstück
-- zu cleaning_cycles (Putzdienst) und programs.booking_closes_at (Ferien).
-- Beides sind organisatorische Werte, die sich zyklisch ändern, und gehören
-- deshalb als Daten hierher, nicht in Code oder Deploy-Konfiguration (rules.md
-- Abschnitt 3): die Anmeldung wird real je Schule dynamisch geschlossen —
-- Zeitpunkt hängt an der Bewerberzahl, teils blieb sie bis Juni offen
-- (prozesse.md Abschnitt 3.1) — und je Zweig, weil Grund- und Realschule nicht
-- am selben Tag schließen. Deshalb eine Zeile je Zweig × Schuljahr, nicht je
-- Schuljahr.
--
-- Das Fenster trägt die gewünschte HARTE SPERRE (prozesse.md Abschnitt 3.4):
-- offen/zu ist ein Vergleich des Backends gegen diese Zeile, kein Constraint —
-- der benannte legitime Ausweg ist der einzelne Nachmeldelink des Sekretariats
-- in die reguläre Voranmeldung, ein Vorgang und kein Datenzustand. Der
-- Quereinstieg (applications.is_lateral_entry) läuft ganzjährig am Fenster
-- vorbei; seine Gebühr liest er trotzdem hier, aus der Zeile seines Zieljahrs.
--
-- fee ist die Anmeldegebühr, gezahlt beim Absenden (prozesse.md Abschnitt 3.1);
-- payments.amount bleibt wie beim Putzdienst die Kopie zum Zahlungszeitpunkt.
-- Je Zweig ein eigener Betrag, auch wenn beide heute gleich sein mögen: zwei
-- einzeln gesetzte Entscheidungen, keine Ableitung — dieselbe Abwägung wie
-- buyout_amount/slot_buyout_amount am Putzdienst-Zyklus.
--
-- Kein Fremdschlüssel von applications hierher — eine Bewerbung darf
-- existieren, bevor jemand das Fenster des Jahrgangs gepflegt hat (Nachmeldung,
-- Quereinstieg), dieselbe Entscheidung wie bei enrollment_cutoffs; die
-- Verbindung läuft über (school_branch_id, school_year). Und anders als beim
-- Putzdienst-Buchungsfenster kein Überlappungs-Constraint: die Bewerbung
-- benennt ihr Zieljahr selbst, „wofür wird gerade gebucht" ist hier nie
-- mehrdeutig — zwei gleichzeitig offene Fenster (beide Zweige, zwei Jahrgänge)
-- sind der Normalfall, kein Fehler.
CREATE TABLE application_windows (
    application_window_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id      integer NOT NULL REFERENCES school_branches(school_branch_id) ON DELETE RESTRICT,
    school_year           text NOT NULL CHECK (school_year ~ '^[0-9]{4}/[0-9]{2}$'),  -- Format begruendet an enrollment_cutoffs
    opens_at              timestamptz NOT NULL,
    closes_at             timestamptz NOT NULL,
    fee                   numeric(8,2) NOT NULL CHECK (fee >= 0),
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            text NOT NULL,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    updated_by            text NOT NULL,
    UNIQUE (school_branch_id, school_year),
    CONSTRAINT application_windows_period_check CHECK (closes_at > opens_at)
);

-- Angebote, deren Wahrnehmung bei der Zusage einen Bonus gibt (Musikarche,
-- Ferienprogramm, Clemens-KITA). Selbstauskunft im Formular, deshalb eine
-- Werteliste und kein Verweis auf echte Buchungen: ein Ferienprogramm-Besuch von
-- vor drei Jahren steht in keiner Buchungstabelle, die noch existiert.
CREATE TABLE school_programs (
    school_program_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> '')
);

-- Status der Bewerbung. Trägt den gesamten Lebenslauf und ersetzt drei
-- naheliegende Zusatzentitäten: Warteliste, Absage und der Rücktritt vor dem
-- ersten Schultag sind Ausprägungen dieses Feldes (domains/grenzkarte.md).
--
-- Zwei nicht umbenennbare Kennzeichen daneben, gleiche Bauform wie
-- cleaning_duty_types.is_major: is_waitlist steuert die jährliche
-- Fortschreibung, is_final beendet das Verfahren und startet die Löschfrist.
-- Beide dürfen sich nicht ändern, wenn jemand das Label umbenennt.
CREATE TABLE application_statuses (
    application_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                 text NOT NULL UNIQUE CHECK (label <> ''),
    is_waitlist           boolean NOT NULL DEFAULT false,
    is_final              boolean NOT NULL DEFAULT false,
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            text NOT NULL,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    updated_by            text NOT NULL,
    -- Ein Status kann nicht zugleich „wartet" und „ist abgeschlossen" sein.
    CONSTRAINT application_statuses_waitlist_not_final_check
        CHECK (NOT (is_waitlist AND is_final))
);

-- Schulart-Niveau: Hauptschule, Realschule, Gymnasium. EINE Liste für ZWEI
-- Spalten der Bewerbung — die amtliche Grundschulempfehlung und die eigene
-- Einschätzung aus Gespräch und Testblättern (Begründung an applications).
CREATE TABLE school_recommendations (
    school_recommendation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label                    text NOT NULL UNIQUE CHECK (label <> '')
);

-- Konsolidierte Einschätzung „passt zur Schule": Zusage / Eher Ja / Eher Nein /
-- Absage. sort_order, weil die Reihenfolge fachlich ist und nicht alphabetisch.
CREATE TABLE fit_assessments (
    fit_assessment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> ''),
    sort_order        smallint NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Q1 — Zustimmung
-- ---------------------------------------------------------------------------

-- Zweck einer Zustimmung: Schulvertrag, Gesundheitsdaten, Fotoeinverständnis,
-- Zeckenentfernung, Informationsaustausch Hort↔Schule, Werbung,
-- Lastschrift-Erlaubnis.
--
-- Die Zeckenentfernung steht hier und nicht als Spalte in Domäne 9: sie ist
-- eine Erlaubnis und kein Merkmal des Kindes (domains/gesundheit.md). Sie gilt
-- dem KIND und nicht einem einzelnen Merkmal — das ist der Unterschied zur
-- Verabreichungserlaubnis, die deshalb an health_traits bleibt.
--
-- code neben dem frei umbenennbaren label, dasselbe Muster wie
-- genders/countries/languages in Stammdaten — nur ist der Abnehmer hier kein
-- Export, sondern das Systemverhalten, das an einzelnen Zwecken hängt: die
-- breit lesbare Fotoeinverständnis-Ansicht filtert genau den Foto-Zweck
-- (domains/grenzkarte.md, Q1), der Werbemail-Versand den Werbe-Zweck, und die
-- Vertrags- und Ferienstrecken legen Zustimmungen bestimmter Zwecke an. Auf dem
-- label aufgesetzt bräche all das still, sobald jemand „Fotoeinverständnis"
-- umbenennt — dieselbe Falle, gegen die application_statuses seine beiden
-- Kennzeichen trägt. Geseedet, nicht über die Oberfläche gepflegt; kommt wie
-- die drei Stammdaten-Codes nicht ins Schreibrecht der Laufzeit-Rolle.
CREATE TABLE consent_purposes (
    consent_purpose_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label              text NOT NULL UNIQUE CHECK (label <> ''),
    code               text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{0,31}$')  -- z. B. "photo", "advertising"
);

-- Wer hat wann wozu geantwortet — erteilt oder abgelehnt —, über welche
-- Zustelladresse, und wurde eine Erteilung widerrufen (domains/grenzkarte.md,
-- Q1).
--
-- Die ABLEHNUNG ist eine eigene Antwort und keine fehlende Zeile: das
-- Fotoeinverständnis „kann angenommen oder abgelehnt werden" (prozesse.md
-- Abschnitt 7.1), und ohne Zeile wäre „abgelehnt" nicht von „noch nicht
-- beantwortet" zu unterscheiden — für die Vollständigkeitsprüfung des
-- Sekretariats dieselbe Unterscheidung zwischen entschieden und vergessen wie
-- cleaning_slots.attendance_recorded_at beim Putzdienst. Für den Leser der
-- breiten Foto-Ansicht ändert sich nichts: nur eine nicht widerrufene
-- Erteilung zählt als Ja.
--
-- Die Zustelladresse gehört zwingend dazu und ist NICHT aus persons.email
-- ableitbar: zwei Erziehungsberechtigte dürfen sich eine Mailbox teilen
-- (domains/stammdaten.md, „Geteilte Mailbox"), und nur mit festgehaltener
-- Adresse ist hinterher auswertbar, ob zwei Zustimmungen über dasselbe Postfach
-- kamen. Ebenso wenig ableitbar ist sie aus der Login-Identität — die
-- Oberflächen-Abfrage „als wer sind Sie angemeldet" ist Bedienführung, keine
-- Sicherheitsgrenze (idea/04-identitaet-zugriff.md).
--
-- person_id ist eine beliebige persons-Zeile und nicht auf Erziehungsberechtigte
-- eingeschränkt: ab 14 Jahren muss das Kind beim Fotoeinverständnis selbst
-- zustimmen.
--
-- child_id nullable, weil nicht jede Zustimmung ein Kind betrifft (Werbung an
-- den anmeldenden Elternteil). Das UNIQUE ist deshalb NULLS NOT DISTINCT: sonst
-- ließe sich dieselbe kindlose Zustimmung beliebig oft anlegen, weil NULL in
-- einem gewöhnlichen UNIQUE zu sich selbst ungleich ist.
--
-- Keine Zustimmungshistorie: revoked_at ersetzt den Zustand, ein erneutes
-- Erteilen überschreibt dieselbe Zeile — wie überall in diesem Projekt. Ebenso
-- wird eine Ablehnung nicht widerrufen, sondern durch eine spätere Erteilung
-- überschrieben (declined_at auf NULL, granted_at gesetzt).
CREATE TABLE consents (
    consent_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id          uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    child_id           uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    consent_purpose_id integer NOT NULL REFERENCES consent_purposes(consent_purpose_id) ON DELETE RESTRICT,
    -- Zeitpunkt statt Boolean wegen der Nachweispflicht aus Art. 7 Abs. 1 DSGVO,
    -- dieselbe Bauform wie children.previous_school_consent_at. Genau eine der
    -- beiden Spalten ist gesetzt (CHECK unten): erteilt oder abgelehnt — eine
    -- Zeile ohne Antwort gibt es nicht, „noch nicht beantwortet" ist die
    -- fehlende Zeile.
    -- granted_at bewusst OHNE Default: mit DEFAULT now() würde ein
    -- Ablehnungs-INSERT, der die Spalte schlicht weglässt, still zu einer
    -- Erteilung.
    granted_at         timestamptz,
    declined_at        timestamptz,
    -- Auch die Ablehnung kam über eine Adresse und bleibt nachweisbar — die
    -- Zustelladresse ist deshalb für beide Antworten Pflicht.
    delivery_email     citext NOT NULL CHECK (delivery_email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    revoked_at         timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    UNIQUE NULLS NOT DISTINCT (person_id, child_id, consent_purpose_id),
    CONSTRAINT consents_answer_present_check
        CHECK ((granted_at IS NULL) <> (declined_at IS NULL)),
    -- Widerrufen wird nur eine Erteilung; eine Ablehnung ist bereits das Nein.
    CONSTRAINT consents_revoked_after_granted_check
        CHECK (revoked_at IS NULL OR (granted_at IS NOT NULL AND revoked_at >= granted_at))
);
CREATE INDEX ON consents (child_id);

-- ---------------------------------------------------------------------------
-- Q2 — Dokument und Signatur
-- ---------------------------------------------------------------------------

-- code wie an consent_purposes und aus demselben Grund: die Strecken, die
-- Dokumente eines bestimmten Typs anlegen oder abfragen (Schulvertrag,
-- SEPA-Mandat, Attest), brauchen einen Anker, der eine Umbenennung des labels
-- überlebt — und der Lösch-Job dazu, sobald Aufbewahrungsfristen je Dokumenttyp
-- gelten (idea/06-dsgvo-organisatorisch.md, Fristen noch offen).
CREATE TABLE document_types (
    document_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label            text NOT NULL UNIQUE CHECK (label <> ''),
    code             text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{0,31}$')  -- z. B. "school_contract", "sepa_mandate"
);

-- Dokument: Typ, Bezug, Ablageort, Erzeugungszeitpunkt. Bewusst NICHT mit Q1
-- verschmolzen — eine Zustimmung kann ohne Dokument existieren (Häkchen), und
-- ein Dokument trägt oft mehrere Zustimmungen (ein Schulvertrag, zwei
-- Unterschriften).
--
-- DIE DATEI SELBST BLEIBT IN SHAREPOINT, hier steht nur die Referenz
-- (domains/grenzkarte.md, Q2). Zwei Folgen, die nicht übersehen werden dürfen:
-- der pg_dump-Backupumfang bleibt unverändert, und der Lösch-Job muss die Datei
-- dort mitentfernen — eine verwaiste Datei in SharePoint ist genauso ein
-- DSGVO-Verstoß wie eine verwaiste Zeile, und sie fällt niemandem auf.
--
-- DIE REFERENZ IST DIE GRAPH-KENNUNG, NICHT DER PFAD: Bibliothek (drive) plus
-- Element (driveItem), beide nur gemeinsam gültig. Ein Pfad bräche bei jedem
-- Verschieben und Umbenennen — und genau das ist der real belegte Fehlermodus
-- dieser Schule: „bricht ein in Teams verschobener Datei-Link den Prozess, ohne
-- dass die verschiebende Person das merkt" (fachdomaenen.md Abschnitt 3). Die
-- Element-Kennung überlebt beides innerhalb ihrer Bibliothek; damit darf die
-- Akte eines Kindes beim Zug- oder Zweigwechsel in einen anderen
-- Kohorten-Ordner gezogen werden, ohne dass hier eine Zeile angefasst wird.
-- Der Anzeigepfad wird bei Bedarf über Graph aufgelöst und NICHT gespeichert —
-- er wäre ein zweiter, veraltender Ort (rules.md Abschnitt 1).
-- Beide Spalten, statt die Bibliothek als Konfigurationswert anzunehmen: es gibt
-- mindestens zwei (von Weltenbaum erzeugt / Schülerakte, domains/grenzkarte.md,
-- Q2), und welche gilt, ist Teil der Adresse und keine Regel im Code.
--
-- Bezug ist entweder ein Kind oder eine Bewerbung — genau eines von beidem,
-- getragen vom Fremdschlüssel statt von einem Typ-Feld daneben, wie bei payments
-- und contracts. Der Vertragsvorgang braucht keinen eigenen Bezug: er hängt
-- selbst schon an einer Bewerbung oder einem Kind.
--
-- EINE ZEILE SAGT ZWEI DINGE, EINZELN ODER ZUSAMMEN: angefordert
-- (requested_on) und vorgelegt (Referenz samt created_on, nur gemeinsam) —
-- dieselbe Bauform wie measles_proofs in domains/gesundheit-schema.sql. Grund
-- ist die Sekretariats-Checkliste des Anmeldetags (prozesse.md Abschnitt 5.2):
-- „Beobachtungsbogen des Kindergartens einholen; falls nicht mitgebracht,
-- bekommen die Eltern einen Bogen zum Ausfüllenlassen" ist ein Vorgang mit
-- offenem Ende, und ohne die Anforderungszeile wäre „fehlt noch" von „nie
-- verlangt" nicht zu unterscheiden — dieselbe Unterscheidung zwischen
-- entschieden und vergessen wie bei der abgelehnten Zustimmung (consents) und
-- der übertragenen Anwesenheitsliste (cleaning_slots.attendance_recorded_at).
--
-- Zwei Folgen: der Lösch-Job darf für eine Zeile ohne Referenz keine Datei
-- in SharePoint suchen (domains/grenzkarte.md, Q2) — es gibt keine —, und eine
-- Signatur auf einer noch nicht vorgelegten Unterlage verhindert die Datenbank
-- nicht (der CHECK liefe über zwei Tabellen). Das bleibt Sache der
-- Eingabemaske, dieselbe dokumentierte Lücke wie bei contract_responses.person_id.
--
-- Entscheidend ist die LÖSCHFRIST, nicht der Anlass: was länger leben muss als
-- die Bewerbung, zeigt aufs Kind. Am Kind hängen deshalb Geburtsurkunde,
-- Zeugnis, Grundschulempfehlung und Beobachtungsbogen, das
-- Gesundheitsdatenblatt samt Attesten (domains/gesundheit.md) und das
-- SEPA-Mandat (domains/grenzkarte.md, Q2; domains/stammdaten-schema.sql,
-- children.mandate_reference) — Letzteres besonders, weil der Datenwert für den
-- Einzug am Kind steht und ohne sein Dokument als Nachweis dastünde.
-- Die drei Verfahrensunterlagen hängen ausdrücklich MIT am Kind und nicht an der
-- Bewerbung, obwohl sie nur zu Beginn gelesen werden: wie lange sie bleiben,
-- entscheidet die Schule mit der Aufbewahrungsfrist (TODO.md) und nicht der
-- Entwurf — an der Bewerbung hätten sie still deren kürzere Frist geerbt. An ihr
-- hängt deshalb nur der Schulvertrag, der ohne seinen Vorgang nichts bedeutet.
CREATE TABLE documents (
    document_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_type_id integer NOT NULL REFERENCES document_types(document_type_id) ON DELETE RESTRICT,
    child_id         uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    application_id   uuid,   -- Fremdschlüssel per ALTER TABLE unten (applications wird danach definiert)
    -- Graph-Kennung der Bibliothek und des Elements (Kopfkommentar). CHECK <> ''
    -- wie an den identitätstragenden Spalten in Stammdaten: eine leere Kennung
    -- sähe aus wie eine Referenz und zeigte nirgendwohin.
    storage_drive_id text CHECK (storage_drive_id <> ''),
    storage_item_id  text CHECK (storage_item_id <> ''),
    created_on       date,               -- Vorlage-/Erzeugungsdatum, gilt nur mit der Referenz
    requested_on     date,               -- angefordert am; leer heißt: lag ohne Aufforderung vor
    -- Fassung der Word-Vorlage, aus der dieses Dokument erzeugt wurde (der
    -- SharePoint-Versionsstempel, z. B. "3.0"). Leer bei allem, was nicht
    -- Weltenbaum erzeugt hat — Geburtsurkunde, Zeugnis, Attest.
    --
    -- Sie hat genau EINEN Abnehmer, und ohne ihn gäbe es die Spalte nicht
    -- (domains/anmeldung.md, „Wenn mitten im Vorgang ein Fehler auffällt"): Vor
    -- Abschluss darf ein Dokument neu erzeugt werden, ohne dass bereits
    -- geleistete Unterschriften verfallen — ein fehlender Buchstabe im Namen
    -- kostet die Eltern sonst einen zweiten kompletten Signaturlauf. Das ist
    -- nur zulässig, solange sich der VERTRAGSTEXT nicht geändert hat, und
    -- genau das sagt diese Spalte: dieselbe Fassung heißt, dass sich
    -- ausschließlich Platzhalter unterscheiden können. Deshalb erzeugt die
    -- Korrektur auch aus der HIER stehenden Fassung neu und nicht aus der
    -- aktuellen — eine inzwischen hochgeladene Vorlage mit geänderter
    -- Kündigungsfrist schöbe sich sonst unter eine schon geleistete
    -- Unterschrift.
    --
    -- Keine Vorlagenhistorie in der Datenbank: die Fassungen selbst hält
    -- SharePoint, hier steht nur, welche es war. CHECK <> '' wie an den
    -- übrigen bedeutungstragenden Textspalten — ein Leerstring sähe aus wie
    -- eine Fassung und verglichen sich gegen nichts.
    template_version text CHECK (template_version <> ''),
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    CONSTRAINT documents_exactly_one_subject_check
        CHECK ((child_id IS NOT NULL)::int + (application_id IS NOT NULL)::int = 1),
    -- Eine halbe Adresse ist keine: ohne Bibliothek findet der Abruf das Element
    -- nicht, ohne Element sagt die Bibliothek nichts.
    CONSTRAINT documents_storage_complete_check
        CHECK ((storage_drive_id IS NULL) = (storage_item_id IS NULL)),
    CONSTRAINT documents_any_fact_check
        CHECK (storage_item_id IS NOT NULL OR requested_on IS NOT NULL),
    CONSTRAINT documents_presentation_complete_check
        CHECK ((storage_item_id IS NULL) = (created_on IS NULL))
);
CREATE INDEX ON documents (child_id);

-- Der Aktenordner eines Kindes — die ZWEITE Ebene neben den Dokumentzeilen
-- oben, und der Grund, warum nicht jede Datei eine Zeile braucht.
--
-- Eine documents-Zeile bekommt nur, was ein Prozess liest: die signierten
-- Unterlagen (Vertrag, Gesundheitsblatt, Fotoeinverständnis, SEPA-Mandat,
-- Atteste) und die am Anmeldetag angeforderten (Geburtsurkunde, Zeugnis,
-- Grundschulempfehlung, Beobachtungsbogen) — dort muss „fehlt noch" von „nie
-- verlangt" unterscheidbar sein. Alles Übrige der digitalen Schülerakte —
-- Schriftverkehr, Bescheinigungen, „was im Lauf der Zeit dazukam" (prozesse.md
-- Abschnitt 17) — liegt im Ordner OHNE Zeile. Nicht jedes Kind hat dieselben
-- Dateien, und ein Index, den niemand liest und der unvollständig sein darf,
-- ist schlechter als keiner: niemand sähe ihm an, ob er vollständig ist.
--
-- Diese eine Zeile macht den Lösch-Job trotzdem vollständig: er löscht den
-- ORDNER und erwischt damit auch die Dateien, die Weltenbaum nie gesehen hat
-- (idea/06-dsgvo-organisatorisch.md). Ohne sie bliebe genau der freie Teil der
-- Akte stehen. Zweiter Abnehmer ist die Datenauskunft (TODO.md), dritter die
-- Ansicht „Akte öffnen".
--
-- child_id ist zugleich Primärschlüssel: ein Kind hat einen Aktenordner oder
-- keinen — dieselbe Bauform wie measles_proofs und meal_profiles. Nullable ist
-- damit die ganze Zeile: ein Bewerber ohne Unterlagen und ein reines
-- Ferienprogramm-Kind haben keinen.
--
-- ON DELETE RESTRICT und damit KEINE Kaskade: der Ordner ist der letzte Ort,
-- an dem Personendaten liegen, die keine Zeile mehr nennt — er darf nicht als
-- Nebenwirkung eines anderen Löschbefehls aus der Datenbank verschwinden,
-- während seine Dateien in SharePoint stehen bleiben. Der Lösch-Job muss ihn
-- ausdrücklich anfassen, wie bei den Gesundheitstabellen.
--
-- Eigene Tabelle statt einer Spalte an children: der Aktenordner ist kein
-- Stammdatum, sondern Teil von Q2 — und Stammdaten sind ab dem Vollimport
-- eingefroren (domains/grenzkarte.md). Neue Tabellen, die sie nur
-- referenzieren, bleiben jederzeit erlaubt.
CREATE TABLE child_file_folders (
    child_id         uuid PRIMARY KEY REFERENCES children(child_id) ON DELETE RESTRICT,
    -- Graph-Kennung wie an documents und dort begründet: Bibliothek plus
    -- Element, nie ein Pfad. Der Ordner darf damit umbenannt und in einen
    -- anderen Kohorten-Ordner verschoben werden, ohne dass hier etwas
    -- nachzuziehen ist — der Zug- oder Zweigwechsel wird ein reiner
    -- SharePoint-Vorgang.
    storage_drive_id text NOT NULL CHECK (storage_drive_id <> ''),
    storage_item_id  text NOT NULL CHECK (storage_item_id <> ''),
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    -- Zwei Kinder können nicht denselben Ordner haben — der reale Weg dorthin
    -- ist ein Verknüpfen per Copy-Paste beim Nachtragen des Altbestands.
    UNIQUE (storage_drive_id, storage_item_id)
);

-- Signatur: Person × Dokument × Zeitpunkt × Signaturbild × Niveau.
-- Niveau als Spalte und nicht als Werteliste: es gibt heute durchgängig genau
-- eine Stufe (einfache elektronische Signatur), und eine Liste mit einer Zeile
-- wäre ein Mechanismus ohne Bedarf (rules.md Abschnitt 1). Kommt eine zweite
-- Stufe, ist das eine Werteliste und keine Umdeutung dieser Spalte.
CREATE TABLE signatures (
    signature_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     uuid NOT NULL REFERENCES documents(document_id) ON DELETE RESTRICT,
    person_id       uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    signed_at       timestamptz NOT NULL DEFAULT now(),
    image_path      text CHECK (image_path <> ''),
    -- CHECK auf den einen bekannten Wert und nicht nur auf „nicht leer": ohne ihn
    -- wären „ees" oder „EES " lautlos eine zweite Signaturstufe, und genau die
    -- Unterscheidung soll die Spalte tragen. Kommt eine echte zweite Stufe, ist
    -- das ohnehin eine Werteliste und damit eine Migration — dann fällt dieser
    -- CHECK mit. Gleiches Muster wie die Formatprüfung an genders.code.
    signature_level text NOT NULL DEFAULT 'EES' CHECK (signature_level = 'EES'),
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    -- Dieselbe Person unterschreibt dasselbe Dokument einmal.
    UNIQUE (document_id, person_id)
);
CREATE INDEX ON signatures (person_id);

-- Eine Zustimmung zeigt optional auf die Signatur, die sie belegt. Nachgezogen,
-- weil consents vor signatures steht: das Häkchen ohne Dokument ist der
-- Regelfall, die belegte Zustimmung die Ausnahme.
ALTER TABLE consents ADD COLUMN signature_id uuid REFERENCES signatures(signature_id) ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------
-- Gesprächstermine
-- ---------------------------------------------------------------------------

-- Ein Anmeldetag je Schulzweig: das Raster, aus dem die Slots entstehen.
-- Wochentag, Zeitfenster, Mittagspause und Kinder je Stunde sind DATEN und
-- keine Konstanten — die zuständigen Personen setzen sie selbst, weil sie sich
-- immer wieder ändern und die Sondertermine heute ohnehin niemand vollständig
-- kennt (prozesse.md Abschnitt 5.1). Der heutige Stand ist damit ein
-- Ausgangswert und keine Regel im Code.
CREATE TABLE interview_days (
    interview_day_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(school_branch_id) ON DELETE RESTRICT,
    school_year      text NOT NULL CHECK (school_year ~ '^[0-9]{4}/[0-9]{2}$'),  -- Format begruendet an enrollment_cutoffs
    day_on           date NOT NULL,
    starts_at        time NOT NULL,
    ends_at          time NOT NULL,
    break_starts_at  time,
    break_ends_at    time,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, day_on),
    -- Ziel des zusammengesetzten Fremdschlüssels von interview_slots — hält
    -- deren school_branch_id konsistent zum Tag, an dem sie hängen. Gleiche
    -- Bauform wie grade_levels.UNIQUE (grade_level_id, school_branch_id) in
    -- Stammdaten.
    UNIQUE (interview_day_id, school_branch_id),
    CONSTRAINT interview_days_period_check CHECK (ends_at > starts_at),
    -- Pause gilt nur ganz oder gar nicht, und sie liegt innerhalb des Tages.
    CONSTRAINT interview_days_break_complete_check
        CHECK ((break_starts_at IS NULL) = (break_ends_at IS NULL)),
    CONSTRAINT interview_days_break_within_day_check
        CHECK (break_starts_at IS NULL
               OR (break_ends_at > break_starts_at
                   AND break_starts_at >= starts_at AND break_ends_at <= ends_at))
);

-- Konkreter buchbarer Slot. Eigene Zeilen statt einer Berechnung aus dem Raster:
-- eine Buchung braucht ein stabiles Ziel, das auch dann noch dasselbe meint,
-- wenn jemand die Pause des Tages verschiebt.
--
-- Kapazität am Slot, weil real 4–5 Kinder je Stunde verarbeitet werden und die
-- Zahl je Tag schwankt. Sie ist hier eine harte Obergrenze für die
-- Selbstbuchung durch die Eltern — anders als beim Putzdienst, wo die Kapazität
-- berechnet wird und das Sekretariat sie überschreiten darf.
--
-- Hart heißt nicht schemaseitig: eine Obergrenze über die Summe der Buchungen
-- eines Slots ist eine Bedingung über mehrere Zeilen und damit kein CHECK. Sie
-- gehört in die Backend-Stelle, die den Termin vergibt, und zwar in derselben
-- Transaktion mit einer Sperre auf dieser Slot-Zeile — sonst prüfen zwei
-- gleichzeitige Elternbuchungen beide gegen denselben Stand und der letzte
-- Platz wird zweimal vergeben. Gleiche Bringschuld wie bei
-- program_days.capacity (domains/ferien-schema.sql).
-- school_branch_id ist eine kontrollierte Doppelung zum Anmeldetag, keine zweite
-- Pflegestelle: sie trägt allein den zusammengesetzten Fremdschlüssel von
-- applications unten, der verhindert, dass eine Grundschul-Bewerbung in einen
-- Realschul-Slot gebucht wird. Über den Ableitungsweg (Slot → Tag → Zweig) lässt
-- sich das nicht ausdrücken, und genau dafür erlaubt rules.md Abschnitt 1 die
-- Ausnahme — gebunden an ihr Original durch den zusammengesetzten
-- Fremdschlüssel, damit beide gar nicht erst auseinanderlaufen können.
-- Dasselbe Muster wie classes.school_branch_id in Stammdaten.
CREATE TABLE interview_slots (
    interview_slot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_day_id  integer NOT NULL,
    school_branch_id  integer NOT NULL,
    starts_at         time NOT NULL,
    capacity          smallint NOT NULL CHECK (capacity > 0),
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    UNIQUE (interview_day_id, starts_at),
    -- Ziel des zusammengesetzten Fremdschlüssels von applications.
    UNIQUE (interview_slot_id, school_branch_id),
    -- Kein zusätzlicher einspaltiger Fremdschlüssel auf interview_days daneben:
    -- dieser verlangt ohnehin eine Zeile mit passendem (id, school_branch_id),
    -- beide Spalten sind NOT NULL, und beim Löschen eines Tages blockiert er
    -- genauso. Gleiche Abwägung wie an classes.grade_level_id in Stammdaten.
    FOREIGN KEY (interview_day_id, school_branch_id)
        REFERENCES interview_days(interview_day_id, school_branch_id)
);

-- ---------------------------------------------------------------------------
-- Bewerbung
-- ---------------------------------------------------------------------------

-- Die Bewerbung ZEIGT auf Kind und Familie, statt Personendaten zu kopieren
-- (Kopfkommentar, Entscheidung 1). Sie trägt nur, was die Bewerbung selbst
-- betrifft.
--
-- Mehrere Bewerbungen je Kind sind der Normalfall, nicht der Ausnahmefall: der
-- Wechsel von der eigenen Grundschule in die eigene Realschule ist eine zweite
-- Bewerbung desselben Kindes, und eine abgelehnte Bewerbung kann im Folgejahr
-- wiederholt werden. Deshalb UNIQUE nur je Kind und Zielschuljahr.
--
-- Ein NEUER Anlauf im SELBEN Zieljahr (Absage im Frühjahr, Quereinstiegsversuch
-- vor dem 01.08.) ist dagegen bewusst keine zweite Zeile: das Sekretariat
-- öffnet die bestehende per Status wieder — der benannte Ausweg. Eine zweite
-- Anmeldegebühr entsteht dabei nicht (payments.application_id ist UNIQUE), und
-- nach dem Lösch-Lauf zum 01.08. (domains/anmeldung.md, „Löschung") ist die
-- Zeile für einen späten Quereinstieg ohnehin frei.
--
-- registration_date steht daneben an children und ist keine Doppelung: das
-- Anmeldedatum überlebt die Bewerbung, die eine kürzere Löschfrist hat
-- (domains/stammdaten.md, „Felder").
CREATE TABLE applications (
    application_id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    child_id                   uuid NOT NULL REFERENCES children(child_id) ON DELETE RESTRICT,
    application_status_id      integer NOT NULL REFERENCES application_statuses(application_status_id) ON DELETE RESTRICT,
    -- Ziel der Bewerbung. Die Klassenstufe wird bei Wartelistenfällen jährlich
    -- fortgeschrieben (Klasse 5 → Klasse 6), das Zielschuljahr ebenso — deshalb
    -- zwei Spalten und keine Ableitung aus dem Anmeldedatum.
    target_school_year         text NOT NULL CHECK (target_school_year ~ '^[0-9]{4}/[0-9]{2}$'),  -- Format begruendet an enrollment_cutoffs
    target_grade_level_id      integer NOT NULL,
    -- Zweig der Zielklassenstufe, kontrollierte Doppelung wie bei
    -- interview_slots und aus demselben Grund: nur mit einer echten Spalte lässt
    -- sich schemaseitig erzwingen, dass der gebuchte Gesprächsslot zum Zweig der
    -- Bewerbung gehört (beide Fremdschlüssel unten). Ohne sie ließe sich eine
    -- Grundschul-Bewerbung in einen Realschul-Anmeldetag buchen — auffallen
    -- würde es erst an der Gesprächsliste, wenn der Termin schon vergeben ist.
    -- Sie ist außerdem für sich brauchbar („alle Realschul-Bewerbungen dieses
    -- Jahrgangs") und spart dort den Join über grade_levels.
    school_branch_id           integer NOT NULL,
    -- Quereinstieg ist ein eigener Ablauf (ganzjährig, Platzprüfung vor dem
    -- Gespräch) und kein Nebeneffekt der Zielklassenstufe: ableitbar wäre er nur
    -- über ein Kennzeichen „Eingangsklassenstufe" an grade_levels, das es dort
    -- nicht gibt und für das eine eingefrorene Stammdaten-Tabelle nicht
    -- aufgemacht wird.
    is_lateral_entry           boolean NOT NULL DEFAULT false,
    -- Hospitationszeitraum des Quereinstiegs (Quereinsteiger-Checkliste,
    -- domains/grenzkarte.md, „Bewerbung"). Bewusst KEIN CHECK gegen
    -- is_lateral_entry: eine Hospitation außerhalb des Quereinstiegs zu
    -- verbieten wäre eine Sperre ohne benannten Bedarf — dieselbe Abwägung wie
    -- bei zwei regulären Putzterminen am selben Tag (cleaning_slots).
    trial_attendance_starts_on date,
    trial_attendance_ends_on   date,
    submitted_on               date NOT NULL DEFAULT current_date,
    -- Wer das Formular ausgefüllt hat und die Bestätigung, dass der andere
    -- Elternteil informiert ist — beides steht so auf dem realen Formular.
    filled_by_person_id        uuid REFERENCES persons(person_id) ON DELETE RESTRICT,
    other_parent_informed      boolean NOT NULL DEFAULT false,
    attended_info_evening      boolean NOT NULL DEFAULT false,
    -- Geschwister als Selbstauskunft, weil es bei externen Bewerbern noch keine
    -- Familie gibt, aus der es folgen könnte. Bei der Aufnahme löst es sich
    -- gegen families auf. Bewusst ohne Namensliste (Kopfkommentar).
    siblings_at_school         boolean NOT NULL DEFAULT false,
    sibling_count              smallint CHECK (sibling_count >= 0),
    interested_in_care         boolean NOT NULL DEFAULT false,
    -- Grundschulseite: Kindergarten samt Rücksprache-Erlaubnis und Empfehlung.
    -- Die Erlaubnis ist wie children.previous_school_consent_at ein einmaliges,
    -- sofort verbrauchtes Einverständnis (also NICHT Q1), steht aber an der
    -- Bewerbung und nicht am Kind: die abgebende Schule wird über den
    -- Anmeldetag hinaus gebraucht, der Kindergarten nicht.
    kindergarten_id            integer REFERENCES kindergartens(kindergarten_id) ON DELETE RESTRICT,
    kindergarten_consent_at    timestamptz,
    kindergarten_recommendation_id integer REFERENCES kindergarten_recommendations(kindergarten_recommendation_id) ON DELETE RESTRICT,
    enrollment_category_id     integer REFERENCES enrollment_categories(enrollment_category_id) ON DELETE RESTRICT,
    -- Realschulseite: die amtliche Grundschulempfehlung der abgebenden Schule.
    -- ZWEI Felder mit derselben Werteliste, solange nicht bestätigt ist, dass es
    -- dasselbe ist (domains/grenzkarte.md, „Bewertung"): dies ist das Dokument
    -- der abgebenden Schule, own_recommendation_id unten die eigene Einschätzung
    -- aus Gespräch und Testblättern. Sind es zwei Namen für dieselbe Angabe,
    -- bleibt eine Spalte leer — der billigere Irrtum, denn ein Feld für zwei
    -- Sachverhalte verlöre gerade den interessanten Fall, dass beide
    -- auseinandergehen.
    primary_school_recommendation_id integer REFERENCES school_recommendations(school_recommendation_id) ON DELETE RESTRICT,
    -- Austausch der Schülerüberweisung mit der staatlichen Schule
    -- (children.previous_school_id). DREI Schritte, weil der reale Ablauf drei
    -- hat: wir informieren die abgebende Schule, daraufhin kommt die
    -- Überweisung, und ggf. geht sie zurück. Auf den Checklisten stehen sie
    -- ebenso als drei eigene Punkte („Bisherige örtl. Schule informieren",
    -- „Schülerüberweisung erhalten?", „Rücksendung an Herkunftsschule").
    --
    -- Der erste Schritt braucht eine eigene Spalte, weil er sonst nicht vom
    -- Warten zu unterscheiden wäre: ohne ihn hieße ein leeres
    -- student_transfer_received_on zugleich „wir haben die Schule noch nicht
    -- informiert" (zu tun: informieren) und „die Schule hat noch nicht
    -- geantwortet" (zu tun: nachfassen) — zwei verschiedene Handlungen für
    -- dasselbe Bild. Ein Anker daneben, an dem sich das ablesen ließe, gibt es
    -- hier nicht: der Austausch läuft Wochen nach dem Anmeldetag und damit lange
    -- nach documents_checked_at (domains/grenzkarte.md, „Drei Zustände").
    --
    -- Ein Vorgangsschritt der Bewerbung und bewusst KEINE Q5-Nachzieh-Aufgabe —
    -- er zieht keine Weltenbaum-Änderung in ein Fremdsystem nach, und an zwei
    -- Orten geführt wäre derselbe Erledigt-Haken zweimal pflegbar
    -- (domains/grenzkarte.md, Q5).
    --
    -- Weiterhin kein Reihenfolge-CHECK, und mit dem dritten Schritt erst recht
    -- nicht: die abgebende Schule kann die Überweisung auch unaufgefordert
    -- schicken (die Eltern melden das Kind dort selbst ab), und die Rücksendung
    -- ist ausdrücklich nur „ggf.". Erzwungen wäre das eine Sperre gegen einen
    -- realen Ablauf.
    student_transfer_requested_on date,   -- „Bisherige örtl. Schule informieren"
    student_transfer_received_on  date,
    student_transfer_returned_on  date,
    -- Vollständigkeitsprüfung der Unterlagen am Anmeldetag — der letzte Punkt
    -- der Sekretariats-Checkliste (prozesse.md Abschnitt 5.2) und die
    -- verwaltende der beiden Spuren des Tages. Nicht zu verwechseln mit
    -- contracts.completeness_checked_at: das ist dieselbe Handlung Wochen später
    -- am fertigen Vertrag, hier geht es um die Unterlagen, die die Eltern zum
    -- Gespräch mitbringen (Geburtsurkunde, Zeugnis, Beobachtungsbogen). Welche
    -- davon fehlen, sagt documents.requested_on; DASS jemand durchgesehen hat,
    -- sagt nur diese Spalte — sonst wäre eine vergessene Prüfung von einer
    -- vollständigen Mappe nicht zu unterscheiden.
    documents_checked_at       timestamptz,
    -- Warteliste: die jährliche Rückfrage, ob das Interesse weiterbesteht
    -- (prozesse.md Abschnitt 6). Zwei Spalten, weil die fehlende Antwort selbst
    -- eine Information ist: ohne den Zeitpunkt der Frage wäre „gefragt, keine
    -- Antwort" von „dieses Jahr nie gefragt" nicht zu unterscheiden — über
    -- mehrere Jahre hinweg genau der Fall, in dem eine Familie still liegen
    -- bleibt. Beide werden bei der jährlichen Fortschreibung geleert
    -- (domains/anmeldung.md), sie gelten also immer für das aktuelle
    -- target_school_year. Keine Historie, wie überall.
    waitlist_interest_asked_at     timestamptz,
    waitlist_interest_confirmed_at timestamptz,
    -- Gesprächstermin. Nullable: die Voranmeldung läuft Monate vor der
    -- Terminvergabe. Fremdschlüssel steht unten als zusammengesetzter, der
    -- zugleich den Zweig prüft — ein einspaltiger daneben wäre eine
    -- Einschränkung ohne eigene Wirkung.
    interview_slot_id          integer,
    -- --- Bewertung: engstes Zugriffsprofil im System nach den Art.-9-Daten -----
    -- Vier Spalten, kein eigenes Zugriffssystem: sie bekommen ein eigenes
    -- Spalten-GRANT auf dieser Tabelle (wie die Konfessionsspalten an children),
    -- und sie sind standardmäßig NICHT breit sichtbar. Die Lehrer-Checkliste
    -- bleibt Papier und wird nach dem Verfahren vernichtet; hier landet nur das
    -- konsolidierte Ergebnis samt weniger Notizen (prozesse.md Abschnitt 5.2).
    fit_assessment_id          integer REFERENCES fit_assessments(fit_assessment_id) ON DELETE RESTRICT,
    own_recommendation_id      integer REFERENCES school_recommendations(school_recommendation_id) ON DELETE RESTRICT,
    -- Rangnummer nur für die Grenzfälle der Entscheidungsrunde; klare Zusagen
    -- und klare Absagen brauchen keine. Nach der Entscheidung liest sie niemand
    -- mehr — sie bleibt als Beleg, wie entschieden wurde.
    rank_number                smallint CHECK (rank_number > 0),
    assessment_notes           text CHECK (assessment_notes <> ''),
    -- --- Ende Bewertung -------------------------------------------------------
    -- EIN Freitextfeld für den Bearbeitungsstand, bewusst nicht zwei: die
    -- Trennung zwischen „Bemerkung" und „Stand" wird im Alltag nicht eingehalten
    -- (domains/grenzkarte.md). Kein Notiz-Verlauf, solange niemand danach sucht.
    -- Es nimmt ZWEI Herkünfte auf: den Bearbeitungsstand der Wartelisten-Tabelle
    -- und den „Freitext für zusätzliche Anmerkungen" der Sekretariats-Checkliste
    -- am Anmeldetag (prozesse.md Abschnitt 5.2). Beide gehören der verwaltenden
    -- Spur und damit hierher — NICHT nach assessment_notes: das liegt im
    -- Bewertungsblock unten mit eigenem, engem Spalten-GRANT und ist
    -- standardmäßig nicht breit sichtbar. Eine Anmeldetags-Anmerkung dort wäre
    -- für genau die Verwaltung unlesbar, die sie geschrieben hat.
    processing_note            text CHECK (processing_note <> ''),
    -- Zusammensetzungswunsch für die Klassenbildung — real drei Kinder je
    -- Jahrgang. Eine Kind-zu-Kind-Verknüpfung mit Richtung und Gegenseitigkeit
    -- dafür zu bauen wäre ein Mechanismus ohne Bedarf (domains/grenzkarte.md,
    -- „Klassenbildung").
    class_placement_wish       text CHECK (class_placement_wish <> ''),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    created_by                 text NOT NULL,
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    updated_by                 text NOT NULL,
    UNIQUE (child_id, target_school_year),
    -- Eine Geschwisterzahl von 0 verträgt sich nicht mit „Geschwister an der
    -- Schule": beides zusammen ist ein Ausfüllfehler, kein Sonderfall.
    -- Name bewusst nicht "applications_sibling_count_check": den vergibt
    -- Postgres bereits automatisch für den Spalten-CHECK an sibling_count, und
    -- zwei Constraints desselben Namens gibt es nicht.
    CONSTRAINT applications_siblings_at_school_count_check
        CHECK (NOT siblings_at_school OR coalesce(sibling_count, 1) > 0),
    -- Eine Rücksprache-Erlaubnis ohne Kindergarten hat keinen Adressaten.
    CONSTRAINT applications_kindergarten_consent_requires_kindergarten_check
        CHECK (kindergarten_consent_at IS NULL OR kindergarten_id IS NOT NULL),
    -- Ein Ende ohne Anfang ist kein Zeitraum, eines davor erst recht nicht.
    CONSTRAINT applications_trial_attendance_period_check
        CHECK (trial_attendance_ends_on IS NULL
               OR (trial_attendance_starts_on IS NOT NULL
                   AND trial_attendance_ends_on >= trial_attendance_starts_on)),
    -- Bestätigt werden kann nur, was gefragt wurde — dieselbe Bauform wie
    -- consents_revoked_after_granted_check.
    CONSTRAINT applications_waitlist_confirmation_requires_query_check
        CHECK (waitlist_interest_confirmed_at IS NULL
               OR (waitlist_interest_asked_at IS NOT NULL
                   AND waitlist_interest_confirmed_at >= waitlist_interest_asked_at)),
    -- Bindet school_branch_id an die Zielklassenstufe …
    FOREIGN KEY (target_grade_level_id, school_branch_id)
        REFERENCES grade_levels(grade_level_id, school_branch_id),
    -- … und den gebuchten Slot an denselben Zweig. interview_slot_id ist
    -- nullable, und das ist hier genau richtig: ein zusammengesetzter
    -- Fremdschlüssel greift per Default (MATCH SIMPLE) nicht, sobald eine seiner
    -- Spalten NULL ist — eine Bewerbung ohne Gesprächstermin läuft also
    -- ungehindert durch, eine mit Termin nur im passenden Zweig.
    FOREIGN KEY (interview_slot_id, school_branch_id)
        REFERENCES interview_slots(interview_slot_id, school_branch_id)
);
CREATE INDEX ON applications (child_id);
CREATE INDEX ON applications (application_status_id);
CREATE INDEX ON applications (interview_slot_id);
-- „Alle Bewerbungen dieses Zielschuljahrs samt Stufe" ist die Arbeitsliste der
-- Entscheidungsrunde und der jährlichen Fortschreibung.
CREATE INDEX ON applications (target_school_year, target_grade_level_id);

ALTER TABLE documents ADD FOREIGN KEY (application_id) REFERENCES applications(application_id) ON DELETE RESTRICT;
CREATE INDEX ON documents (application_id);

-- Wahrgenommene Angebote: M:N, weil mehrere gleichzeitig zutreffen.
--
-- MIT Audit-Spalten, anders als eine reine Werteliste und nach demselben Maßstab
-- wie guardian_categories in Stammdaten: der Inhalt steuert eine REGEL, nicht
-- nur einen Anzeigetext — die Wahrnehmung dieser Angebote gibt bei der Zusage
-- einen Bonus (siehe school_programs). Wer hier eine Zeile ergänzt oder
-- entfernt, verschiebt eine Aufnahmeentscheidung; ohne created_by/updated_by
-- wäre das nicht auf Verursacher und Zeitpunkt zurückzuführen.
CREATE TABLE application_programs (
    application_id    uuid NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    school_program_id integer NOT NULL REFERENCES school_programs(school_program_id) ON DELETE RESTRICT,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    PRIMARY KEY (application_id, school_program_id)
);

-- ---------------------------------------------------------------------------
-- Schulvertrag und Hortvertrag
-- ---------------------------------------------------------------------------

-- Der Vertragsvorgang beginnt mit der Zusage und endet mit der Bestätigungsmail.
-- Eigene Zeile und keine Spalten an der Bewerbung: er hat einen eigenen
-- Lebenslauf mit vier Stationen, von denen drei nach dem Absenden der Eltern
-- liegen, und die meisten Bewerbungen erreichen ihn nie.
--
-- Die vier Zeitpunkte sind bewusst Zeitpunkte und kein Statusfeld: sie treten
-- immer in dieser Reihenfolge ein, und „wann war das" ist die Frage, die im
-- Nachhinein gestellt wird (domains/anmeldung.md).
--
-- BEZUG IST ENTWEDER EINE BEWERBUNG ODER EIN KIND, getragen vom Fremdschlüssel
-- statt von einem Typ-Feld daneben, wie bei documents und payments. Er trägt
-- damit zugleich die Vertragsart: BEWERBUNG heißt Schulvertrag, KIND heißt
-- Hortvertrag.
--
-- DER HORTVERTRAG IST IMMER EIN EIGENER VORGANG — für interne Kinder wie für
-- externe, und dadurch derselbe Ablauf für beide. Drei Gründe, jeder allein
-- tragend:
--   * Er entsteht später. Am Anmeldetag steht der Betreuungsbedarf regelmäßig
--     noch nicht fest; erhoben wird dort nur applications.interested_in_care.
--     An den Schulvertrag gehängt fände ein im Mai nachgereichter Hortvertrag
--     dessen vier Zeitpunkte längst gesetzt — weder eigene Frist noch eigene
--     Prüfung durch das Sekretariat noch eigene Freigabe.
--   * Er wird im laufenden Schuljahr geändert und gekündigt, während der
--     Schulvertrag steht: Modul-Anpassungen im September, zum Halbjahr und bei
--     Stundenplanänderungen (prozesse.md Abschnitt 8).
--   * Der Hort nimmt Kinder auf, die weder Grund- noch Realschüler sind
--     (prozesse.md Abschnitt 8) — für sie gibt es gar keine Bewerbung.
-- Auch die eigene Bestätigung des Horts (Anschreiben + Welcome-Brief,
-- prozesse.md Abschnitt 5.2) braucht deshalb ihren eigenen confirmation_sent_at
-- und nicht den der Aufnahmebestätigung.
--
-- WER PRÜFT UND WER GIBT FREI, hängt an der Vertragsart und ist deshalb keine
-- Eigenschaft dieser Tabelle — die beiden Spalten sind nach der Handlung
-- benannt, nicht nach der Stelle:
--   * Schulvertrag: die Verwaltung prüft auf Vollständigkeit, die Schulleitung
--     des jeweiligen Zweigs gibt frei und zeichnet gegen (prozesse.md
--     Abschnitt 7.1).
--   * Hortvertrag: der Vorgang läuft vollständig über den Hort — der Hort prüft,
--     die HORTLEITUNG gibt frei und zeichnet gegen (prozesse.md Abschnitt 8:
--     „Unterschriften von Mutter, Vater und Hortleitung"). Die Schulleitung ist
--     hier gar nicht zuständig: sie ist je Zweig benannt (glossar.md), und ein
--     externes Hortkind hat keinen.
-- Beide Male sind es zwei verschiedene Personen — die Freigabe ist die
-- Zweitprüfung, und genau deshalb braucht das Aufsetzen keine eigene Rolle
-- (domains/anmeldung.md).
--
-- MEHRERE VERTRÄGE ÜBER DIE ZEIT SIND ZULÄSSIG, je Bewerbung wie je Kind —
-- deshalb steht auf keiner der beiden Bezugsspalten ein tabellenweites UNIQUE.
-- Zwei reale Anlässe: ein Kind schließt über die Jahre mehrere Hortverträge,
-- und ein bereits gegengezeichneter Schulvertrag muss neu aufgesetzt werden,
-- wenn nach der Freigabe auffällt, dass wesentliche Angaben fehlen (real
-- vorgekommen). Der alte Vorgang bleibt dabei stehen: er ist der Beleg, wie
-- damals entschieden wurde, und seine vier Zeitpunkte werden nicht rückdatiert.
--
-- ES GILT DER VERTRAG MIT DEM JÜNGSTEN confirmation_sent_at — abgeleitet und
-- deshalb ohne „ist aktuell"-Kennzeichen, das ein zweiter Ort für dieselbe
-- Tatsache wäre (rules.md Abschnitt 1). Ein noch laufender Neuvorgang ändert
-- damit nichts, solange er nicht abgeschlossen ist: bis dahin bleibt der zuletzt
-- bestätigte der gültige, und genau das ist die richtige Aussage.
--
-- Was bleibt, ist die Sperre gegen den Versehensfall: HÖCHSTENS EIN OFFENER
-- Vorgang je Bewerbung und je Kind (partielle Unique-Indizes unten). Zwei
-- gleichzeitig laufende Vertragsstrecken zum selben Vorgang wären keine
-- Historie, sondern ein Fehler — die Eltern bekämen zwei Links und niemand
-- wüsste, welcher zählt. Referenzmuster wie
-- care_module_bookings_one_open_per_child_and_module.
CREATE TABLE contracts (
    contract_id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id        uuid REFERENCES applications(application_id) ON DELETE RESTRICT,
    child_id              uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    -- Frist für die Eltern, real 14 Tage ab Versand. Als Datum und nicht als
    -- Dauer, weil die Verwaltung sie im Einzelfall verlängert.
    deadline_on            date NOT NULL,
    -- Die beiden Spalten sind nach der HANDLUNG benannt und nicht nach der
    -- Stelle, weil die Stelle von der Vertragsart abhängt (Begründung im
    -- Tabellenkopf, „Wer prüft und wer gibt frei"): beim Schulvertrag prüft die
    -- Verwaltung und die Schulleitung gibt frei, beim Hortvertrag prüft der Hort
    -- und die Hortleitung gibt frei. Ein Name wie „headmaster_released_at" wäre
    -- für die Hälfte der Zeilen schlicht falsch — die Schulleitung ist je Zweig
    -- zuständig (glossar.md), und ein externes Hortkind hat keinen.
    completeness_checked_at timestamptz,
    released_at            timestamptz,
    confirmation_sent_at   timestamptz,
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             text NOT NULL,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    updated_by             text NOT NULL,
    -- Die Reihenfolge ist Teil des Verfahrens: erst prüft die führende Stelle
    -- auf Vollständigkeit, dann gibt die zuständige Leitung frei, dann geht die
    -- Bestätigung raus. Eine Bestätigungsmail vor der Freigabe wäre genau der
    -- Fehler, der an dieser Schule niemandem auffiele.
    -- Geprüft wird beides: dass der frühere Schritt überhaupt stattgefunden hat
    -- UND dass er früher liegt. Ohne den Zeitvergleich ließe sich
    -- completeness_checked_at nachträglich hinter die Freigabe schieben, und die
    -- Zeile dokumentierte eine Prüfung, die nach der Freigabe stattfand — genau
    -- die Aussage, die diese vier Zeitpunkte tragen sollen. Gleiche Bauform wie
    -- consents_revoked_after_granted_check.
    CONSTRAINT contracts_release_after_check_check
        CHECK (released_at IS NULL
               OR (completeness_checked_at IS NOT NULL
                   AND released_at >= completeness_checked_at)),
    CONSTRAINT contracts_confirmation_after_release_check
        CHECK (confirmation_sent_at IS NULL
               OR (released_at IS NOT NULL
                   AND confirmation_sent_at >= released_at)),
    CONSTRAINT contracts_exactly_one_subject_check
        CHECK ((application_id IS NOT NULL)::int + (child_id IS NOT NULL)::int = 1)
);
CREATE INDEX ON contracts (child_id);
CREATE INDEX ON contracts (application_id);
-- Höchstens ein OFFENER Vorgang je Bezug (Kopfkommentar): abgeschlossene
-- Verträge sammeln sich als Historie, laufende darf es nur einen geben. Je
-- Bezugsspalte ein eigener partieller Index; Zeilen der jeweils anderen Art
-- tragen dort NULL und kollidieren nicht.
CREATE UNIQUE INDEX contracts_one_open_per_application
    ON contracts (application_id) WHERE confirmation_sent_at IS NULL;
CREATE UNIQUE INDEX contracts_one_open_per_child
    ON contracts (child_id) WHERE confirmation_sent_at IS NULL;

-- Antwort je Erziehungsberechtigtem. Eigene Zeilen und kein Feld am Vertrag,
-- weil Mutter und Vater je einen eigenen persönlichen Link bekommen und
-- UNTERSCHIEDLICH antworten können — sagt einer ja und der andere nein, wird das
-- Sekretariat benachrichtigt und klärt telefonisch (prozesse.md Abschnitt 7.1).
-- Genau dieser Konflikt ist an einem einzelnen Vertragsfeld nicht darstellbar.
--
-- Die Stammdatenbestätigung steht daneben: jeder bestätigt seine EIGENEN Daten,
-- die des Kindes bestätigen beide — deshalb zwei Zeitpunkte je Zeile und nicht
-- einer.
--
-- person_id ist schemaseitig eine beliebige persons-Zeile und NICHT auf die
-- Sorgeberechtigten des betroffenen Kindes eingeschränkt. Das ist eine Lücke mit
-- Ansage, keine Auslassung: die Bedingung führt über contract → application →
-- child → family → family_guardians und ist damit weder als CHECK noch als
-- Fremdschlüssel ausdrückbar, sondern nur als Trigger — und Trigger für
-- tabellenübergreifende Bedingungen lehnt dieses Projekt an jeder vergleichbaren
-- Stelle ab (Freikauf-Frist in domains/putzdienst-schema.sql, slot_date im
-- Zyklus, phone_numbers.is_primary). Die Bindung entsteht stattdessen dort, wo
-- der persönliche Vertragslink erzeugt wird: er geht ausschließlich an die
-- Erziehungsberechtigten der Familie des Kindes (idea/04-identitaet-zugriff.md).
-- Genannt wird es hier, weil das die rechtlich gewichtigste Tabelle der Domäne
-- ist und die Lücke sonst wie ein Versehen aussähe.
CREATE TABLE contract_responses (
    contract_id             uuid NOT NULL REFERENCES contracts(contract_id) ON DELETE CASCADE,
    person_id               uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    accepted                boolean,
    responded_at            timestamptz,
    own_data_confirmed_at   timestamptz,
    child_data_confirmed_at timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    created_by              text NOT NULL,
    updated_at              timestamptz NOT NULL DEFAULT now(),
    updated_by              text NOT NULL,
    PRIMARY KEY (contract_id, person_id),
    -- Eine Antwort ohne Zeitpunkt ist keine, und ein Zeitpunkt ohne Antwort
    -- ebenso wenig.
    CONSTRAINT contract_responses_answer_complete_check
        CHECK ((accepted IS NULL) = (responded_at IS NULL))
);
CREATE INDEX ON contract_responses (person_id);

-- ---------------------------------------------------------------------------
-- Betreuungsmodule (Hortvertrag)
-- ---------------------------------------------------------------------------

-- Katalog der buchbaren Module: Frühbetreuung, vier Nachmittagsvarianten, Hort
-- nach Mittagschule (prozesse.md Abschnitt 8). Werteliste, weil die Schule
-- Module streicht und ergänzt, ohne dass eine Migration nötig sein darf.
--
-- school_branch_id nullable: „Hort nach Mittagschule" gilt nur für die
-- Realschule, alle übrigen für beide Zweige. NULL heißt also „ohne
-- Einschränkung" und nicht „unbekannt".
--
-- Dass ein Kind nur ein Modul seines eigenen Zweigs bucht, erzwingt das Schema
-- NICHT: der Zweig des Kindes führt über children.class_id → classes und wäre
-- nur als Trigger prüfbar. Dieselbe dokumentierte Lücke wie bei
-- contract_responses.person_id unten, program_bookings.child_id
-- (domains/ferien-schema.sql) und class_parent_representatives.guardian_id
-- (domains/klassenorganisation-schema.sql) — die Bindung liegt in der
-- Buchungsstrecke, die nur die für dieses Kind gültigen Module anbietet.
CREATE TABLE care_modules (
    care_module_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> ''),
    school_branch_id  integer REFERENCES school_branches(school_branch_id) ON DELETE RESTRICT,
    -- Zeiten als Text und nicht als time-Spalten: der reale Katalog beginnt
    -- überwiegend bei „Schulende" und nicht zu einer Uhrzeit, und diese Angabe
    -- steht im Formular, wird aber von keiner Abfrage ausgewertet.
    time_description  text NOT NULL CHECK (time_description <> ''),
    -- Die Hausaufgabenbetreuung ist Bestandteil des MODULS, kein eigenes
    -- Interesse- oder Buchungsfeld an Bewerbung oder Buchung: real enthalten
    -- die Nachmittagsbetreuungen 2–4 sie, Modul 1 (nur bis 13:00) nicht
    -- (prozesse.md Abschnitt 8). Wer sie bekommt, entscheidet damit allein die
    -- Modulwahl — ein Feld daneben wäre ein zweiter Ort für dieselbe Tatsache.
    includes_homework boolean NOT NULL DEFAULT false,
    -- Dieselbe Bauform für das Mittagessen: der Betreuungsvertrag berechnet es
    -- „für alle Schüler, die länger als 13 Uhr betreut werden" — ob ein Modul
    -- das auslöst, ist eine Eigenschaft des Moduls und keine eigene Buchung.
    -- Aus time_description (Freitext) ist die 13-Uhr-Grenze nicht maschinell
    -- ablesbar, deshalb ein eigenes Kennzeichen, gepflegt von der Verwaltung.
    -- Das Katalogmodul „Mittagessen" (RS-Mensa-Abo, domains/mensa.md) trägt es
    -- trivialerweise auch — „isst mit" ist damit EIN Prädikat über EINE
    -- Tabelle: aktive Buchung eines includes_lunch-Moduls am jeweiligen
    -- Wochentag. Abnehmer sind die Küchen-Tagesliste und der Abrechnungshinweis
    -- an die Buchhaltung („Zuzüglich Mittagessen"); die Abrechnung selbst
    -- bleibt bei Optigem (domains/grenzkarte.md, Q3).
    includes_lunch    boolean NOT NULL DEFAULT false,
    sort_order        smallint NOT NULL UNIQUE,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL
);

-- Gebuchtes Modul für ein Kind, mit eigenem Gültigkeitszeitraum.
--
-- Hängt am KIND und nicht am Vertragsvorgang: der Hort nimmt auch Kinder auf,
-- die weder Grund- noch Realschüler sind (prozesse.md Abschnitt 8) — für sie
-- gibt es keine Bewerbung, aber eine Buchung. contract_id sagt nur, aus welchem
-- Vorgang die Buchung entstanden ist: bei Betreuungsmodulen der Hortvertrag des
-- Kindes (Begründung an contracts, gilt für interne wie externe Kinder), beim
-- Mensa-Abo gar keiner — deshalb nullable.
--
-- valid_from/valid_until tragen Laufzeit, Kündigung und Angebotsende in einem:
-- der reale Betreuungsvertrag läuft ein Schuljahr (01.08.–31.07.) und
-- verlängert sich stillschweigend, kündbar mit Monatsfrist (prozesse.md
-- Abschnitt 8) — valid_until bleibt also NULL, solange nichts endet, und wird
-- bei Kündigung oder Angebotsende gesetzt (das Hortangebot endet mit
-- Klasse 5). Als Datum und nicht als Regel im Code, weil die Schule Fristen
-- und Grenzen verschiebt.
--
-- Dieselben zwei Tabellen tragen auch das MENSA-Wochentags-Abo der Realschule:
-- dessen Anmeldeformular ist dieselbe Buchungsform (Wochentage ankreuzen,
-- Monatsbeitrag, Schuljahreslaufzeit, Kündigung zum Halbjahr) — im Katalog
-- steht dafür die Zeile „Mittagessen" mit includes_lunch, eine eigene
-- Buchungstabelle gäbe es nur dem Namen nach (domains/mensa.md).
CREATE TABLE care_module_bookings (
    care_module_booking_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    child_id               uuid NOT NULL REFERENCES children(child_id) ON DELETE RESTRICT,
    care_module_id         integer NOT NULL REFERENCES care_modules(care_module_id) ON DELETE RESTRICT,
    contract_id            uuid REFERENCES contracts(contract_id) ON DELETE RESTRICT,
    valid_from             date NOT NULL,
    valid_until            date,
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             text NOT NULL,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    updated_by             text NOT NULL,
    UNIQUE (child_id, care_module_id, valid_from),
    CONSTRAINT care_module_bookings_period_check
        CHECK (valid_until IS NULL OR valid_until >= valid_from)
);
CREATE INDEX ON care_module_bookings (child_id);
-- Höchstens EINE offene Buchung je Kind und Modul. Das UNIQUE oben schließt
-- valid_from ein und lässt deshalb zwei Zeilen desselben Moduls mit
-- verschiedenem Beginn und beide ohne Ende zu — genau die Form, in der eine
-- Modul-Anpassung real entsteht: alte Buchung beenden, neue anlegen
-- (prozesse.md Abschnitt 8, im September kostenfrei, zum Halbjahr gegen
-- Gebühr). Wird das valid_until der alten dabei vergessen, sind beide „aktiv",
-- und „isst am Wochentag X mit" (domains/mensa.md) zählt dasselbe Kind zweimal:
-- die Küche kocht eine Portion zu viel und der Abrechnungshinweis geht doppelt
-- an die Buchhaltung. Beides fällt niemandem auf, weil jede Zeile für sich
-- gültig aussieht.
--
-- Der Index erzwingt damit die richtige Reihenfolge (erst schließen, dann neu
-- anlegen) und trägt zugleich die Zusage aus domains/anmeldung.md, „welcher
-- Vertrag gilt, sagt die Laufzeit der Buchung".
--
-- Partieller Index statt EXCLUDE über daterange: volle Überlappungsfreiheit
-- bräuchte btree_gist für die beiden Gleichheitsspalten (uuid, integer) und
-- damit eine Extension — für den realen Fehlerfall (die alte Zeile nicht
-- geschlossen) genügt die offene Buchung. Referenzmuster wie
-- phone_numbers_one_primary_per_person in Stammdaten und
-- program_bookings_one_active_per_child_and_day in der Ferien-Domäne.
CREATE UNIQUE INDEX care_module_bookings_one_open_per_child_and_module
    ON care_module_bookings (child_id, care_module_id) WHERE valid_until IS NULL;

-- Die Buchungseinheit ist Modul × Wochentag, nicht das Modul allein: je Modul
-- werden die einzelnen Tage gewählt (prozesse.md Abschnitt 8). Deshalb eine
-- eigene Zeile je Tag und keine sieben Boolean-Spalten — ein Wochentag mehr oder
-- weniger ist damit ein Datensatz.
--
-- MIT Audit-Spalten, obwohl die Buchung darüber sie ohnehin trägt: der Wochentag
-- IST hier die Buchungseinheit und keine Verfeinerung. Ein entfernter Mittwoch
-- ändert Leistung und Rechnung, und die Audit-Spalten der Buchungszeile bleiben
-- dabei unberührt — die Änderung wäre spurlos.
CREATE TABLE care_module_booking_days (
    care_module_booking_id uuid NOT NULL REFERENCES care_module_bookings(care_module_booking_id) ON DELETE CASCADE,
    -- ISO-8601: 1 = Montag … 5 = Freitag. Betreuung am Wochenende gibt es nicht,
    -- und ein Tippfehler „7" wäre sonst eine stille Buchung ins Leere.
    weekday                smallint NOT NULL CHECK (weekday BETWEEN 1 AND 5),
    created_at             timestamptz NOT NULL DEFAULT now(),
    created_by             text NOT NULL,
    updated_at             timestamptz NOT NULL DEFAULT now(),
    updated_by             text NOT NULL,
    PRIMARY KEY (care_module_booking_id, weekday)
);

-- ---------------------------------------------------------------------------
-- Q3 — Zahlungsvorgang erweitern
-- ---------------------------------------------------------------------------

-- Die Anmeldegebühr ist der dritte Stripe-Anlass (domains/grenzkarte.md, Q3).
-- Sie kommt als weitere nullable Vorgangs-Spalte samt erweitertem
-- Entweder-oder-CHECK an die bestehende Tabelle — nicht als zweite
-- Zahlungstabelle: der Fremdschlüssel trägt die Unterscheidung, und genau die
-- referenzielle Integrität ist der Grund, Q3 überhaupt einmal zu bauen.
-- ON DELETE RESTRICT wie bei den beiden Putzdienst-Anlässen: die Zahlungszeile
-- geht mit ihrer Bewerbung, aber nicht nebenbei. Sie bleibt auch nicht als
-- vorgangsloser Beleg stehen — Optigem ist für die Buchhaltung führend und zieht
-- die Zahlung selbst aus Stripe (fachdomaenen.md Abschnitt 4), Weltenbaum
-- braucht sie nach dem Verfahren also nicht mehr. Damit bleibt der
-- Entweder-oder-CHECK unangetastet: eine Zahlung ohne Anlass gibt es nie, und
-- eine leere Vorgangsspalte ist immer ein Fehler und nie ein Zustand.
--
-- Folge für den Lösch-Job: er räumt von außen nach innen — Zahlung, dann
-- Zustimmung, Signatur und Dokument samt SharePoint-Datei (in dieser
-- Reihenfolge: consents.signature_id blockiert die Signatur,
-- signatures.document_id das Dokument), dann der Vertragsvorgang, dann die
-- Bewerbung (domains/anmeldung.md, „Löschung"). Die Fremdschlüssel erzwingen
-- die Reihenfolge, statt sie ihm zu überlassen — wer eine Stufe überspringt,
-- bricht mit einer Fremdschlüssel-Verletzung ab und hinterlässt einen halb
-- geräumten Bestand.
ALTER TABLE payments
    ADD COLUMN application_id uuid UNIQUE REFERENCES applications(application_id) ON DELETE RESTRICT;

ALTER TABLE payments DROP CONSTRAINT payments_exactly_one_subject_check;
ALTER TABLE payments ADD CONSTRAINT payments_exactly_one_subject_check
    CHECK ((cleaning_buyout_id IS NOT NULL)::int
         + (cleaning_slot_buyout_id IS NOT NULL)::int
         + (application_id IS NOT NULL)::int = 1);

-- ---------------------------------------------------------------------------
-- Q5 — Nachzieh-Aufgabe
-- ---------------------------------------------------------------------------

-- ASV-BW und Optigem haben keine Update-Schnittstelle: jede Änderung, die in
-- Weltenbaum passiert, muss ein Mensch dort nachziehen — heute über Zuruf und
-- Gedächtnis, ohne dass ein Ausbleiben auffiele (prozesse.md Abschnitt 2). Q5
-- macht daraus eine benannte Aufgabe mit Erledigt-Zustand
-- (domains/grenzkarte.md, Q5). Hier gebaut, weil der erste reale Abnehmer die
-- Neuanlage in ASV-BW nach Vertragsabschluss ist (prozesse.md Abschnitt 7.1,
-- Schritt 8); die alltägliche Datenänderung der Stammdaten erzeugt später
-- dieselben Aufgaben.
--
-- Gespeichert wird nur, was sich nicht ableiten lässt: WAS zu tun ist und OB
-- es erledigt wurde. Die Änderung selbst steht in den Audit-Spalten der
-- geänderten Zeile, und welches Feld welches Fremdsystem betrifft, ist eine
-- statische Abbildung im Code, der die Aufgabe erzeugt — beides bekommt
-- deshalb keine Tabelle (domains/grenzkarte.md, Q5). Die Erzeugung und
-- Abarbeitung der Aufgaben ist Backend-Arbeit in wb-backend und ausdrücklich
-- NICHT Teil dieses Entwurfs — hier steht nur die Struktur.

-- Fremdsystem, in das nachzuziehen ist ("ASV-BW", "Optigem", "Microsoft 365").
-- code als stabiler Anker wie an consent_purposes und aus demselben Grund: der
-- Code, der Aufgaben erzeugt, wählt das Zielsystem programmatisch — auf dem
-- frei umbenennbaren label aufgesetzt bräche das still.
CREATE TABLE sync_targets (
    sync_target_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label          text NOT NULL UNIQUE CHECK (label <> ''),
    code           text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]{0,31}$')  -- z. B. "asv_bw", "optigem", "m365"
);

-- Eine offene oder erledigte Nachzieh-Aufgabe. completed_at NULL heißt offen;
-- WER erledigt hat, trägt die ohnehin vorhandene updated_by-Spalte — dieselbe
-- Bauform wie cleaning_assignments.penalty_waived_at.
--
-- person_id sagt, WEN die Aufgabe betrifft, und ist bewusst ON DELETE CASCADE:
-- eine Aufgabe ist operativ, nichts Vereinbartes — löscht der Lösch-Job Jahre
-- später die Person, ist nichts mehr nachzuziehen, und eine stehengebliebene
-- Aufgabenzeile wäre selbst ein Personenbezug ohne Zweck. Damit die Kaskade
-- sauber bleibt, beschreibt description die AUFGABE („Adresse in Optigem
-- aktualisieren"), nie die Person — Name und Kontext folgen aus person_id.
-- Nullable für personenlose Aufgaben (z. B. ein Klassenverteiler in M365).
-- description ist Freitext mit benanntem Abnehmer: die Aufgabenliste, die das
-- Sekretariat abarbeitet — vom erzeugenden Code formuliert, nicht von Hand.
CREATE TABLE sync_tasks (
    sync_task_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sync_target_id integer NOT NULL REFERENCES sync_targets(sync_target_id) ON DELETE RESTRICT,
    person_id      uuid REFERENCES persons(person_id) ON DELETE CASCADE,
    description    text NOT NULL CHECK (description <> ''),
    completed_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     text NOT NULL,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     text NOT NULL
);
CREATE INDEX ON sync_tasks (person_id);
-- Die Arbeitsliste des Sekretariats: alle offenen Aufgaben je Zielsystem.
CREATE INDEX sync_tasks_open_by_target ON sync_tasks (sync_target_id) WHERE completed_at IS NULL;

-- ---------------------------------------------------------------------------
-- Audit-Trigger
-- ---------------------------------------------------------------------------
-- Nur auf Tabellen mit Audit-Spalten: die reinen Wertelisten ohne eigenen
-- Lebenslauf (kindergartens, school_programs, …) tragen keine, wie in Stammdaten.
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON enrollment_cutoffs
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON application_windows
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON application_statuses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON consents
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON documents
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_file_folders
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON signatures
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON interview_days
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON interview_slots
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON applications
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON application_programs
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contracts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contract_responses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON care_modules
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON care_module_bookings
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON care_module_booking_days
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON sync_tasks
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
