-- Ferienanmelde-Schema: Ferienprogramm und Kochwerkstatt (Domäne 3,
-- fachdomaenen.md Abschnitt 6). Konzeptioneller Entwurf zu domains/ferien.md
-- und domains/grenzkarte.md — konkreter als Prosa, aber noch kein
-- Alembic-Migrationscode.
--
-- SETZT domains/stammdaten-schema.sql, domains/putzdienst-schema.sql UND
-- domains/anmeldung-schema.sql VORAUS und wird nach ihnen geladen: es
-- referenziert children/persons, erweitert die payments-Tabelle ein weiteres Mal
-- und nutzt die Zustimmung (Q1) aus dem Anmelde-Schema für die
-- Werbe-Einwilligung.
--
-- Die Domäne ist klein, hat aber die unangenehmste Eigenschaft aller Domänen:
-- sie legt Personen an, die mit der Schule sonst nichts zu tun haben. Schulfremde
-- Kinder bekommen eine children-Zeile samt Familie, anmeldendem Elternteil und
-- Notfallkontakt (domains/stammdaten.md, „Familie") — children.exit_date bleibt
-- bei ihnen dauerhaft leer und taugt deshalb NICHT als Löschfrist-Anker
-- (idea/06-dsgvo-organisatorisch.md). Der Anker ist das Programm: ist es vorbei
-- und hat das Kind keinen anderen Bezug zur Schule, fällt es mit der Frist der
-- Buchung. Mit der Kochwerkstatt kommen zusätzlich ERWACHSENE Teilnehmer dazu —
-- reine persons-Zeilen ohne Rollenzeile, gebucht über eine eigene
-- Teilnehmer-Spalte (program_bookings), mit demselben Programm-Anker.
--
-- Was hier bewusst NICHT steht:
--   * Kein „Clemens-Kind"-Kennzeichen. Die Frage des Formulars ist aus dem
--     Stammdaten-Prädikat „eingeschrieben" ableitbar und wäre als Spalte ein
--     zweiter, veraltender Ort (domains/grenzkarte.md, Domäne 3).
--   * Keine Notfallnummer als Feld. Sie ist eine Kontaktverknüpfung in
--     Stammdaten — und der Kontakt braucht einen Namen, sobald er eine dritte
--     Person ist (domains/grenzkarte.md).
--   * Keine Fotoeinverständnis-Sonderbehandlung. Bei schulfremden Kindern wird
--     sie nachgereicht, aber es ist dieselbe Zustimmung (Q1) und dasselbe
--     Dokument (Q2) wie überall sonst.
--   * Keine eigene Zahlung je Buchung. Bezahlt wird die Anmeldung als Ganzes
--     (Begründung an program_registrations).
--   * Keine Stornogebühr und keine Rückerstattung. Storniert wird heute per Mail
--     an den Hort; was daraus finanziell folgt, entscheidet die Buchhaltung
--     außerhalb von Weltenbaum (domains/grenzkarte.md, Q3).

-- Ein Programm ist ein konkretes Angebot in einem konkreten Zeitraum — die
-- Herbstferien 2026, nicht „das Ferienprogramm" allgemein. Kochwerkstatt und
-- Ferienprogramm teilen sich diese Tabelle, weil sie sich in nichts
-- unterscheiden, was das Schema sieht.
--
-- booking_closes_at ist Pflicht und nicht nullable: die Anmeldung wird
-- ausdrücklich VOR Programmbeginn geschlossen, weil vorab eingekauft und
-- geplant werden muss — auch dann, wenn rechnerisch noch Platz wäre
-- (prozesse.md Abschnitt 10). Ein Programm ohne Anmeldeschluss gibt es nicht.
CREATE TABLE programs (
    program_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> ''),   -- z. B. "Ferienprogramm Herbst 2026"
    starts_on         date NOT NULL,
    ends_on           date NOT NULL,
    booking_closes_at timestamptz NOT NULL,
    -- Preis je gebuchtem Tag, für die Berechnung des Zahlbetrags beim Absenden.
    -- Wie beim Putzdienst steht der Betrag am Programm und die gezahlte Summe an
    -- der Zahlung: was gezahlt wurde, muss auch dann noch stimmen, wenn der
    -- Preis später korrigiert wird.
    fee_per_day       numeric(8,2) NOT NULL CHECK (fee_per_day >= 0),
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    CONSTRAINT programs_period_check CHECK (ends_on >= starts_on),
    -- „Der Anmeldeschluss liegt spätestens am Programmbeginn" — mit FEST
    -- VERDRAHTETER Zone und nicht als booking_closes_at::date <= starts_on.
    -- Der Cast timestamptz → date wertet die Zeitzone der SITZUNG aus; Postgres
    -- nimmt ihn im CHECK zwar an, aber dieselbe Zeile fällt damit je nach
    -- Verbindung anders aus (gemessen gegen Postgres 18: 2026-10-12 23:59+02
    -- mit starts_on 2026-10-13 läuft unter Europe/Berlin durch und scheitert
    -- unter Pacific/Kiritimati). Das trifft nicht die Eingabe, sondern die
    -- WIEDERHERSTELLUNG: ein Restore unter anderer Zeitzone weist sonst Zeilen
    -- ab, die jahrelang gültig waren — und der quartalsweise Restore-Test
    -- (rules.md Abschnitt 8) ist genau die Stelle, an der das zu spät auffiele.
    -- Mit AT TIME ZONE 'Europe/Berlin' ist der Ausdruck unveränderlich und die
    -- Aussage dieselbe: vor Mitternacht nach dem Starttag, in Ortszeit der
    -- Schule.
    CONSTRAINT programs_booking_closes_before_start_check
        CHECK (booking_closes_at < ((starts_on + 1)::timestamp AT TIME ZONE 'Europe/Berlin'))
);

-- Angebotstag mit eigener Kapazität. Die Grenze gilt je TAG und nicht je
-- Programm — genau so ist sie real formuliert (prozesse.md Abschnitt 10), und
-- eine Programmsumme ließe zu, dass alle Kinder am selben Tag erscheinen.
--
-- Anders als beim Putzdienst ist die Kapazität hier eine harte Obergrenze und
-- kein berechneter Richtwert: es geht um Aufsicht und eingekauftes Material,
-- nicht um eine gleichmäßige Verteilung.
--
-- HART heißt nicht schemaseitig: eine Obergrenze über die Summe der Buchungen
-- eines Tages ist eine Bedingung über mehrere Zeilen und damit kein CHECK. Sie
-- gehört in dieselbe Backend-Stelle, die die Buchung anlegt, und zwar in
-- derselben Transaktion mit einer Sperre auf dieser Tageszeile — sonst prüfen
-- zwei gleichzeitige Elternbuchungen beide gegen denselben Stand und der letzte
-- Platz wird zweimal vergeben. Dieselbe Abwägung und dieselbe Bringschuld wie
-- bei der Freikauf-Frist (domains/putzdienst-schema.sql) und bei
-- interview_slots.capacity (domains/anmeldung-schema.sql).
--
-- Der Tag trägt sein Zeitfenster selbst: starts_at ist der Beginn, ends_at das
-- SPÄTESTE Betreuungsende, aus dem die Oberfläche die wählbaren Enden anbietet
-- (real 14:00 und 16:00). Ohne diese beiden Spalten bezöge sich
-- program_bookings.care_until auf nichts — die Angabe stünde ausschließlich in
-- der Eingabemaske, und ein Betreuungsende um 03:00 liefe widerspruchsfrei
-- durch. Dass care_until in dieses Fenster fällt, prüft wieder das Backend:
-- die Bedingung greift über zwei Tabellen.
CREATE TABLE program_days (
    program_day_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id     integer NOT NULL REFERENCES programs(program_id) ON DELETE RESTRICT,
    day_on         date NOT NULL,
    starts_at      time NOT NULL,
    ends_at        time NOT NULL,
    capacity       smallint NOT NULL CHECK (capacity > 0),
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     text NOT NULL,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     text NOT NULL,
    UNIQUE (program_id, day_on),
    CONSTRAINT program_days_period_check CHECK (ends_at > starts_at)
);

-- Der Anmeldevorgang: ein Absenden des Formulars, MEHRERE Kinder und mehrere
-- Tage. Eigene Entität, weil die Zahlung genau an ihm hängt — bei drei Kindern
-- füllt niemand drei Formulare aus und bezahlt dreimal (prozesse.md Abschnitt
-- 10). Ohne sie müsste jede einzelne Tagesbuchung ihre eigene Zahlung tragen,
-- und Q3 verlangt genau einen Vorgang je Zahlung.
--
-- registered_by_person_id ist der anmeldende Elternteil: an ihn gehen
-- Buchungsbestätigung, Stornierung und die nachzureichende
-- Fotoeinverständnis-Erklärung. Er ist zugleich der Grund, warum auch ein
-- schulfremdes Kind eine Familie bekommt (domains/stammdaten.md).
--
-- Die Werbe-Einwilligung des Formulars steht NICHT hier, sondern als Zustimmung
-- in Q1: sie überlebt den Vorgang, ist widerrufbar und wird später wieder
-- geprüft — genau die Eigenschaften, für die Q1 gebaut wurde.
--
-- KEIN cancelled_at am Vorgang, obwohl „der ganze Vorgang wird storniert" der
-- häufige Fall ist: storniert wird immer die Buchung, und der Vorgang ist
-- storniert, sobald keine aktive Buchung mehr an ihm hängt — ableitbar und
-- damit kein zweiter Ort (rules.md Abschnitt 1). Zwei Spalten wären hier nicht
-- nur Redundanz, sondern eine Falle: die Tageskapazität zählt die Buchungen,
-- ein Storno allein am Vorgang ließe die Plätze also weiter belegt aussehen,
-- und der Tag wäre voll, obwohl niemand kommt.
CREATE TABLE program_registrations (
    program_registration_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id              integer NOT NULL REFERENCES programs(program_id) ON DELETE RESTRICT,
    registered_by_person_id uuid NOT NULL REFERENCES persons(person_id) ON DELETE RESTRICT,
    -- KEIN eigenes submitted_at daneben: die Zeile entsteht beim Absenden, und
    -- created_at trägt damit denselben Zeitpunkt — vom Trigger gesetzt und bei
    -- UPDATE aus OLD übernommen, also unveränderlich. Ein zweites Feld wäre ein
    -- zweiter Ort für dieselbe Tatsache (rules.md Abschnitt 1). Der Unterschied
    -- zu applications.submitted_on ist das Formular: dort IST das Anmeldedatum
    -- ein erhobenes Feld, das bei einer Nachmeldung abweichend gesetzt wird
    -- (prozesse.md Abschnitt 3.2) — das Ferienformular erhebt keines
    -- (Abschnitt 10).
    created_at              timestamptz NOT NULL DEFAULT now(),
    created_by              text NOT NULL,
    updated_at              timestamptz NOT NULL DEFAULT now(),
    updated_by              text NOT NULL
);
CREATE INDEX ON program_registrations (registered_by_person_id);
CREATE INDEX ON program_registrations (program_id);

-- Die eigentliche Buchung: ein Teilnehmer an einem Angebotstag, mit gewähltem
-- Betreuungsende.
--
-- Teilnehmer ist entweder ein KIND oder eine ERWACHSENE Person — die
-- Kochwerkstatt steht ausdrücklich auch Erwachsenen offen (fachdomaenen.md
-- Abschnitt 1), und eine erwachsene Teilnehmerin ist eine persons-Zeile ganz
-- ohne Rollenzeile (domains/stammdaten.md, „Ausblick"). Entweder-oder über
-- zwei Fremdschlüssel samt CHECK, dieselbe Bauform wie der Dokument-Bezug in
-- documents. Ein Kind bleibt dabei bewusst eine children-Zeile und wird nicht
-- auf persons aufgeweicht: an der Kind-Rolle hängen Notfallkontakt und
-- Fotoeinverständnis-Pflicht, und der Löschanker über das Programm (unten)
-- greift für beide Teilnehmerarten gleich.
--
-- care_until als Uhrzeit und nicht als Werteliste: real stehen 14:00 und 16:00
-- zur Wahl, und das sind Zeitpunkte, keine benannten Kategorien — eine Liste
-- „14 Uhr"/„16 Uhr" wäre eine Werteliste über zwei Uhrzeiten, die man auch
-- direkt hinschreiben kann. Welche Enden ein Tag konkret anbietet, leitet die
-- Oberfläche aus dessen Zeitfenster ab (program_days.starts_at/ends_at); dass
-- der gewählte Wert hineinfällt, prüft das Backend, weil die Bedingung über
-- zwei Tabellen greift.
--
-- Storno setzt einen Zeitpunkt, statt die Zeile zu löschen: die stornierte
-- Buchung bleibt als Beleg stehen, und die Tageskapazität zählt sie nicht mehr
-- mit.
--
-- Die Eindeutigkeit „ein Kind, ein Tag, eine Buchung" ist deshalb ein
-- PARTIELLER Unique-Index über die aktiven Zeilen und kein tabellenweites
-- UNIQUE (siehe unten). Ein tabellenweites hätte die Wiederanmeldung nach einem
-- Storno blockiert, und der naheliegende Ausweg — die stornierte Zeile
-- wiederbeleben — wäre falsch: sie hängt am ALTEN Anmeldevorgang mit dessen
-- Zahlung. Der neue Vorgang stünde ohne Buchung da, der stornierte hätte wieder
-- aktive. Mit dem partiellen Index entsteht schlicht eine zweite Zeile im neuen
-- Vorgang, und die alte bleibt storniert.
--
-- child_id ist an nichts gebunden: schemaseitig lässt sich ein Kind einer
-- fremden Familie in einen Vorgang buchen. Wie bei contract_responses.person_id
-- (domains/anmeldung-schema.sql) führte die Bedingung über mehrere Tabellen und
-- wäre nur als Trigger ausdrückbar; die Bindung entsteht stattdessen in der
-- Buchungsstrecke, die nur Kinder der eigenen Familie anbietet
-- (idea/04-identitaet-zugriff.md).
--
-- Kein CHECK „cancelled_at nach der Anmeldung": der Bezugspunkt steht in der
-- anderen Tabelle. Wann tatsächlich storniert wurde, hält ohnehin die
-- Audit-Spalte updated_at fest.
CREATE TABLE program_bookings (
    program_booking_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    program_registration_id uuid NOT NULL REFERENCES program_registrations(program_registration_id) ON DELETE RESTRICT,
    child_id                uuid REFERENCES children(child_id) ON DELETE RESTRICT,
    -- Erwachsene Kochwerkstatt-Teilnehmerin (Kopfkommentar der Tabelle) — eine
    -- persons-Zeile ohne Rollenzeile, regelmäßig die anmeldende Person selbst.
    adult_person_id         uuid REFERENCES persons(person_id) ON DELETE RESTRICT,
    program_day_id          integer NOT NULL REFERENCES program_days(program_day_id) ON DELETE RESTRICT,
    care_until              time NOT NULL,
    -- „Wichtige Notizen"/„Bemerkung" des heutigen Formulars. Notiz zu einem
    -- VORGANG und deshalb hier erlaubt, anders als das verbotene allgemeine
    -- Notizfeld an einer Personenzeile (domains/stammdaten.md, „Felder").
    note                    text CHECK (note <> ''),
    cancelled_at            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    created_by              text NOT NULL,
    updated_at              timestamptz NOT NULL DEFAULT now(),
    updated_by              text NOT NULL,
    -- Genau ein Teilnehmer je Buchung: keiner wäre eine Buchung ins Leere, zwei
    -- wären zwei Plätze in einer Zeile — die Tageskapazität zählt Zeilen.
    CONSTRAINT program_bookings_exactly_one_participant_check
        CHECK ((child_id IS NOT NULL)::int + (adult_person_id IS NOT NULL)::int = 1)
);
CREATE INDEX ON program_bookings (program_registration_id);
CREATE INDEX ON program_bookings (program_day_id);
-- Für den Lösch-Job: hängt an dieser Person noch eine Buchung?
CREATE INDEX ON program_bookings (adult_person_id);
-- Höchstens eine AKTIVE Buchung je Teilnehmer und Angebotstag. Referenzmuster
-- für „höchstens eine markierte Zeile je Gruppe" wie
-- phone_numbers_one_primary_per_person in Stammdaten — hier über die
-- Abwesenheit des Storno-Zeitpunkts. Je Teilnehmerart ein eigener partieller
-- Index; Zeilen der jeweils anderen Art tragen NULL und kollidieren nicht
-- (NULLs sind im UNIQUE verschieden).
CREATE UNIQUE INDEX program_bookings_one_active_per_child_and_day
    ON program_bookings (child_id, program_day_id) WHERE cancelled_at IS NULL;
CREATE UNIQUE INDEX program_bookings_one_active_per_adult_and_day
    ON program_bookings (adult_person_id, program_day_id) WHERE cancelled_at IS NULL;

-- ---------------------------------------------------------------------------
-- Q3 — Zahlungsvorgang ein letztes Mal erweitern
-- ---------------------------------------------------------------------------
-- Die Ferienprogramm-Buchung ist der dritte und letzte Stripe-ANLASS aus
-- domains/grenzkarte.md (Q3); als Vorgangs-Spalte ist sie die vierte, weil der
-- Putzdienst-Anlass zwei Vorgänge trägt. Damit ist die Liste vollständig:
-- Putzdienst-Komplettfreikauf, Putzdienst-Einzelfreikauf, Anmeldegebühr,
-- Ferienbuchung.
ALTER TABLE payments
    ADD COLUMN program_registration_id uuid UNIQUE
        REFERENCES program_registrations(program_registration_id) ON DELETE RESTRICT;

ALTER TABLE payments DROP CONSTRAINT payments_exactly_one_subject_check;
ALTER TABLE payments ADD CONSTRAINT payments_exactly_one_subject_check
    CHECK ((cleaning_buyout_id IS NOT NULL)::int
         + (cleaning_slot_buyout_id IS NOT NULL)::int
         + (application_id IS NOT NULL)::int
         + (program_registration_id IS NOT NULL)::int = 1);

-- ---------------------------------------------------------------------------
-- Audit-Trigger
-- ---------------------------------------------------------------------------
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON programs
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON program_days
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON program_registrations
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON program_bookings
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
