-- Mensa-Schema (Domäne 6, fachdomaenen.md Abschnitt 6): das Küchenprofil je
-- Kind. Konzeptioneller Entwurf zu domains/mensa.md und domains/grenzkarte.md —
-- konkreter als Prosa, aber noch kein Alembic-Migrationscode.
--
-- SETZT domains/stammdaten-schema.sql VORAUS: es referenziert children und
-- nutzt set_row_audit() samt app.actor-Präfixregel.
--
-- DIE BUCHUNG DES MITTAGESSENS HAT HIER BEWUSST KEINE EIGENE TABELLE. Das
-- RS-Anmeldeformular („Anmeldung zum Mittagessen", prozesse.md Abschnitt 9)
-- ist dieselbe Buchungsform wie der Betreuungsvertrag des Horts: Wochentage
-- ankreuzen, Monatsbeitrag, Schuljahreslaufzeit, Kündigung zum Halbjahr. Sie
-- läuft deshalb über die bestehenden Tabellen care_module_bookings/
-- care_module_booking_days (domains/anmeldung-schema.sql) mit der Katalogzeile
-- „Mittagessen" — eine eigene Essensbuchungstabelle gäbe es nur dem Namen
-- nach. Für Hortkinder folgt das Mittagessen ohnehin aus dem Modul: berechnet
-- wird es „für alle Schüler, die länger als 13 Uhr betreut werden"
-- (Betreuungsvertrag), ablesbar an care_modules.includes_lunch. „Isst am
-- Wochentag X mit" ist damit EIN Prädikat: aktive Buchung eines
-- includes_lunch-Moduls, dessen Buchungstage X enthalten.
--
-- Was hier steht, gehört allein der KÜCHE: welche Essensvariante ein Kind
-- bekommt. Erhoben über zwei Formulare — die „Infos für die Küche" der
-- RS-Mensa-Anmeldung und die Vegetarier-Frage des Betreuungsvertrags —,
-- gespeichert EINMAL je Kind, nicht je Anmeldung: dasselbe
-- Ein-Datenbestand-Prinzip wie bei den Gesundheitsdaten (domains/gesundheit.md).
--
-- ABGRENZUNG ZU DOMÄNE 9, damit es niemand „zusammenräumt": das Küchenprofil
-- ist die Handlungsanweisung an die Küche (welche Variante kochen), von den
-- Eltern formuliert — KEINE Diagnose und kein medizinischer Bestand. Die
-- Lebensmittelunverträglichkeit mit Diagnose, Attest und Notfallanweisung
-- bleibt ein health_traits-Merkmal mit dem engen Art.-9-Zugriff; die Küche
-- bekommt dorthin keinen Zugriff. Dieselbe Zweiteilung wie action_note gegen
-- den vollen Satz: nicht die Länge unterscheidet die Spalten, sondern der
-- Leserkreis.
--
-- Zugriff: eigene Rolle für Küche/Hausdienstverwaltung mit GRANT auf genau
-- diese Tabellen plus die Tagesliste — wie überall steht das GRANT selbst in
-- wb-backend/db/init-roles.sh, nicht hier.
--
-- Was hier bewusst NICHT steht:
--   * Keine Preis-Spalten. Die Beitragssatzung/Preisliste (Module, Mittagessen)
--     liegt nicht vor, ihre Struktur ist unbekannt — geraten würde sie falsch
--     (domains/grenzkarte.md, „Weiße Flecken"). Die Abrechnung bleibt ohnehin
--     bei Optigem (Q3): in Weltenbaum entsteht für Mensa und Hort keine
--     Zahlung, nur die Lastschrift-Erlaubnis als Zustimmung (Q1).
--   * Keine Essensausgabe-/Anwesenheitserfassung. Die Berechtigung wird heute
--     auf Papier geprüft (prozesse.md Abschnitt 9); die Tagesliste ist eine
--     Abfrage, kein Bestand.
--   * Kein Speiseplan. Kein benannter Prozess braucht ihn.

-- ---------------------------------------------------------------------------
-- Werteliste
-- ---------------------------------------------------------------------------

-- Essensvariante, nach der die Küche kocht und zählt ("Vegetarisch",
-- "Laktosefrei", "Glutenfrei"). Lookup statt dreier Boolean-Spalten (rules.md
-- Abschnitt 3): die Küche gruppiert danach (wie viele vegetarische Portionen
-- heute), und eine weitere Variante („vegan") ist eine Zeile statt einer
-- Migration. Kein code daneben: an keiner Variante hängt Systemverhalten,
-- eine Umbenennung ändert nur den Anzeigetext.
CREATE TABLE meal_diet_types (
    meal_diet_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label             text NOT NULL UNIQUE CHECK (label <> '')
);

-- ---------------------------------------------------------------------------
-- Küchenprofil
-- ---------------------------------------------------------------------------

-- Höchstens ein Profil je Kind — child_id ist zugleich Primärschlüssel, wie
-- beim Masernnachweis. Keine Zeile heißt: der Küche ist nichts mitzuteilen.
--
-- kitchen_note trägt die „sonstigen Unverträglichkeiten" des Formulars als
-- Handlungsangabe an die Küche („keine Nüsse") — Freitext mit benanntem
-- Abnehmer, keine Diagnose (Kopfkommentar).
--
-- ON DELETE RESTRICT wie bei den Gesundheitstabellen und aus demselben Grund:
-- die Essensvariante lässt Rückschlüsse auf Gesundheit (und beim Vegetarischen
-- ggf. Weltanschauung) zu — eine solche Zeile verschwindet nicht als
-- Nebenwirkung eines anderen Löschbefehls, der Lösch-Job räumt sie
-- ausdrücklich zuerst.
CREATE TABLE meal_profiles (
    child_id     uuid PRIMARY KEY REFERENCES children(child_id) ON DELETE RESTRICT,
    kitchen_note text CHECK (kitchen_note <> ''),
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text NOT NULL
);

-- Varianten je Kind, M:N: „vegetarisch UND glutenfrei" ist der reale Fall, den
-- ein Einzelverweis nicht trüge. Hängt am Profil, nicht direkt am Kind — die
-- Profilzeile ist der eine Anker, den die Küchen-Rolle liest, und ohne sie
-- gäbe es zwei getrennt zu grantende Einstiege.
--
-- MIT Audit-Spalten, obwohl das Profil sie trägt: die Variante IST hier die
-- Aussage — eine entfernte Laktose-Zeile ändert, was ein Kind zu essen
-- bekommt, und die Profilzeile bliebe dabei unberührt. Dieselbe Abwägung wie
-- bei care_module_booking_days.
CREATE TABLE meal_profile_diets (
    child_id          uuid NOT NULL REFERENCES meal_profiles(child_id) ON DELETE CASCADE,
    meal_diet_type_id integer NOT NULL REFERENCES meal_diet_types(meal_diet_type_id) ON DELETE RESTRICT,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    PRIMARY KEY (child_id, meal_diet_type_id)
);

-- ---------------------------------------------------------------------------
-- Audit-Trigger
-- ---------------------------------------------------------------------------
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON meal_profiles
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON meal_profile_diets
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
