CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE genders (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE,
    code  text NOT NULL UNIQUE CHECK (code ~ '^[A-Za-z0-9]{1,8}$')
);

CREATE TABLE salutations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE academic_titles (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE guardian_categories (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE denominations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE languages (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE,
    code  text NOT NULL UNIQUE CHECK (code ~ '^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$')
);

CREATE TABLE countries (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE,
    code  text NOT NULL UNIQUE CHECK (code ~ '^[A-Z]{3}$')
);

CREATE TABLE phone_types (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE school_branches (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE grade_levels (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(id) ON DELETE RESTRICT,
    label            text NOT NULL,
    sort_order       smallint NOT NULL,
    is_final_grade   boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, label),
    UNIQUE (school_branch_id, sort_order),
    UNIQUE (id, school_branch_id)
);

CREATE UNIQUE INDEX ON grade_levels (school_branch_id) WHERE is_final_grade;

CREATE TABLE classes (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(id) ON DELETE RESTRICT,
    grade_level_id   integer NOT NULL,
    entry_year       smallint NOT NULL,
    stream           text NOT NULL CHECK (stream <> ''),
    is_active        boolean NOT NULL DEFAULT true,
    class_teacher_id uuid,
    room             text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, entry_year, stream),
    FOREIGN KEY (grade_level_id, school_branch_id) REFERENCES grade_levels(id, school_branch_id),
    CHECK (entry_year BETWEEN 2000 AND 2100)
);

CREATE TABLE previous_schools (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE addresses (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    street       text,
    house_number text,
    district     text,
    postal_code  text,
    city         text,
    country_id   integer NOT NULL REFERENCES countries(id) ON DELETE RESTRICT,
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text NOT NULL
);

CREATE INDEX ON addresses (postal_code, street, house_number);

CREATE TABLE persons (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    salutation_id     integer REFERENCES salutations(id) ON DELETE RESTRICT,
    academic_title_id integer REFERENCES academic_titles(id) ON DELETE RESTRICT,
    first_name        text,
    last_name         text NOT NULL CHECK (last_name <> ''),
    gender_id         integer REFERENCES genders(id) ON DELETE RESTRICT,
    address_id        uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    email             citext,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    CHECK (email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE INDEX ON persons (address_id);

CREATE INDEX ON persons (email);

CREATE INDEX ON persons (lower(last_name) text_pattern_ops);

CREATE TABLE organizations (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text NOT NULL CHECK (name <> ''),
    address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    email      citext,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL,
    CHECK (email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);

CREATE INDEX ON organizations (address_id);

CREATE TABLE phone_numbers (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid REFERENCES persons(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
    phone_type_id   integer NOT NULL REFERENCES phone_types(id) ON DELETE RESTRICT,
    number          text NOT NULL CHECK (number <> ''),
    is_primary      boolean NOT NULL DEFAULT false,
    note            text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL)),
    UNIQUE (person_id, number),
    UNIQUE (organization_id, number)
);

CREATE UNIQUE INDEX ON phone_numbers (person_id)       WHERE is_primary AND person_id IS NOT NULL;

CREATE UNIQUE INDEX ON phone_numbers (organization_id) WHERE is_primary AND organization_id IS NOT NULL;

CREATE TABLE families (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL
);

CREATE TABLE children (
    id                 uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    family_id          uuid REFERENCES families(id) ON DELETE RESTRICT,
    nickname           text,
    date_of_birth      date NOT NULL,
    birthplace         text,
    birth_country_id      integer REFERENCES countries(id) ON DELETE RESTRICT,
    nationality_id        integer REFERENCES countries(id) ON DELETE RESTRICT,
    second_nationality_id integer REFERENCES countries(id) ON DELETE RESTRICT,
    home_language_id   integer REFERENCES languages(id) ON DELETE RESTRICT,
    denomination_id    integer REFERENCES denominations(id) ON DELETE RESTRICT,
    congregation       text,
    provisional_grade_level_id integer REFERENCES grade_levels(id) ON DELETE RESTRICT,
    class_id           integer REFERENCES classes(id) ON DELETE RESTRICT,
    registration_date  date,
    entry_date         date,
    exit_date          date,
    previous_school_id integer REFERENCES previous_schools(id) ON DELETE RESTRICT,
    previous_school_consent_at timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    CHECK (second_nationality_id IS NULL OR nationality_id IS NOT NULL),
    CHECK (second_nationality_id IS NULL OR second_nationality_id <> nationality_id),
    CHECK (exit_date IS NULL OR entry_date IS NULL OR exit_date >= entry_date),
    CHECK (entry_date IS NULL OR registration_date IS NULL OR entry_date >= registration_date),
    CHECK (previous_school_consent_at IS NULL OR previous_school_id IS NOT NULL),
    CHECK (class_id IS NULL OR provisional_grade_level_id IS NULL)
);

CREATE INDEX ON children (family_id);

CREATE INDEX ON children (class_id);

CREATE INDEX ON children (provisional_grade_level_id);

CREATE TABLE guardians (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid UNIQUE REFERENCES persons(id) ON DELETE RESTRICT,
    organization_id uuid UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    occupation      text,
    denomination_id integer REFERENCES denominations(id) ON DELETE RESTRICT,
    congregation    text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL)),
    CHECK (person_id IS NOT NULL OR (occupation IS NULL AND denomination_id IS NULL AND congregation IS NULL))
);

CREATE TABLE employees (
    id               uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    work_email       citext UNIQUE,
    entra_object_id  text UNIQUE CHECK (entra_object_id <> ''),
    employment_start date,
    employment_end   date,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    CHECK (work_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    CHECK (employment_end IS NULL OR employment_start IS NULL OR employment_end >= employment_start)
);
ALTER TABLE classes ADD FOREIGN KEY (class_teacher_id) REFERENCES employees(id) ON DELETE RESTRICT;

CREATE INDEX ON classes (class_teacher_id);

CREATE TABLE family_guardians (
    family_id            uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    guardian_id          uuid NOT NULL REFERENCES guardians(id) ON DELETE CASCADE,
    guardian_category_id integer REFERENCES guardian_categories(id) ON DELETE RESTRICT,
    include_in_correspondence boolean NOT NULL DEFAULT true,
    contact_person       text,
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           text NOT NULL,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    updated_by           text NOT NULL,
    PRIMARY KEY (family_id, guardian_id)
);

CREATE INDEX ON family_guardians (guardian_id);

CREATE TABLE contacts (
    id         uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    note       text,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL
);

CREATE TABLE child_contacts (
    child_id     uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    relationship text,
    priority     smallint,
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text NOT NULL,
    PRIMARY KEY (child_id, contact_id)
);

CREATE INDEX ON child_contacts (contact_id);

CREATE UNIQUE INDEX ON child_contacts (child_id, priority) WHERE priority IS NOT NULL;

CREATE TABLE payers (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id          uuid UNIQUE REFERENCES persons(id) ON DELETE RESTRICT,
    organization_id    uuid UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    billing_address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    iban               text CHECK (iban ~ '^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$'),
    bic                text CHECK (bic ~ '^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$'),
    account_holder     text,
    mandate_reference  text UNIQUE CHECK (mandate_reference <> ''),
    mandate_signed_at  date,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL)),
    CHECK ((mandate_reference IS NULL) = (mandate_signed_at IS NULL)),
    CHECK (mandate_reference IS NULL OR iban IS NOT NULL)
);

CREATE INDEX ON payers (billing_address_id);

CREATE TABLE child_payers (
    child_id   uuid NOT NULL REFERENCES children(id) ON DELETE RESTRICT,
    payer_id   uuid NOT NULL REFERENCES payers(id) ON DELETE CASCADE,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL,
    PRIMARY KEY (child_id, payer_id)
);

CREATE INDEX ON child_payers (payer_id);

CREATE UNIQUE INDEX ON child_payers (child_id) WHERE is_primary;

CREATE FUNCTION set_row_audit() RETURNS trigger AS $$
DECLARE
    actor text := nullif(current_setting('app.actor', true), '');
BEGIN
    IF actor IS NULL THEN
        RAISE EXCEPTION 'app.actor nicht gesetzt — SET LOCAL app.actor vor jedem Schreibzugriff auf eine Audit-Tabelle';
    END IF;
    IF actor !~ '^(entra|guardian|system):.' THEN
        RAISE EXCEPTION 'app.actor braucht ein bekanntes Präfix (entra:/guardian:/system:), war: %', actor;
    END IF;
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := now();
        NEW.created_by := actor;
    ELSE
        NEW.created_at := OLD.created_at;
        NEW.created_by := OLD.created_by;
    END IF;
    NEW.updated_at := now();
    NEW.updated_by := actor;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON grade_levels
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON classes
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON persons
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON organizations
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON phone_numbers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON families
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON children
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON employees
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON family_guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON payers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_payers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

CREATE FUNCTION check_family_guardians_contact_person() RETURNS trigger AS $$
BEGIN
    IF NEW.contact_person IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM guardians WHERE id = NEW.guardian_id AND organization_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'contact_person nur zulässig, wenn guardian_id eine Organisation ist (guardian_id %)', NEW.guardian_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_family_guardians_contact_person BEFORE INSERT OR UPDATE ON family_guardians
    FOR EACH ROW EXECUTE FUNCTION check_family_guardians_contact_person();
