-- Stammdaten-Kernschema (Person, Adresse, Familie, Erziehungsberechtigte, Kind,
-- Kontakte, Zahlungsverantwortliche). Konzeptioneller Entwurf zu
-- domains/stammdaten.md — konkreter als Prosa, aber noch kein Alembic-
-- Migrationscode. Übertragung in SQLAlchemy-2.0-Modelle + Alembic-Migration
-- folgt im App-Stack-Repo (wb-backend), gemäß dessen eigener CLAUDE.md
-- (englische Bezeichner, dort Abschnitt 1/8).
--
-- Gegengelesen gegen vier reale Schulverwaltungs-Schemata (ASV-BW-Strukturdump,
-- SVWS-NRW, GibbonEdu, eigenes Vorprojekt), um Randfälle nicht neu zu erfinden.
-- Wo eine Referenz bewusst NICHT übernommen wurde, steht der Grund am Feld.
--
-- id-Typ: uuid statt fortlaufender Zahl für alle personenbezogenen Entitäten —
-- verhindert, dass eine Familie/Person über die reine ID einer anderen erraten
-- werden kann (Defense in Depth zusätzlich zum ohnehin nötigen Ownership-Check,
-- idea/04). Nativ ab Postgres 13 (gen_random_uuid()), keine Extension nötig.
-- Kleine Referenztabellen (Lookups, Klassen): integer-Identity, kein
-- Ownership-Check nötig, tauchen nie in einer URL für Externe auf.
--
-- Ein Ort pro Sachverhalt (rules.md Abschnitt 1): jedes Attribut existiert an
-- genau einer Stelle. Kein Feld darf je nach Fall in zwei Tabellen stehen können,
-- sonst wird bei einer Änderung eine der beiden Stellen vergessen. Deshalb:
--   * persons trägt, was JEDE natürliche Person hat (Identität, Erreichbarkeit,
--     Anschrift) — Demografie steht am Kind, Beruf am Erziehungsberechtigten.
--   * Kind, Erziehungsberechtigte, Kontakt und Zahlungsverantwortliche/r sind
--     Rollen AUF persons, keine parallelen Personentabellen mit je eigenen
--     Namens-/Telefonspalten.
--   * Organisationen sind eine eigene Tabelle, nicht ein Satz Zusatzspalten auf
--     guardians, die bei natürlichen Personen leer bliebe.
--   * Kein abgeleitetes/redundantes Feld — auch nicht Klassenstufe und Klasse am
--     Kind: children.provisional_grade_level_id und children.class_id schließen
--     sich per CHECK gegenseitig aus, es gibt also nie zwei Werte für denselben
--     Sachverhalt gleichzeitig (Begründung an der Tabelle).
--
-- Datensparsamkeit (rules.md Abschnitt 7): ein Feld existiert nur, wenn es auf
-- einem realen Formular steht ODER ein benannter Prozess es braucht. Deshalb
-- führen Erziehungsberechtigte kein Geburtsdatum und keine Demografie.
--
-- Audit-Spalten: created_at/created_by/updated_at/updated_by auf jeder Tabelle mit
-- veränderlichem Inhalt (idea/03) — dazu zählen classes/grade_levels (Jahreslauf
-- bzw. Regeländerung über die Verwaltungsoberfläche sind ebenfalls Änderungen),
-- nicht aber die übrigen, nur per Bezeichnung änderbaren Lookup-Tabellen.
-- Format von created_by/updated_by:
--   "<oid>"            — Entra-ID Object-ID des internen Nutzers (stabil, überlebt
--                        Namens-/Mailwechsel, anders als UPN)
--   "guardian:<uuid>"  — Erziehungsberechtigte über den OTP-Pfad (idea/04)
--   "system:<job>"     — automatische Läufe (z. B. "system:import", "system:rollover")
-- Alle vier Spalten werden per Trigger gefüllt (ganz unten), nicht von der
-- Anwendung — kein Schreibpfad kann sie vergessen. created_by/updated_by sind
-- zusätzlich NOT NULL: der Trigger ist der Regelweg, NOT NULL der Schema-Backstop,
-- falls ein Schreibpfad den Trigger je umgeht (z. B. absichtlich deaktiviert für
-- einen Bulk-Import).

CREATE EXTENSION IF NOT EXISTS citext;  -- für case-insensitive E-Mail-Vergleiche

-- ---------------------------------------------------------------------------
-- Lookup-Tabellen (rules.md Abschnitt 3: Kategoriewerte als Daten, nicht als
-- ENUM/CHECK) — Bezeichnung frei änderbar über die Verwaltungsoberfläche, keine
-- Migration pro Umbenennung.
-- ---------------------------------------------------------------------------

CREATE TABLE genders (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE   -- z. B. "männlich", "weiblich", "divers", "keine Angabe"
);

-- Anrede für Anschreiben ("Herr", "Frau", "keine Anrede"). Bewusst getrennt vom
-- Geschlecht und NICHT daraus abgeleitet: Geschlecht ist das amtliche Merkmal für
-- ASV-BW/Statistik, die Anrede die Ansprache im Schreiben — bei "divers", bei
-- "keine Anrede" (Anrede steckt schon im Namen, z. B. "Freiherr von") und bei
-- persönlicher Präferenz gibt es keine Ableitung. ASV-BW und SVWS-NRW führen
-- beide Felder ebenfalls nebeneinander. Fehlt heute im ASV-Export nach Vis365
-- und damit in M365 — Rundschreiben sind deshalb dort nicht sauber anredbar.
CREATE TABLE salutations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Akademischer Grad ("Dr.", "Prof. Dr.") — gehört zur Ansprache im Schreiben,
-- nicht zum Namen. Werteliste wie in ASV-BW (wl_akademischer_grad).
CREATE TABLE academic_titles (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Klassifizierung einer Erziehungsberechtigten-Beziehung (z. B. "Elternteil",
-- "Pflegeeltern", "Jugendamt", "Vereinsvormund") — rein informativ. Hängt an
-- family_guardians, nicht am Erziehungsberechtigten: dieselbe Person kann in
-- einer Familie leiblicher Elternteil und in einer anderen Pflegeelternteil sein.
-- Entspricht K_ErzieherArt in SVWS-NRW.
CREATE TABLE guardian_categories (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE denominations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE   -- z. B. "römisch-katholisch", "evangelisch", "konfessionslos"
);

-- Art einer Telefonnummer ("Festnetz", "Mobil", "Arbeit"). Lookup statt fester
-- Spalten, damit eine vierte Art eine Datenzeile ist und keine Migration —
-- Muster von SVWS-NRW (K_TelefonArt) und ASV-BW (Kommunikationstyp).
CREATE TABLE phone_types (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Schulzweig — heute Grundschule und Realschule (fachdomaenen.md Abschnitt 1).
CREATE TABLE school_branches (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Klassenstufen als Daten statt als Zahlenbereich: label ist frei ("1", "10",
-- "VKL", "J1"), sort_order ordnet innerhalb des Zweigs. is_final_grade markiert
-- die jeweils letzte Klasse eines Zweigs und ersetzt damit die 4/10-Konstante
-- der Putzdienst-Regel (domains/putzdienst.md, „Abgänge & Klassenstufen-
-- Übergänge") — Regeländerung ist ein UPDATE, keine Migration und kein Codetouch
-- (rules.md Abschnitt 3). Mit Audit-Spalten, anders als die übrigen Lookup-
-- Tabellen: is_final_grade steuert die Putzdienst-Abgangslogik direkt, eine
-- unbemerkte Fehländerung hat also eine reale Auswirkung auf laufende
-- Zuteilungen statt nur eine Bezeichnung zu ändern.
CREATE TABLE grade_levels (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(id) ON DELETE RESTRICT,
    label            text NOT NULL,
    sort_order       smallint NOT NULL,
    is_final_grade   boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, label),
    UNIQUE (school_branch_id, sort_order),
    -- Ziel des zusammengesetzten Fremdschlüssels von classes unten — hält
    -- classes.school_branch_id konsistent zur jeweils referenzierten
    -- Klassenstufe, statt es unabhängig pflegbar zu lassen.
    UNIQUE (id, school_branch_id)
);

-- Klasse als Kohorte ("RS25a"), nicht als Klassenstufen-Slot: die Zeile gehört
-- zur Gruppe Kinder, die gemeinsam eingeschult wurde (Zweig + Eintrittsjahr +
-- Zug), nicht zu einer festen Klassenstufe. Der Zug (a/b) bleibt über die
-- gesamte Schulzeit stabil, auch wenn einzelne Kinder wechseln/dazukommen/
-- abgehen (domains/stammdaten.md) — deshalb trägt die Zeile selbst die
-- Kohorten-Identität (school_branch_id, entry_year, stream). grade_level_id
-- ist die AKTUELLE Klassenstufe und wird beim jährlichen Jahreslauf auf
-- derselben Zeile fortgeschrieben, ohne die Kinder auf eine andere Klassenzeile
-- umzuhängen. Diese Kennung ist an der Schule bereits im Gebrauch, u. a. für
-- die digitale Schülerakte — Ordnerstruktur/Ablage bleiben über die gesamte
-- Schulzeit einer Kohorte stabil.
--
-- entry_year: Kalenderjahr, in dem das Schuljahr der Kohorte beginnt, vierstellig
-- (z. B. 2025 für Schuljahr 25/26) — konsistent mit date_of_birth/entry_date,
-- keine Y2K-artige Mehrdeutigkeit. Die zweistellige Kurzform in „RS25a" ist reine
-- Anzeigeberechnung (entry_year % 100), kein eigener Speicherwert.
--
-- Kein Anzeigename als Spalte: sowohl die aktuelle Klassenbezeichnung ("5a",
-- für Klassenlisten/M365-Verteiler/Vis365-Export) als auch die Kohorten-
-- Kennung ("RS25a", für die Akte) sind aus school_branch_id, entry_year,
-- stream und der jeweils aktuellen grade_levels.label berechenbar — kein
-- abgeleitetes/redundantes Feld (rules.md Abschnitt 1).
--
-- school_branch_id ist eine kontrollierte Doppelung zu grade_level_id:
-- school_branch_id + entry_year + stream müssen zusammen eindeutig sein (zwei
-- Zweige können im selben Jahr beide einen Zug "a" einschulen) — das geht nur
-- mit einer echten Spalte, nicht über den Umweg grade_level_id →
-- grade_levels.school_branch_id. Der zusammengesetzte Fremdschlüssel hält
-- beide Spalten konsistent.
CREATE TABLE classes (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(id) ON DELETE RESTRICT,
    grade_level_id   integer NOT NULL REFERENCES grade_levels(id) ON DELETE RESTRICT,
    entry_year       smallint NOT NULL,
    stream           text NOT NULL,          -- "a", "b", … — schulintern frei, kein Lookup nötig (keine schulübergreifend wiederverwendete Kategorie)
    -- Audit-Spalten hier wie bei grade_levels bewusst vorhanden, anders als bei
    -- den übrigen Lookup-Tabellen: grade_level_id wird vom Jahreslauf jährlich
    -- fortgeschrieben (Tabellenkommentar oben) — ohne created_by/updated_by
    -- wäre ein fehlerhafter Lauf nicht auf Verursacher/Zeitpunkt zurückzuführen.
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       text NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       text NOT NULL,
    UNIQUE (school_branch_id, entry_year, stream),
    FOREIGN KEY (grade_level_id, school_branch_id) REFERENCES grade_levels(id, school_branch_id),
    CHECK (entry_year BETWEEN 2000 AND 2100)
);

-- Abgebende Schule (Realschul-Voranmeldeformular, siehe children.previous_school_id).
-- Lookup statt Freitext, weil dieselbe Grundschule sonst in drei Schreibweisen
-- in der Datenbank steht; wächst über die Verwaltungsoberfläche.
CREATE TABLE previous_schools (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Anschrift
-- ---------------------------------------------------------------------------

-- Eigene Tabelle statt Adressspalten an jeder Person: Kind und ein oder beide
-- Erziehungsberechtigte wohnen im Regelfall unter derselben Anschrift — eine
-- Familie zieht um, und ohne gemeinsame Zeile wären das drei bis fünf
-- Änderungen, von denen erfahrungsgemäß eine vergessen wird (rules.md
-- Abschnitt 1). ASV-BW löst es genauso (svp_anschrift, referenziert von Person
-- und Kontakt); SVWS-NRW dupliziert die Adresse stattdessen an Schüler und
-- Erzieher — genau der Zustand, den wir vermeiden wollen.
--
-- Preis dieser Entscheidung, in der Verwaltungsoberfläche zu lösen und nicht im
-- Schema: eine geteilte Zeile zu ändern ändert sie für alle, die daran hängen.
-- Die Maske muss beim Bearbeiten fragen „nur für diese Person" (= neue Zeile
-- anlegen und umhängen) oder „für alle an dieser Anschrift" (= Zeile ändern).
-- Der Trennungsfall — ein Elternteil zieht aus — ist der erste Fall, nicht der
-- zweite. Index auf persons.address_id existiert genau für diese Rückfrage.
--
-- Getrennte Personen bekommen dadurch je ihre eigene Adresszeile; es gibt
-- weiterhin keine mehrdeutige "Familienadresse".
CREATE TABLE addresses (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    street       text,
    house_number text,               -- text statt Zahl wegen "12a", "12-14"
    district     text,               -- Teilort (baden-württembergische Besonderheit, ASV: ortsteil)
    postal_code  text,
    city         text,
    country      text NOT NULL DEFAULT 'DE' CHECK (country ~ '^[A-Z]{2}$'),  -- ISO 3166-1 alpha-2
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text NOT NULL
);
-- Ohne diesen Index findet die Eingabemaske eine bestehende Adresszeile beim
-- Erfassen praktisch nie (voller Scan pro Eingabe) — dann sammeln sich
-- Dubletten an, und das ganze „geteilte Anschrift"-Konzept oben verwaist in
-- der Praxis. Bewusst kein UNIQUE: der dokumentierte „nur für diese Person"-Split
-- legt kurzzeitig bewusst eine wertgleiche Zweitzeile an.
CREATE INDEX ON addresses (postal_code, street, house_number);

-- ---------------------------------------------------------------------------
-- Personen und Organisationen
-- ---------------------------------------------------------------------------

-- Person: gemeinsame Stammdaten jedes natürlichen Menschen im System — Kind,
-- natürliche Erziehungsberechtigte-Person, Kontaktperson, Zahlungsverantwortliche/r;
-- künftig auch Personal/Lehrer. Nur Attribute, die für jede Rolle gelten;
-- Rollenspezifisches steht auf children/guardians/payers. Organisationen sind
-- keine Personen (eigene Tabelle unten). Entspricht svp_person (ASV-BW) und
-- gibbonPerson (Gibbon).
CREATE TABLE persons (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    salutation_id     integer REFERENCES salutations(id) ON DELETE RESTRICT,
    academic_title_id integer REFERENCES academic_titles(id) ON DELETE RESTRICT,
    first_name        text,            -- nullable: seltene Einzelname-Fälle
    last_name         text NOT NULL,
    gender_id         integer REFERENCES genders(id) ON DELETE RESTRICT,
    address_id        uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    -- E-Mail der Person, eindeutig (UNIQUE). Bei Erziehungsberechtigten
    -- zugleich die Identität für den OTP-Login (idea/04) — UNIQUE stellt damit
    -- sicher, dass ein Treffer bei der OTP-Prüfung immer genau eine Person
    -- ergibt, nie eine Mehrdeutigkeit zwischen mehreren Personen. Jede Person
    -- braucht deshalb eine eigene Adresse, auch wenn zwei Erziehungsberechtigte
    -- bislang eine Mailbox geteilt haben. E-Mail-basierte Authentifizierung
    -- beweist trotzdem weiterhin nur Postfach-Zugriff, nie zwingend die
    -- dahinterstehende Einzelperson — Prozesse mit echtem Einzelzustimmungs-
    -- bedarf (z. B. Schulvertrag, wo beide Erziehungsberechtigte separat
    -- zustimmen müssen) brauchen deshalb weiterhin eine eigene, explizite
    -- Zustimmungserfassung je Erziehungsberechtigtem (Anmeldeprozess-
    -- Fachdomäne) statt sich auf die Login-Identität zu verlassen. Beim Kind
    -- bleibt die Mail beim Import leer; befüllt wird sie erst durch die
    -- spätere M365-Kontenverwaltung (Schulpostfach, fachdomaenen.md
    -- Abschnitt 6) — ein Login-Ziel wird das Kind dadurch nicht, Weltenbaum
    -- kennt für Schüler keinen Zugangsweg.
    email             citext UNIQUE,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text NOT NULL,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text NOT NULL,
    -- Leerstring statt NULL ist ein typisches Import-Artefakt (CSV/Excel) und
    -- würde bei sonstiger Auswertung wie ein Wert statt wie „keine Angabe"
    -- behandelt — billig hier verhindert. Mit UNIQUE oben zusätzlich wichtig:
    -- ohne diesen CHECK würde bereits die zweite Person mit Leerstring-Mail
    -- (z. B. ein Kind vor der M365-Kontenverwaltung) den UNIQUE-Constraint
    -- verletzen.
    CHECK (email <> '')
);
CREATE INDEX ON persons (address_id);
-- UNIQUE oben legt den Index für den OTP-Login (idea/04) automatisch an,
-- kein separates CREATE INDEX nötig.
-- Ein normaler B-Tree kann unter einer echten (nicht-C-)Collation kein
-- `LIKE 'Müll%'` beschleunigen, nur Gleichheit — für die Namenssuche der
-- Verwaltungsoberfläche (Präfix, case-insensitiv) nötig: text_pattern_ops auf
-- lower(last_name), deckt dabei auch die case-insensitive Gleichheitssuche
-- (Dublettenprüfung Nachname+Geburtsdatum, domains/stammdaten.md) mit ab.
CREATE INDEX ON persons (lower(last_name) text_pattern_ops);

-- Organisation als Erziehungsberechtigte (Jugendamt, Pflegedienst, Vereinsvormund
-- — real vorkommend, domains/stammdaten.md). Eigene Anschrift und Telefonnummer,
-- weil die Schule sie anschreiben und anrufen können muss. Der fallbezogene
-- Sachbearbeiter steht nicht hier, sondern an family_guardians: das Jugendamt
-- vergibt ihn pro Fall, nicht pro Behörde.
CREATE TABLE organizations (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text NOT NULL,
    address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    email      citext,               -- Leerstring-Import-Artefakt: CHECK unten, Begründung an persons.email
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL,
    CHECK (email <> '')
);
CREATE INDEX ON organizations (address_id);

-- Telefonnummern als Zeilen statt als feste Spalten (Festnetz/Arbeit/Mobil):
-- eine weitere Art ist damit eine Datenzeile, keine Migration. is_primary
-- kennzeichnet die von der Person benannte Hauptnummer — für O365-Kontakte und
-- den telefonischen Erstkontakt braucht es eine eindeutige Auswahl statt
-- Zufall. Muster von SVWS-NRW (SchuelerTelefone + K_TelefonArt) und ASV-BW
-- (svp_kommunikation); Gibbon nimmt stattdessen vier feste Slots phone1..phone4
-- und kann deshalb keine fünfte Nummer.
--
-- Gehört entweder zu einer Person ODER zu einer Organisation — dieselbe
-- Entweder-oder-Modellierung wie bei guardians unten, damit die Nummer einer
-- Behörde nicht in einer zweiten Tabelle landet.
CREATE TABLE phone_numbers (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid REFERENCES persons(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
    phone_type_id   integer NOT NULL REFERENCES phone_types(id) ON DELETE RESTRICT,
    number          text NOT NULL,
    is_primary      boolean NOT NULL DEFAULT false,
    note            text,               -- z. B. "nur vormittags"
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL))
);
CREATE INDEX ON phone_numbers (person_id);
CREATE INDEX ON phone_numbers (organization_id);
-- Höchstens eine Hauptnummer je Person bzw. je Organisation.
CREATE UNIQUE INDEX ON phone_numbers (person_id)       WHERE is_primary AND person_id IS NOT NULL;
CREATE UNIQUE INDEX ON phone_numbers (organization_id) WHERE is_primary AND organization_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Familie, Kind, Erziehungsberechtigte
-- ---------------------------------------------------------------------------

-- Familie: Sorgerecht-Konstellation, nicht Haushalt (domains/stammdaten.md).
-- Manuell durch die Verwaltung gepflegt, kein abgeleitetes Feld. Bewusst ohne
-- Bezeichnungsfeld: ein „Familie Müller" veraltet beim ersten Namenswechsel und
-- ist ohnehin aus den Mitgliedern ableitbar. Gibbon führt dieselbe Struktur
-- (gibbonFamily + gibbonFamilyAdult + gibbonFamilyChild), hängt dort aber
-- zusätzlich die Wohnanschrift an die Familie — bei uns falsch, weil Familie
-- hier die Sorgerechtslage abbildet und nicht den gemeinsamen Haushalt.
CREATE TABLE families (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL
);

-- Kind: IST eine Person (immer natürliche Person) — deshalb teilt sich children.id
-- direkt mit persons.id, keine eigene person_id-Spalte. Hier stehen die Felder,
-- die es nur beim Kind gibt: Demografie (aus Voranmeldeformular und ASV-BW-Export,
-- Zweck ist die Übernahme nach ASV-BW) und Schulbezug. Erziehungsberechtigte
-- bekommen diese Felder bewusst nicht (Datensparsamkeit, rules.md Abschnitt 7).
--
-- provisional_grade_level_id UND class_id schließen sich gegenseitig aus (CHECK
-- unten) — keine gekoppelte Kopie, keine Redundanz, die auseinanderlaufen
-- könnte. Ist eine Klasse zugeteilt, kommt die aktuelle Klassenstufe
-- ausschließlich per Join aus classes.grade_level_id; provisional_grade_level_id
-- trägt nur den Zustand „Klassenstufe bekannt, Klasse (a/b) noch nicht
-- zugeteilt" — z. B. vor der Klassenzuteilung im Jahreslauf oder bevor die
-- Klassenzeilen eines neuen Jahrgangs überhaupt existieren. Ein Ferienprogramm-
-- Kind (fachdomaenen.md Abschnitt 1, auch für schulfremde Kinder offen) hat
-- weder das eine noch das andere gesetzt. Absichtlich NICHT „grade_level_id"
-- genannt: der Name macht sichtbar, dass ein direkter Lesezugriff bei
-- zugeteilter Klasse NULL liefert, statt still einen falschen/veralteten Wert
-- vorzutäuschen. Der Jahreslauf einer fortbestehenden Kohorte schreibt dadurch
-- nur classes.grade_level_id fort (wenige Zeilen) — kein Kind wird dafür
-- angefasst.
CREATE TABLE children (
    id                 uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    family_id          uuid REFERENCES families(id) ON DELETE RESTRICT,  -- nullable: Familie wird ggf. erst nach dem Import zugeordnet
    nickname           text,               -- Rufname, falls abweichend vom Vornamen — Schulalltag (Lehrer), nicht amtlicher Schriftverkehr; ASV-BW bleibt für die amtliche Rufname/Vorname-Unterscheidung führend
    date_of_birth      date NOT NULL,
    birthplace         text,
    birth_country      text CHECK (birth_country ~ '^[A-Z]{2}$'),        -- ISO 3166-1 alpha-2
    nationality        text CHECK (nationality ~ '^[A-Z]{2}$'),
    second_nationality text CHECK (second_nationality ~ '^[A-Z]{2}$'),   -- doppelte Staatsangehörigkeit
    home_language      text,               -- BCP 47; ein Feld für Verkehrs-/Muttersprache, siehe domains/stammdaten.md
    -- Konfession/Kirchengemeinde: Art.-9-DSGVO-Daten (besondere Kategorie,
    -- Religionszugehörigkeit, Voranmeldeformular). Rollenspezifisch auf
    -- children UND guardians statt an der gemeinsamen Basistabelle persons —
    -- dieselbe Feld-pro-Rolle-Regel wie occupation bei guardians: contacts/
    -- payers können die Spalte damit strukturell gar nicht erst befüllen, nicht
    -- nur per Konvention. Schutz zusätzlich per Spalten-GRANT auf genau diese
    -- zwei Spalten je Tabelle statt über eine eigene Tabellengrenze
    -- (wb-backend/db/init-roles.sh; Owner von children/guardians darf dabei
    -- nicht backend_runtime sein, sonst greift das Spalten-GRANT nicht).
    denomination_id    integer REFERENCES denominations(id) ON DELETE RESTRICT,
    congregation       text,               -- Kirchengemeinde, Freitext
    provisional_grade_level_id integer REFERENCES grade_levels(id) ON DELETE RESTRICT,  -- NUR gültig, solange class_id NULL ist (CHECK unten) — danach gilt classes.grade_level_id
    class_id           integer REFERENCES classes(id) ON DELETE RESTRICT,  -- Klasse; NULL solange nicht zugeteilt oder nicht eingeschult
    entry_date         date,               -- Eintrittsdatum: Grundlage der Quereinsteiger-Proration (domains/putzdienst.md)
    exit_date          date,               -- Abgangsdatum: Löschfrist-Anker (idea/06-dsgvo-organisatorisch.md)
    previous_school_id integer REFERENCES previous_schools(id) ON DELETE RESTRICT,  -- abgebende Schule (Realschul-Voranmeldung)
    previous_school_consent_at timestamptz,  -- Einwilligung zur Auskunftseinholung dort; NULL = keine Einwilligung. Zeitpunkt statt Boolean wegen Nachweispflicht (Art. 7 Abs. 1 DSGVO)
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    CHECK (second_nationality IS NULL OR nationality IS NOT NULL),
    CHECK (exit_date IS NULL OR entry_date IS NULL OR exit_date >= entry_date),
    CHECK (previous_school_consent_at IS NULL OR previous_school_id IS NOT NULL),
    CHECK (class_id IS NULL OR provisional_grade_level_id IS NULL)
);
CREATE INDEX ON children (family_id);
CREATE INDEX ON children (class_id);
CREATE INDEX ON children (provisional_grade_level_id);
CREATE INDEX ON children (date_of_birth);

-- Erziehungsberechtigte: entweder eine natürliche Person ODER eine Organisation —
-- genau eine der beiden Referenzen ist gesetzt (CHECK unten). Die strukturelle
-- Unterscheidung trägt damit der Fremdschlüssel selbst; ein zusätzliches
-- is_organization-Flag wäre ein zweiter Ort für dieselbe Tatsache und könnte
-- widersprüchlich gepflegt werden. Die frei benennbare Klassifizierung
-- („Elternteil"/„Jugendamt") steht an der Familienzugehörigkeit unten.
--
-- Name, Anschrift, Telefon und E-Mail stehen nicht hier, sondern an persons bzw.
-- organizations — SVWS-NRW legt sie stattdessen als Anrede1/Name1/Vorname1 +
-- Anrede2/Name2/Vorname2 in EINE Zeile am Schüler (SchuelerErzAdr) und kann damit
-- weder Patchwork noch einen dritten Sorgeberechtigten abbilden.
CREATE TABLE guardians (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid UNIQUE REFERENCES persons(id) ON DELETE RESTRICT,
    organization_id uuid UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    occupation      text,               -- Beruf (Voranmeldeformular), nur bei natürlicher Person
    is_employee     boolean NOT NULL DEFAULT false,  -- Putzdienst-Befreiung (domains/putzdienst.md), nur bei natürlicher Person
    -- Konfession/Kirchengemeinde: Art.-9-DSGVO-Daten, Voranmeldeformular, nur
    -- bei natürlicher Person — Begründung und GRANT-Hinweis an children.denomination_id.
    denomination_id integer REFERENCES denominations(id) ON DELETE RESTRICT,
    congregation    text,               -- Kirchengemeinde, Freitext
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL)),
    CHECK (person_id IS NOT NULL OR (occupation IS NULL AND is_employee = false AND denomination_id IS NULL AND congregation IS NULL))
);

-- Erziehungsberechtigte↔Familie: M:N (Patchwork-Fall, domains/stammdaten.md).
-- Nur sorgerechtgebende Mitgliedschaft — reines Umgangsrecht wird hier nie
-- eingetragen. Diese Tabelle ist zugleich die Grundlage des OTP-Ownership-Checks
-- und die vorgesehene Stelle für eine spätere Sichtbarkeits-Einschränkung
-- zwischen Sorgeberechtigten (domains/stammdaten.md, „Offene Punkte") — Gibbon
-- führt dort genau dafür ein Flag (gibbonFamilyAdult.childDataAccess). Wir bauen
-- es erst, wenn ein Fall vorliegt; die Struktur muss dafür nicht geändert werden.
CREATE TABLE family_guardians (
    family_id            uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    guardian_id          uuid NOT NULL REFERENCES guardians(id) ON DELETE CASCADE,
    guardian_category_id integer REFERENCES guardian_categories(id) ON DELETE RESTRICT,
    -- nur bei Organisation: Sachbearbeiter für diesen Fall, Freitext (wechselt
    -- öfter, keine eigene Person-Zeile wert). Kein CHECK möglich (Organisations-
    -- Status steht auf guardians, nicht auf dieser Zeile) — durchgesetzt per
    -- Trigger unten (check_family_guardians_contact_person).
    contact_person       text,
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           text NOT NULL,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    updated_by           text NOT NULL,
    PRIMARY KEY (family_id, guardian_id)
);
CREATE INDEX ON family_guardians (guardian_id);

-- ---------------------------------------------------------------------------
-- Kontakte (nicht-rechtliche Bezugspersonen)
-- ---------------------------------------------------------------------------

-- Notfallkontakt/Abholberechtigt ohne Rechtsstellung — nie Datenzugriff, kein
-- Ownership-Check nötig, kein Login (domains/stammdaten.md). Rolle auf persons
-- wie children und guardians: dieselbe Großmutter, die für ein Enkelkind
-- Pflegeelternteil und für ein anderes nur Notfallkontakt ist, steht damit
-- einmal in der Datenbank statt zweimal, und Name/Telefon/Anschrift folgen
-- derselben Mechanik wie überall sonst. ASV-BW hängt an svp_kontakt ebenfalls
-- eine Anschrift; Gibbon legt Notfallkontakte dagegen als feste Spaltenpaare
-- (emergency1Name … emergency2Relationship) auf die Person des Kindes und
-- kann deshalb keinen dritten Kontakt und keine geteilte Nummer.
--
-- Preis dieser Vereinheitlichung: Anschrift und E-Mail sind für Kontakte
-- technisch befüllbar. Datensparsamkeit ist hier also nur noch eine Regel der
-- Eingabemaske, nicht mehr strukturell erzwungen — anders als bei Demografie
-- (nur children) und Beruf (nur guardians), die weiterhin an der Rollentabelle
-- hängen und für andere Rollen gar nicht existieren.
CREATE TABLE contacts (
    id         uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    notes      text,               -- z. B. "nur nachmittags erreichbar"
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL
);

-- relationship steht an der Verknüpfung, nicht am Kontakt: „Großmutter" gilt
-- relativ zum Kind, nicht absolut zur Person. Verknüpfung an das Kind und nicht
-- an die Familie, weil ein Kind vor der manuellen Familienzuordnung noch keine
-- Familie hat.
--
-- priority: Reihenfolge „Notfallkontakt 1/2/3", ein realer Prozess an dieser
-- Schule — anders als die bewusst nicht übernommene Gibbon-contactPriority bei
-- Erziehungsberechtigten (domains/stammdaten.md). Nullable, weil nicht jede
-- Verknüpfung eine Reihenfolge braucht (z. B. reine Abholberechtigung ohne
-- Notfall-Rolle); wo gesetzt, höchstens einmal je Kind (UNIQUE unten) — keine
-- zwei Kontakte mit demselben Rang.
CREATE TABLE child_contacts (
    child_id     uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    relationship text,               -- Freitext: "Großmutter", "Nachbarin" — keine Rechtsklassifizierung, daher kein CHECK
    priority     smallint,
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text NOT NULL,
    PRIMARY KEY (child_id, contact_id)
);
CREATE INDEX ON child_contacts (contact_id);
CREATE UNIQUE INDEX ON child_contacts (child_id, priority) WHERE priority IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Zahlungsverantwortliche
-- ---------------------------------------------------------------------------

-- Zahlungsverantwortlich für ein Kind ist nicht dasselbe wie sorgeberechtigt
-- (domains/stammdaten.md) — Großeltern zahlen mit oder allein, ohne
-- Erziehungsberechtigte zu sein; das Jugendamt übernimmt bei Kostenübernahmen
-- (z. B. Ferienprogramm) direkt als Organisation. Deshalb eine eigene Rolle
-- statt Wiederverwendung von guardians/contacts, mit demselben
-- Entweder-Person-oder-Organisation-Muster wie guardians (Fremdschlüssel trägt
-- die Unterscheidung, kein zusätzliches Flag).
--
-- Bewusst KEIN Anteil/Betrag je Zahler (Bezuschussung, Gutscheine) — offener
-- Punkt, noch zu klären; child_payers.is_primary hält vorerst nur fest, wer
-- der/die Hauptzahler:in ist, analog phone_numbers.is_primary.
--
-- IBAN/BIC sind sensible, aber keine Art.-9-Daten — eigene Rollentabelle statt
-- Spalten auf persons/children/guardians (anders als Konfession oben): der
-- Zugriffskontext ist ein anderer (Abrechnung statt allgemeines Personenprofil),
-- betrifft nur wenige Personen, und die meisten Abfragen auf persons brauchen
-- die Daten nie mit. Eigene, engere DB-Rolle wie bei den Konfessionsspalten
-- (wb-backend/db/init-roles.sh).
--
-- billing_address_id nullable: NULL heißt „Anschrift der zahlenden
-- Person/Organisation gilt", nur bei abweichender Rechnungsadresse gesetzt —
-- kein Pflicht-Duplikat der ohnehin vorhandenen Adresse.
CREATE TABLE payers (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id          uuid UNIQUE REFERENCES persons(id) ON DELETE RESTRICT,
    organization_id    uuid UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    billing_address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    iban               text,
    bic                text,
    account_holder     text,               -- Kontoinhaber, falls abweichend vom Namen der Person/Organisation
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text NOT NULL,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL))
);
CREATE INDEX ON payers (billing_address_id);

-- Kind↔Zahler: M:N (mehrere Zahler je Kind für Bezuschussungsfälle, dieselbe
-- zahlende Person/Organisation ggf. für mehrere Kinder). ON DELETE RESTRICT
-- auf child_id: ein Kind mit noch bestehender Zahlungsverantwortung wird nicht
-- nebenbei mitgelöscht, das ist eine echte Entscheidung wie bei guardians
-- (domains/stammdaten.md, „Löschmechanik") — anders als child_contacts, das
-- keine Rechtsfolge hat.
CREATE TABLE child_payers (
    child_id   uuid NOT NULL REFERENCES children(id) ON DELETE RESTRICT,
    payer_id   uuid NOT NULL REFERENCES payers(id) ON DELETE CASCADE,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL,
    PRIMARY KEY (child_id, payer_id)
);
CREATE INDEX ON child_payers (payer_id);
-- Höchstens eine/r Hauptzahler:in je Kind.
CREATE UNIQUE INDEX ON child_payers (child_id) WHERE is_primary;

-- ---------------------------------------------------------------------------
-- Audit-Spalten automatisch fortschreiben. In der Datenbank statt in der
-- Anwendung, damit kein Schreibpfad sie vergessen kann (idea/03) — sonst bleibt
-- updated_at für immer auf dem Einfüge-Zeitpunkt stehen und der Audit-Trail ist
-- wertlos.
--
-- Den Verursacher kennt nur die Anwendung. Sie setzt ihn einmal pro Transaktion
-- als Sitzungsvariable (SET LOCAL app.actor = '<oid>' / 'guardian:<uuid>' /
-- 'system:<job>'), der Trigger schreibt ihn in jede berührte Zeile. Fehlt die
-- Variable, scheitert der Schreibpfad hart (rules.md Abschnitt 3: „ein stiller
-- Fehlschlag zählt als nicht vorhanden") statt einen leeren oder veralteten
-- Verursacher stehen zu lassen. nullif(..., '') ist dabei nötig: Postgres
-- liefert für eine per SET LOCAL gesetzte Sitzungsvariable außerhalb der
-- setzenden Transaktion nicht NULL zurück, sondern einen Leerstring — ohne
-- nullif würde ein Schreibpfad, der SET LOCAL vergisst, unbemerkt mit leerem
-- Verursacher durchlaufen statt hart zu scheitern.
--
-- Bewusst KEINE separate Änderungshistorie-Tabelle: kein aktueller Prozess
-- braucht mehr als „wer hat zuletzt geändert" (rules.md Abschnitt 1). Die vier
-- Spalten bleiben der Anknüpfungspunkt, falls doch einmal eine volle Historie
-- nötig wird.
-- ---------------------------------------------------------------------------

CREATE FUNCTION set_row_audit() RETURNS trigger AS $$
DECLARE
    actor text := nullif(current_setting('app.actor', true), '');
BEGIN
    IF actor IS NULL THEN
        RAISE EXCEPTION 'app.actor nicht gesetzt — SET LOCAL app.actor vor jedem Schreibzugriff auf eine Audit-Tabelle';
    END IF;
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := now();
        NEW.created_by := actor;
    ELSE
        NEW.created_at := OLD.created_at;   -- unveränderlich
        NEW.created_by := OLD.created_by;
    END IF;
    NEW.updated_at := now();
    NEW.updated_by := actor;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON grade_levels
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON classes
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON persons
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON organizations
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON phone_numbers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON families
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON children
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON family_guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON payers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_payers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();

-- ---------------------------------------------------------------------------
-- family_guardians.contact_person nur bei Organisation als Erziehungsberechtigte
-- (Tabellenkommentar oben) — kein CHECK möglich, weil der Organisations-Status
-- auf guardians steht, einer anderen Tabelle als contact_person selbst; CHECK-
-- Constraints dürfen keine andere Tabelle nachschlagen. Analog zu
-- guardians.occupation, nur eben cross-table statt in derselben Zeile.
-- ---------------------------------------------------------------------------

CREATE FUNCTION check_family_guardians_contact_person() RETURNS trigger AS $$
BEGIN
    IF NEW.contact_person IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM guardians WHERE id = NEW.guardian_id AND organization_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'contact_person nur zulässig, wenn guardian_id eine Organisation ist (guardian_id %)', NEW.guardian_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_family_guardians_contact_person BEFORE INSERT OR UPDATE ON family_guardians
    FOR EACH ROW EXECUTE FUNCTION check_family_guardians_contact_person();
