-- Stammdaten-Kernschema (Person, Adresse, Familie, Erziehungsberechtigte, Kind,
-- Kontakte). Konzeptioneller Entwurf zu domains/stammdaten.md — konkreter als
-- Prosa, aber noch kein Alembic-Migrationscode. Übertragung in SQLAlchemy-2.0-
-- Modelle + Alembic-Migration folgt im App-Stack-Repo (wb-backend), gemäß dessen
-- eigener CLAUDE.md (englische Bezeichner, dort Abschnitt 1/8).
--
-- Gegengelesen gegen vier reale Schulverwaltungs-Schemata (ASV-BW-Strukturdump,
-- SVWS-NRW, GibbonEdu, eigenes Vorprojekt), um Randfälle nicht neu zu erfinden.
-- Wo eine Referenz bewusst NICHT übernommen wurde, steht der Grund am Feld.
--
-- id-Typ: uuid statt fortlaufender Zahl für alle personenbezogenen Entitäten —
-- verhindert, dass eine Familie/Person über die reine ID einer anderen erraten
-- werden kann (Defense in Depth zusätzlich zum ohnehin nötigen Ownership-Check,
-- idea/04). Nativ ab Postgres 13 (gen_random_uuid()), keine Extension nötig.
-- Kleine Referenztabellen (Lookups, Klassen): integer-Identity, kein
-- Ownership-Check nötig, tauchen nie in einer URL für Externe auf.
--
-- Ein Ort pro Sachverhalt (rules.md Abschnitt 1): jedes Attribut existiert an
-- genau einer Stelle. Kein Feld darf je nach Fall in zwei Tabellen stehen können,
-- sonst wird bei einer Änderung eine der beiden Stellen vergessen. Deshalb:
--   * persons trägt, was JEDE natürliche Person hat (Identität, Erreichbarkeit,
--     Anschrift) — Demografie steht am Kind, Beruf am Erziehungsberechtigten.
--   * Kind, Erziehungsberechtigte und Kontakt sind Rollen AUF persons, keine
--     parallelen Personentabellen mit je eigenen Namens-/Telefonspalten.
--   * Organisationen sind eine eigene Tabelle, nicht ein Satz Zusatzspalten auf
--     guardians, die bei natürlichen Personen leer bliebe.
--   * Kein abgeleitetes/redundantes Feld. Einzige Ausnahme: children.grade_level_id
--     neben children.class_id — per Fremdschlüssel gekoppelt, kann also nicht
--     auseinanderlaufen (Begründung an der Tabelle).
--
-- Datensparsamkeit (rules.md Abschnitt 7): ein Feld existiert nur, wenn es auf
-- einem realen Formular steht ODER ein benannter Prozess es braucht. Deshalb
-- führen Erziehungsberechtigte kein Geburtsdatum und keine Demografie.
--
-- Audit-Spalten: created_at/created_by/updated_at/updated_by auf jeder Tabelle mit
-- veränderlichem Inhalt (idea/03). Format von created_by/updated_by:
--   "<oid>"            — Entra-ID Object-ID des internen Nutzers (stabil, überlebt
--                        Namens-/Mailwechsel, anders als UPN)
--   "guardian:<uuid>"  — Erziehungsberechtigte über den OTP-Pfad (idea/04)
--   "system:<job>"     — automatische Läufe (z. B. "system:import", "system:rollover")
-- Alle vier Spalten werden per Trigger gefüllt (ganz unten), nicht von der
-- Anwendung — kein Schreibpfad kann sie vergessen.

CREATE EXTENSION IF NOT EXISTS citext;  -- für case-insensitive E-Mail-Vergleich/-Eindeutigkeit

-- ---------------------------------------------------------------------------
-- Lookup-Tabellen (rules.md Abschnitt 3: Kategoriewerte als Daten, nicht als
-- ENUM/CHECK) — Bezeichnung frei änderbar über die Verwaltungsoberfläche, keine
-- Migration pro Umbenennung.
-- ---------------------------------------------------------------------------

CREATE TABLE genders (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE   -- z. B. "männlich", "weiblich", "divers", "keine Angabe"
);

-- Anrede für Anschreiben ("Herr", "Frau", "keine Anrede"). Bewusst getrennt vom
-- Geschlecht und NICHT daraus abgeleitet: Geschlecht ist das amtliche Merkmal für
-- ASV-BW/Statistik, die Anrede die Ansprache im Schreiben — bei "divers", bei
-- "keine Anrede" (Anrede steckt schon im Namen, z. B. "Freiherr von") und bei
-- persönlicher Präferenz gibt es keine Ableitung. ASV-BW und SVWS-NRW führen
-- beide Felder ebenfalls nebeneinander. Fehlt heute im ASV-Export nach Vis365
-- und damit in M365 — Rundschreiben sind deshalb dort nicht sauber anredbar.
CREATE TABLE salutations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Akademischer Grad ("Dr.", "Prof. Dr.") — gehört zur Ansprache im Schreiben,
-- nicht zum Namen. Werteliste wie in ASV-BW (wl_akademischer_grad).
CREATE TABLE academic_titles (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Klassifizierung einer Erziehungsberechtigten-Beziehung (z. B. "Elternteil",
-- "Pflegeeltern", "Jugendamt", "Vereinsvormund") — rein informativ. Hängt an
-- family_guardians, nicht am Erziehungsberechtigten: dieselbe Person kann in
-- einer Familie leiblicher Elternteil und in einer anderen Pflegeelternteil sein.
-- Entspricht K_ErzieherArt in SVWS-NRW.
CREATE TABLE guardian_categories (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

CREATE TABLE denominations (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE   -- z. B. "römisch-katholisch", "evangelisch", "konfessionslos"
);

-- Art einer Telefonnummer ("Festnetz", "Mobil", "Arbeit"). Lookup statt fester
-- Spalten, damit eine vierte Art eine Datenzeile ist und keine Migration —
-- Muster von SVWS-NRW (K_TelefonArt) und ASV-BW (Kommunikationstyp).
CREATE TABLE phone_types (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Schulzweig — heute Grundschule und Realschule (fachdomaenen.md Abschnitt 1).
CREATE TABLE school_branches (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- Klassenstufen als Daten statt als Zahlenbereich: label ist frei ("1", "10",
-- "VKL", "J1"), sort_order ordnet innerhalb des Zweigs. is_final_grade markiert
-- die jeweils letzte Klasse eines Zweigs und ersetzt damit die 4/10-Konstante
-- der Putzdienst-Regel (domains/putzdienst.md, „Abgänge & Klassenstufen-
-- Übergänge") — Regeländerung ist ein UPDATE, keine Migration und kein Codetouch
-- (rules.md Abschnitt 3).
CREATE TABLE grade_levels (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_branch_id integer NOT NULL REFERENCES school_branches(id) ON DELETE RESTRICT,
    label            text NOT NULL,
    sort_order       smallint NOT NULL,
    is_final_grade   boolean NOT NULL DEFAULT false,
    UNIQUE (school_branch_id, label),
    UNIQUE (school_branch_id, sort_order),
    UNIQUE (id, school_branch_id)
);

-- Klasse ("5a") innerhalb einer Klassenstufe ("5") — die Einheit, in der die
-- Schule tatsächlich arbeitet: Klassenlisten, M365-Verteilerlisten, Vis365-Export.
-- Alle drei Referenzschemata trennen das ebenso (SVWS Klassen→Jahrgang, Gibbon
-- FormGroup→YearGroup, ASV svp_klasse).
--
-- Bewusst OHNE Schuljahresbezug, anders als in allen drei Referenzen: es gibt
-- hier keine Schuljahres-Historie (domains/stammdaten.md, „Schuljahreswechsel").
-- Die Klassenzeile "5a" ist dauerhaft; beim Jahreslauf im September werden die
-- Kinder von "5a" auf "6a" umgehängt, nicht die Klassenzeile umbenannt.
--
-- name ist der vollständige Anzeigename ("5a", "VKL"), nicht nur der Zusatz "a" —
-- zusammensetzen aus Klassenstufe + Suffix scheitert an Sonderfällen wie VKL, und
-- der Name ist ohnehin nur Beschriftung; die fachliche Zuordnung trägt der
-- Fremdschlüssel auf grade_levels.
CREATE TABLE classes (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_level_id integer NOT NULL REFERENCES grade_levels(id) ON DELETE RESTRICT,
    name           text NOT NULL UNIQUE,
    UNIQUE (id, grade_level_id)
);

-- Abgebende Schule (Realschul-Voranmeldeformular, siehe children.previous_school_id).
-- Lookup statt Freitext, weil dieselbe Grundschule sonst in drei Schreibweisen
-- in der Datenbank steht; wächst über die Verwaltungsoberfläche.
CREATE TABLE previous_schools (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Anschrift
-- ---------------------------------------------------------------------------

-- Eigene Tabelle statt Adressspalten an jeder Person: Kind und ein oder beide
-- Erziehungsberechtigte wohnen im Regelfall unter derselben Anschrift — eine
-- Familie zieht um, und ohne gemeinsame Zeile wären das drei bis fünf
-- Änderungen, von denen erfahrungsgemäß eine vergessen wird (rules.md
-- Abschnitt 1). ASV-BW löst es genauso (svp_anschrift, referenziert von Person
-- und Kontakt); SVWS-NRW dupliziert die Adresse stattdessen an Schüler und
-- Erzieher — genau der Zustand, den wir vermeiden wollen.
--
-- Preis dieser Entscheidung, in der Verwaltungsoberfläche zu lösen und nicht im
-- Schema: eine geteilte Zeile zu ändern ändert sie für alle, die daran hängen.
-- Die Maske muss beim Bearbeiten fragen „nur für diese Person" (= neue Zeile
-- anlegen und umhängen) oder „für alle an dieser Anschrift" (= Zeile ändern).
-- Der Trennungsfall — ein Elternteil zieht aus — ist der erste Fall, nicht der
-- zweite. Index auf persons.address_id existiert genau für diese Rückfrage.
--
-- Getrennte Personen bekommen dadurch je ihre eigene Adresszeile; es gibt
-- weiterhin keine mehrdeutige "Familienadresse".
CREATE TABLE addresses (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    street       text,
    house_number text,               -- text statt Zahl wegen "12a", "12-14"
    district     text,               -- Teilort (baden-württembergische Besonderheit, ASV: ortsteil)
    postal_code  text,
    city         text,
    country      text NOT NULL DEFAULT 'DE' CHECK (country ~ '^[A-Z]{2}$'),  -- ISO 3166-1 alpha-2
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text
);

-- ---------------------------------------------------------------------------
-- Personen und Organisationen
-- ---------------------------------------------------------------------------

-- Person: gemeinsame Stammdaten jedes natürlichen Menschen im System — Kind,
-- natürliche Erziehungsberechtigte-Person, Kontaktperson; künftig auch
-- Personal/Lehrer. Nur Attribute, die für jede Rolle gelten; Rollenspezifisches
-- steht auf children bzw. guardians. Organisationen sind keine Personen (eigene
-- Tabelle unten). Entspricht svp_person (ASV-BW) und gibbonPerson (Gibbon).
CREATE TABLE persons (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    salutation_id     integer REFERENCES salutations(id) ON DELETE RESTRICT,
    academic_title_id integer REFERENCES academic_titles(id) ON DELETE RESTRICT,
    first_name        text,            -- nullable: seltene Einzelname-Fälle
    last_name         text NOT NULL,
    gender_id         integer REFERENCES genders(id) ON DELETE RESTRICT,
    address_id        uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    -- E-Mail der Person. Bei Erziehungsberechtigten zugleich die Identität für
    -- den OTP-Login (idea/04) — daher UNIQUE. Beim Kind bleibt sie beim Import
    -- leer; befüllt wird sie erst durch die spätere M365-Kontenverwaltung
    -- (Schulpostfach, fachdomaenen.md Abschnitt 6). Ein Kind bleibt auch dann
    -- reines Datenobjekt: Weltenbaum kennt für Schüler keinen Login-Pfad.
    email             citext UNIQUE,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        text,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        text
);
CREATE INDEX ON persons (address_id);
CREATE INDEX ON persons (last_name);

-- Organisation als Erziehungsberechtigte (Jugendamt, Pflegedienst, Vereinsvormund
-- — real vorkommend, domains/stammdaten.md). Eigene Anschrift und Telefonnummer,
-- weil die Schule sie anschreiben und anrufen können muss. Der fallbezogene
-- Sachbearbeiter steht nicht hier, sondern an family_guardians: das Jugendamt
-- vergibt ihn pro Fall, nicht pro Behörde.
CREATE TABLE organizations (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text NOT NULL,
    address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT,
    email      citext,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text
);
CREATE INDEX ON organizations (address_id);

-- Telefonnummern als Zeilen statt als feste Spalten (Festnetz/Arbeit/Mobil):
-- eine weitere Art ist damit eine Datenzeile, keine Migration. is_primary
-- kennzeichnet die Hauptnummer — nötig, weil Vis365/M365 nur eine einzige Nummer
-- je Person übernehmen kann und sonst die Auswahl dem Zufall überlassen bliebe.
-- Muster von SVWS-NRW (SchuelerTelefone + K_TelefonArt) und ASV-BW
-- (svp_kommunikation); Gibbon nimmt stattdessen vier feste Slots phone1..phone4
-- und kann deshalb keine fünfte Nummer.
--
-- Gehört entweder zu einer Person ODER zu einer Organisation — dieselbe
-- Entweder-oder-Modellierung wie bei guardians unten, damit die Nummer einer
-- Behörde nicht in einer zweiten Tabelle landet.
CREATE TABLE phone_numbers (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid REFERENCES persons(id) ON DELETE CASCADE,
    organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
    phone_type_id   integer NOT NULL REFERENCES phone_types(id) ON DELETE RESTRICT,
    number          text NOT NULL,
    is_primary      boolean NOT NULL DEFAULT false,
    note            text,               -- z. B. "nur vormittags"
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL))
);
CREATE INDEX ON phone_numbers (person_id);
CREATE INDEX ON phone_numbers (organization_id);
-- Höchstens eine Hauptnummer je Person bzw. je Organisation.
CREATE UNIQUE INDEX ON phone_numbers (person_id)       WHERE is_primary AND person_id IS NOT NULL;
CREATE UNIQUE INDEX ON phone_numbers (organization_id) WHERE is_primary AND organization_id IS NOT NULL;

-- Konfession/Kirchengemeinde: Art.-9-DSGVO-Daten (besondere Kategorie,
-- Religionszugehörigkeit) — bewusst NICHT als Spalte auf persons, sondern in
-- einer eigenen Tabelle, damit die normale Laufzeit-Rolle sie NICHT sehen kann.
-- Konkrete Rollen-Anlage (eigene, engere Rolle statt der pauschalen
-- backend_runtime-Rolle aus wb-backend/db/init-roles.sh) folgt in wb-backend:
-- Views allein schützen nicht, nötig ist ein eigenes GRANT auf genau diese Tabelle.
CREATE TABLE person_religious_data (
    person_id       uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    denomination_id integer REFERENCES denominations(id) ON DELETE RESTRICT,
    congregation    text,               -- Kirchengemeinde, Freitext
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text
);

-- ---------------------------------------------------------------------------
-- Familie, Kind, Erziehungsberechtigte
-- ---------------------------------------------------------------------------

-- Familie: Sorgerecht-Konstellation, nicht Haushalt (domains/stammdaten.md).
-- Manuell durch die Verwaltung gepflegt, kein abgeleitetes Feld. Bewusst ohne
-- Bezeichnungsfeld: ein „Familie Müller" veraltet beim ersten Namenswechsel und
-- ist ohnehin aus den Mitgliedern ableitbar. Gibbon führt dieselbe Struktur
-- (gibbonFamily + gibbonFamilyAdult + gibbonFamilyChild), hängt dort aber
-- zusätzlich die Wohnanschrift an die Familie — bei uns falsch, weil Familie
-- hier die Sorgerechtslage abbildet und nicht den gemeinsamen Haushalt.
CREATE TABLE families (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text
);

-- Kind: IST eine Person (immer natürliche Person) — deshalb teilt sich children.id
-- direkt mit persons.id, keine eigene person_id-Spalte. Hier stehen die Felder,
-- die es nur beim Kind gibt: Demografie (aus Voranmeldeformular und ASV-BW-Export,
-- Zweck ist die Übernahme nach ASV-BW) und Schulbezug. Erziehungsberechtigte
-- bekommen diese Felder bewusst nicht (Datensparsamkeit, rules.md Abschnitt 7).
--
-- grade_level_id neben class_id ist die einzige bewusste Doppelung im Schema und
-- ist per Fremdschlüssel gegen Auseinanderlaufen gesichert: sind beide gesetzt,
-- erzwingt der zusammengesetzte Fremdschlüssel auf classes(id, grade_level_id),
-- dass die Klassenstufe zur Klasse passt. Nötig, weil beide Zustände real sind —
-- ein Kind ist der Klassenstufe zugeordnet, bevor die Klasse (a/b) feststeht, und
-- ein Ferienprogramm-Kind hat weder das eine noch das andere.
CREATE TABLE children (
    id                 uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    family_id          uuid REFERENCES families(id) ON DELETE RESTRICT,  -- nullable: Familie wird ggf. erst nach dem Import zugeordnet
    date_of_birth      date NOT NULL,
    birthplace         text,
    birth_country      text CHECK (birth_country ~ '^[A-Z]{2}$'),        -- ISO 3166-1 alpha-2
    nationality        text CHECK (nationality ~ '^[A-Z]{2}$'),
    second_nationality text CHECK (second_nationality ~ '^[A-Z]{2}$'),   -- doppelte Staatsangehörigkeit
    home_language      text,               -- BCP 47; ein Feld für Verkehrs-/Muttersprache, siehe domains/stammdaten.md
    grade_level_id     integer REFERENCES grade_levels(id) ON DELETE RESTRICT,
    class_id           integer,            -- Klasse; NULL solange nicht zugeteilt oder nicht eingeschult
    entry_date         date,               -- Eintrittsdatum: Grundlage der Quereinsteiger-Proration (domains/putzdienst.md)
    exit_date          date,               -- Abgangsdatum: Löschfrist-Anker (idea/06-dsgvo-organisatorisch.md)
    previous_school_id integer REFERENCES previous_schools(id) ON DELETE RESTRICT,  -- abgebende Schule (Realschul-Voranmeldung)
    previous_school_consent_at timestamptz,  -- Einwilligung zur Auskunftseinholung dort; NULL = keine Einwilligung. Zeitpunkt statt Boolean wegen Nachweispflicht (Art. 7 Abs. 1 DSGVO)
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         text,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    updated_by         text,
    CHECK (second_nationality IS NULL OR nationality IS NOT NULL),
    CHECK (exit_date IS NULL OR entry_date IS NULL OR exit_date >= entry_date),
    CHECK (previous_school_consent_at IS NULL OR previous_school_id IS NOT NULL),
    CHECK (class_id IS NULL OR grade_level_id IS NOT NULL),
    FOREIGN KEY (class_id, grade_level_id) REFERENCES classes(id, grade_level_id) ON DELETE RESTRICT
);
CREATE INDEX ON children (family_id);
CREATE INDEX ON children (class_id);

-- Erziehungsberechtigte: entweder eine natürliche Person ODER eine Organisation —
-- genau eine der beiden Referenzen ist gesetzt (CHECK unten). Die strukturelle
-- Unterscheidung trägt damit der Fremdschlüssel selbst; ein zusätzliches
-- is_organization-Flag wäre ein zweiter Ort für dieselbe Tatsache und könnte
-- widersprüchlich gepflegt werden. Die frei benennbare Klassifizierung
-- („Elternteil"/„Jugendamt") steht an der Familienzugehörigkeit unten.
--
-- Name, Anschrift, Telefon und E-Mail stehen nicht hier, sondern an persons bzw.
-- organizations — SVWS-NRW legt sie stattdessen als Anrede1/Name1/Vorname1 +
-- Anrede2/Name2/Vorname2 in EINE Zeile am Schüler (SchuelerErzAdr) und kann damit
-- weder Patchwork noch einen dritten Sorgeberechtigten abbilden.
CREATE TABLE guardians (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id       uuid UNIQUE REFERENCES persons(id) ON DELETE RESTRICT,
    organization_id uuid UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    occupation      text,               -- Beruf (Voranmeldeformular), nur bei natürlicher Person
    is_employee     boolean NOT NULL DEFAULT false,  -- Putzdienst-Befreiung (domains/putzdienst.md), nur bei natürlicher Person
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text,
    CHECK ((person_id IS NULL) <> (organization_id IS NULL)),
    CHECK (person_id IS NOT NULL OR (occupation IS NULL AND is_employee = false))
);

-- Erziehungsberechtigte↔Familie: M:N (Patchwork-Fall, domains/stammdaten.md).
-- Nur sorgerechtgebende Mitgliedschaft — reines Umgangsrecht wird hier nie
-- eingetragen. Diese Tabelle ist zugleich die Grundlage des OTP-Ownership-Checks
-- und die vorgesehene Stelle für eine spätere Sichtbarkeits-Einschränkung
-- zwischen Sorgeberechtigten (domains/stammdaten.md, „Offene Punkte") — Gibbon
-- führt dort genau dafür ein Flag (gibbonFamilyAdult.childDataAccess). Wir bauen
-- es erst, wenn ein Fall vorliegt; die Struktur muss dafür nicht geändert werden.
CREATE TABLE family_guardians (
    family_id            uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    guardian_id          uuid NOT NULL REFERENCES guardians(id) ON DELETE CASCADE,
    guardian_category_id integer REFERENCES guardian_categories(id) ON DELETE RESTRICT,
    contact_person       text,          -- nur bei Organisation: Sachbearbeiter für diesen Fall, Freitext (wechselt öfter, keine eigene Person-Zeile wert)
    created_at           timestamptz NOT NULL DEFAULT now(),
    created_by           text,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    updated_by           text,
    PRIMARY KEY (family_id, guardian_id)
);
CREATE INDEX ON family_guardians (guardian_id);

-- ---------------------------------------------------------------------------
-- Kontakte (nicht-rechtliche Bezugspersonen)
-- ---------------------------------------------------------------------------

-- Notfallkontakt/Abholberechtigt ohne Rechtsstellung — nie Datenzugriff, kein
-- Ownership-Check nötig, kein Login (domains/stammdaten.md). Rolle auf persons
-- wie children und guardians: dieselbe Großmutter, die für ein Enkelkind
-- Pflegeelternteil und für ein anderes nur Notfallkontakt ist, steht damit
-- einmal in der Datenbank statt zweimal, und Name/Telefon/Anschrift folgen
-- derselben Mechanik wie überall sonst. ASV-BW hängt an svp_kontakt ebenfalls
-- eine Anschrift; Gibbon legt Notfallkontakte dagegen als feste Spaltenpaare
-- (emergency1Name … emergency2Relationship) auf die Person des Kindes und
-- kann deshalb keinen dritten Kontakt und keine geteilte Nummer.
--
-- Preis dieser Vereinheitlichung: Anschrift und E-Mail sind für Kontakte
-- technisch befüllbar. Datensparsamkeit ist hier also nur noch eine Regel der
-- Eingabemaske, nicht mehr strukturell erzwungen — anders als bei Demografie
-- (nur children) und Beruf (nur guardians), die weiterhin an der Rollentabelle
-- hängen und für andere Rollen gar nicht existieren.
CREATE TABLE contacts (
    id         uuid PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    notes      text,               -- z. B. "nur nachmittags erreichbar"
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text
);

-- relationship steht an der Verknüpfung, nicht am Kontakt: „Großmutter" gilt
-- relativ zum Kind, nicht absolut zur Person. Verknüpfung an das Kind und nicht
-- an die Familie, weil ein Kind vor der manuellen Familienzuordnung noch keine
-- Familie hat.
CREATE TABLE child_contacts (
    child_id     uuid NOT NULL REFERENCES children(id) ON DELETE CASCADE,
    contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    relationship text,               -- Freitext: "Großmutter", "Nachbarin" — keine Rechtsklassifizierung, daher kein CHECK
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   text,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    updated_by   text,
    PRIMARY KEY (child_id, contact_id)
);
CREATE INDEX ON child_contacts (contact_id);

-- ---------------------------------------------------------------------------
-- Audit-Spalten automatisch fortschreiben. In der Datenbank statt in der
-- Anwendung, damit kein Schreibpfad sie vergessen kann (idea/03) — sonst bleibt
-- updated_at für immer auf dem Einfüge-Zeitpunkt stehen und der Audit-Trail ist
-- wertlos.
--
-- Den Verursacher kennt nur die Anwendung. Sie setzt ihn einmal pro Transaktion
-- als Sitzungsvariable (SET LOCAL app.actor = '<oid>' / 'guardian:<uuid>' /
-- 'system:<job>'), der Trigger schreibt ihn in jede berührte Zeile. Fehlt die
-- Variable, bleibt der übergebene Wert stehen statt einen falschen zu erfinden.
--
-- Bewusst KEINE separate Änderungshistorie-Tabelle: kein aktueller Prozess
-- braucht mehr als „wer hat zuletzt geändert" (rules.md Abschnitt 1). Die vier
-- Spalten bleiben der Anknüpfungspunkt, falls doch einmal eine volle Historie
-- nötig wird.
-- ---------------------------------------------------------------------------

CREATE FUNCTION set_row_audit() RETURNS trigger AS $$
DECLARE
    actor text := current_setting('app.actor', true);
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := now();
        NEW.created_by := coalesce(actor, NEW.created_by);
    ELSE
        NEW.created_at := OLD.created_at;   -- unveränderlich
        NEW.created_by := OLD.created_by;
    END IF;
    NEW.updated_at := now();
    NEW.updated_by := coalesce(actor, NEW.updated_by);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON persons
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON organizations
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON phone_numbers
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON person_religious_data
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON families
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON children
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON family_guardians
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
CREATE TRIGGER set_row_audit BEFORE INSERT OR UPDATE ON child_contacts
    FOR EACH ROW EXECUTE FUNCTION set_row_audit();
