-- AGs (Domäne 6, zweiter Teil) — nichts zu bauen.
--
-- Das ist das Ergebnis dieser Domäne, und hier ausnahmsweise mangels Grundlage
-- statt aus einer Entscheidung. Es gibt keinen Soll-Block dazu; die beiden
-- Quellen sagen dasselbe:
--
--   * `prozesse.md` Abschnitt 20 — die Überschrift „20. AGs" und darunter der
--     eine Satz „Zukunftsprojekt, nichts Konkretes bekannt."; mehr steht dort
--     nicht.
--   * `grenzkarte.md`, „Je Domäne": eigene Entitäten „unbekannt", Querschnitt
--     „unbekannt", schreibt Stammdaten „vermutlich nein"; in den weißen Flecken
--     steht sie mit „nichts Konkretes bekannt" und dem Fälligkeitstermin
--     „offen".
--
-- Damit ist nichts belegt — weder ein Formular noch ein benannter Prozess
-- (rules.md Abschnitt 7) —, und geraten wird nicht. Eine Tabelle, die auf
-- Vermutungen beruht, wäre teurer als eine, die später entsteht: Nachrüsten ist
-- der vorgesehene Weg und nicht der Notnagel. Ein Beleg dafür steht in keinem
-- Block — der Satz ist die Linie dieses Schemas, kein Zitat.
--
-- Ein Anhaltspunkt für später, mehr nicht: Wenn AGs kommen, ähneln sie
-- vermutlich weder dem Betreuungsmodul (Modul × Wochentag über ein Schuljahr,
-- anmeldung-schema.sql) noch dem Ferientermin (Termin × Modul mit Platzzahl,
-- ferien-schema.sql) genug, um eine von beiden Strukturen mitzubenutzen —
-- „eine gemeinsame Termin-Entität wäre eine Abstraktion über drei Fälle, die
-- nichts teilen außer einem Datum" (grenzkarte.md). Was sie brauchen,
-- entscheidet der Block, der zuerst geschrieben wird.
--
-- Es gibt deshalb keine CREATE-Anweisung in dieser Datei. Das Prüfskript
-- daneben belegt genau das: dass nichts auf Verdacht entstanden ist.


-- ---------------------------------------------------------------------------
-- Offene Fragen an die Schule
-- ---------------------------------------------------------------------------
-- Keine, die diese Datei betrifft — und das steht in den Quellen selbst, nicht
-- in einer Auskunft daneben: `prozesse.md` Abschnitt 20 nennt die AGs
-- „Zukunftsprojekt, nichts Konkretes bekannt", grenzkarte.md führt sie unter
-- den weißen Flecken mit „nichts Konkretes bekannt" und der Fälligkeit „offen".
-- Beides heißt dasselbe: geplant ja, vorhanden nein. Solange keine läuft, gibt
-- es nichts zu erheben und keinen Ablauf zu beschreiben, also auch nichts zu
-- bauen — der weiße Fleck ist damit nicht geschlossen, er hält nur nichts auf.
-- Er schließt sich, wenn die erste AG ansteht: dann beginnt das mit einem
-- ausgefüllten Block 20 — wer anbietet, wer sich wie anmeldet, ob es Plätze und
-- einen Beitrag gibt — und nicht mit einer Tabelle auf Verdacht.
