-- Klassenbildung (Domäne 12) — nichts zu bauen.
--
-- Das ist das Ergebnis dieser Domäne, keine Auslassung. grenzkarte.md sagt es
-- selbst: „Klassenbildung (12) braucht keine eigene Tabelle … Die Domäne ist
-- damit eine Oberfläche, keine Datendomäne: eine Ansicht über alle Kinder einer
-- künftigen Klassenstufe mit Geschlecht, Wohnort und Geschwistern, aus der ein
-- Mensch `children.class_id` setzt."
--
-- Die heutige Liste für die neuen Klassen 1 und 5 verlangt fünf Angaben. Vier
-- davon stehen schon; die fünfte wird nicht erhoben:
--
--   * **Wohnort und Geschlecht** an `persons` — über `persons.address_id` bzw.
--     `persons.gender_id` (stammdaten-schema.sql).
--   * **Geschwister** folgen aus `children.family_id`: „wer an der Schule ist,
--     steht ohnehin fest" (05).
--   * **Klassenlehrer:in** als `classes.class_teacher_id` (stammdaten-schema.sql)
--     — genau eine je Klasse, so von der Schule entschieden.
--   * **Der Zusammensetzungswunsch** hat keine Spalte. Block 15 entscheidet
--     gegen ihn: „Die Gründe — Freundschaften, Förderbedarf, Ausgewogenheit —
--     bleiben außerhalb wie das Ranking in 07" (Schritt 2), und sein „Was dabei
--     erhoben wird" kennt ihn nicht. Die Ansicht zeigt ihn deshalb nicht; wer
--     den Wunsch kennt, ist der Mensch, der die Klasse setzt.
--
-- Was die Domäne schreibt, steht in Stammdaten. Sie legt die `classes`-Zeile
-- an — „Je Klasse Schulart, Startschuljahr und Zug …, die Klassenlehrkraft und
-- der Raum" (15, Schritt 1) — und sie setzt `children.class_id`, an ihre
-- Schulart gebunden durch den zusammengesetzten Fremdschlüssel
-- `fk_children_class` (rules.md Abschnitt 1). Die beiden Bedingungen aus Block
-- 15 stehen dort als Constraints: die Einschreibung
-- (`ck_children_class_needs_entry`) und die passende Schulart.
--
-- Die **Pflicht** daneben — „Je Kind seine Klasse (Pflicht, sobald beide
-- Bedingungen erfüllt sind)" — bekommt bewusst keinen Constraint. Sie ist über
-- die Zeile hinaus formuliert: Die zweite Bedingung ist die Existenzfrage „es
-- gibt eine Klasse, in die es passt", und die steht nicht in `children`. Im
-- selben Block steht zudem „Ein Kind ohne Klasse ist kein Fehler" (Sonderfälle)
-- — das externe Hortkind und der Warteplatz haben keine, der Wiederholer „steht
-- sichtbar ohne passende Klasse, bis die Schulleitung es umsetzt; gesperrt wird
-- nichts". Die Pflicht ist damit eine Ansicht, kein Constraint.
--
-- Fünf Dinge bekommen bewusst keine Spalte:
--
--   * Eine **Kapazität je Klasse**. „Wie viele Kinder in einer Klasse sitzen,
--     wird gezeigt, nicht geprüft — die Zielmarke von derzeit 25 steht so wenig
--     im System wie in 07."
--   * Die **Stufe und der Anzeigename einer Klasse**. „Stufe und Anzeigename
--     werden nicht erhoben, sondern gerechnet" — aus Schulart, Startjahr und
--     laufendem Schuljahr; `school_branches.first_grade_level` trägt dafür den
--     Anfang.
--   * Der **Zeitpunkt des Umsetzens**. Ein Klassenwechsel „ist dieselbe
--     Handlung wie das erste Setzen und braucht keinen eigenen Weg"; wann er
--     geschah, hält die Änderungsspur fest (querschnitt-schema.sql).
--   * Der **Zusammensetzungswunsch**, siehe oben — die eine Angabe der heutigen
--     Liste, die das Schema nicht trägt.
--   * Das **Ende eines Zuges**. „Wird eine Stufe geteilt oder zusammengelegt,
--     legt die Schulleitung einen Zug an oder lässt ihn auslaufen und setzt die
--     betroffenen Kinder um" (15, Sonderfälle) — eine Handlung ist davon nur
--     das Umsetzen. Ausgelaufen wird gerechnet: „eine Klasse, deren Stufe über
--     4 bzw. 10 hinausliefe, ist ausgelaufen und taucht in keiner laufenden
--     Ansicht mehr auf". Ein `is_active` oder ein Endejahr an `classes` wäre
--     ein zweiter Endezeitpunkt neben dem gerechneten (rules.md Abschnitt 1).
--     Der Preis ist benannt und getragen: Ein leergeräumter Zug bleibt bis zum
--     Ende seiner Kohorte in der Auswahl seiner Stufe stehen — ohne ein Kind
--     darin, und die Schulleitung, die ihn geräumt hat, weiß das.
--
-- Es gibt deshalb keine CREATE-Anweisung in dieser Datei. Das Prüfskript
-- daneben belegt, dass die vier verbliebenen Angaben stehen, dass weder der
-- Wunsch noch das Ende eines Zuges eine Spalte hat, dass die beiden Bedingungen
-- greifen und dass ein Kind ohne Klasse durchgeht.


-- ---------------------------------------------------------------------------
-- Offene Fragen an die Schule
-- ---------------------------------------------------------------------------
-- Keine. Block 15 lässt für diese Domäne nichts offen, was das Schema betrifft.
